//Dump Ghidra's decompiled C for every function splat knows about.
//
//REFERENCE ONLY. The output is never compiled and is never a source of
//truth -- see docs/GHIDRA.md for why. It exists to read large functions
//and to recover struct layouts, not to be pasted into src/.
//
//The one thing this script does that plain auto-analysis does not is
//take the function boundaries from OUR table instead of letting Ghidra
//guess them. Boundary detection is its weakest step on a stripped PS2
//ELF -- it mis-splits around branch-likely tails, alternate entry
//points and handwritten asm -- and we already know every boundary
//exactly from splat's `nonmatching <name>, <size>` headers.
//
//@category RAC1
import java.io.BufferedWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import ghidra.app.decompiler.DecompInterface;
import ghidra.app.decompiler.DecompileOptions;
import ghidra.app.decompiler.DecompileResults;
import ghidra.app.script.GhidraScript;
import ghidra.program.model.address.Address;
import ghidra.program.model.address.AddressSet;
import ghidra.program.model.listing.Function;
import ghidra.program.model.listing.Listing;
import ghidra.program.model.symbol.SourceType;

public class DumpDecompiled extends GhidraScript {

    @Override
    public void run() throws Exception {
        String[] args = getScriptArgs();
        if (args.length < 2) {
            println("usage: DumpDecompiled <functions.csv> <outDir>");
            return;
        }
        Path table = Paths.get(args[0]);
        Path outDir = Paths.get(args[1]);
        Files.createDirectories(outDir);

        Listing listing = currentProgram.getListing();
        Map<String, List<Function>> bySeg = new LinkedHashMap<String, List<Function>>();
        List<String> lines = Files.readAllLines(table, StandardCharsets.UTF_8);

        int made = 0;
        int failed = 0;
        for (int i = 1; i < lines.size(); i++) {
            String line = lines.get(i).trim();
            if (line.isEmpty()) {
                continue;
            }
            String[] f = line.split(",");
            if (f.length < 4) {
                continue;
            }
            String seg = f[0];
            String name = f[1];
            long vram = Long.decode(f[2]).longValue();
            long size = Long.decode(f[3]).longValue();

            try {
                Address start = toAddr(vram);
                AddressSet body = new AddressSet(start, start.add(size - 1));

                clearListing(body);
                disassemble(start);

                Function fn = listing.getFunctionAt(start);
                if (fn != null) {
                    removeFunction(fn);
                }
                fn = createFunction(start, name);
                if (fn == null) {
                    failed++;
                    continue;
                }
                fn.setBody(body);
                fn.setName(name, SourceType.USER_DEFINED);

                List<Function> list = bySeg.get(seg);
                if (list == null) {
                    list = new ArrayList<Function>();
                    bySeg.put(seg, list);
                }
                list.add(fn);
                made++;
            }
            catch (Exception e) {
                println("skip " + name + ": " + e.getMessage());
                failed++;
            }
        }
        println("functions defined: " + made + ", failed: " + failed);

        DecompInterface dec = new DecompInterface();
        dec.setOptions(new DecompileOptions());
        if (!dec.openProgram(currentProgram)) {
            println("decompiler did not open: " + dec.getLastMessage());
            return;
        }
        try {
            for (Map.Entry<String, List<Function>> e : bySeg.entrySet()) {
                Path out = outDir.resolve(e.getKey() + ".c");
                BufferedWriter w = Files.newBufferedWriter(out, StandardCharsets.UTF_8);
                try {
                    w.write("/*\n");
                    w.write(" * GENERATED by tools/ghidra/DumpDecompiled.java -- REFERENCE ONLY.\n");
                    w.write(" * Never compiled, never a source of truth. See docs/GHIDRA.md.\n");
                    w.write(" */\n\n");
                    int ok = 0;
                    for (Function fn : e.getValue()) {
                        if (monitor.isCancelled()) {
                            break;
                        }
                        w.write("/* ==== " + fn.getName() + " @ " + fn.getEntryPoint()
                                + " (" + fn.getBody().getNumAddresses() + " bytes) ==== */\n");
                        DecompileResults r = dec.decompileFunction(fn, 60, monitor);
                        if (r != null && r.decompileCompleted()) {
                            w.write(r.getDecompiledFunction().getC());
                            ok++;
                        }
                        else {
                            w.write("/* decompile failed: "
                                    + (r == null ? "no result" : r.getErrorMessage()) + " */\n");
                        }
                        w.write("\n");
                    }
                    println("wrote " + out + " (" + ok + "/" + e.getValue().size() + " decompiled)");
                }
                finally {
                    w.close();
                }
            }
        }
        finally {
            dec.dispose();
        }
    }
}
