/* Level 08 code following vendor; generated by tools/overlay_src.py, stubs replaced by C as functions are matched. */
#include "common.h"
#include "include_asm.h"

INCLUDE_ASM("asm/overlays", func_L08_002B9438);
INCLUDE_ASM("asm/overlays", func_L08_002B94B0);
INCLUDE_ASM("asm/overlays", func_L08_002D35E8);
INCLUDE_ASM("asm/overlays", func_L08_002D36F8);
INCLUDE_ASM("asm/overlays", func_L08_002D55E0);
INCLUDE_ASM("asm/overlays", func_L08_002D5FA8);
INCLUDE_ASM("asm/overlays", func_L08_002D68D0);
INCLUDE_ASM("asm/overlays", func_L08_002D6C58);
INCLUDE_ASM("asm/overlays", func_L08_002D7010);
INCLUDE_ASM("asm/overlays", func_L08_002D7758);
INCLUDE_ASM("asm/overlays", func_L08_002DB438);
INCLUDE_ASM("asm/overlays", func_L08_002DB468);
INCLUDE_ASM("asm/overlays", func_L08_002DB768);
INCLUDE_ASM("asm/overlays", func_L08_002DBD88);
INCLUDE_ASM("asm/overlays", func_L08_002DBF68);
INCLUDE_ASM("asm/overlays", func_L08_002DD128);
INCLUDE_ASM("asm/overlays", func_L08_002DD440);
INCLUDE_ASM("asm/overlays", func_L08_002DD4F8);
INCLUDE_ASM("asm/overlays", func_L08_002DD818);
INCLUDE_ASM("asm/overlays", func_L08_002DD9C0);
extern void func_00215F80(int, int);
extern int D_L08_001B0FB0[];

void func_L08_002DDB68(char *moby) {
    char *data = *(char **)(moby + 0x78);
    if (*(float *)(data + 0x104) > 0.9f) {
        func_00215F80(0xA, 0x1F4D);
    } else if (*(int *)(data + 0x120) == D_L08_001B0FB0[*(int *)(data + 0x80)]) {
        func_00215F80(0xA, 0x1F50);
    } else if (*(int *)(data + 0x120) == D_L08_001B0FB0[*(int *)(data + 0x88)]) {
        func_00215F80(0xA, 0x1F4F);
    } else {
        func_00215F80(0xA, 0x1F4E);
    }
}
INCLUDE_ASM("asm/overlays", func_L08_002DDC18);
INCLUDE_ASM("asm/overlays", func_L08_002DDD20);
INCLUDE_ASM("asm/overlays", func_L08_002DE738);
INCLUDE_ASM("asm/overlays", func_L08_002DF750);
INCLUDE_ASM("asm/overlays", func_L08_002DF758);
INCLUDE_ASM("asm/overlays", func_L08_002DF8A0);
INCLUDE_ASM("asm/overlays", func_L08_002DFBC0);
INCLUDE_ASM("asm/overlays", func_L08_002E0008);
