/* Level 16 code following help; generated by tools/overlay_src.py, stubs replaced by C as functions are matched. */
#include "common.h"
#include "include_asm.h"

INCLUDE_ASM("asm/overlays", func_L16_00227818);
extern void func_0022C7E0(void);
extern int D_0015EE84_m __asm__("D_0015EE84") MACRO_ADDR;
extern void func_L00_0028B8F8(void);
extern void func_L00_0028A5A8(void);
extern void func_0022C870(void);
extern void func_00234C98(int, long);
extern int D_0015EF88 MACRO_ADDR;
void func_L16_0023A530(void) {
    func_0022C7E0();
    if (D_0015EE84_m == 16) {
        func_L00_0028B8F8();
    } else {
        func_L00_0028A5A8();
    }
    func_0022C870();
    func_00234C98(0x47, 0x5360B);
    func_00234C98(0x4E, 0x1000000 | (D_0015EF88 >> 13));
}
