/* Level 13 code following vendor; generated by tools/overlay_src.py, stubs replaced by C as functions are matched. */
#include "common.h"
#include "include_asm.h"

INCLUDE_ASM("asm/overlays", func_L13_0030CAE0);
INCLUDE_ASM("asm/overlays", func_L13_0030D028);
INCLUDE_ASM("asm/overlays", func_L13_0030D2A8);
INCLUDE_ASM("asm/overlays", func_L13_0030D318);
INCLUDE_ASM("asm/overlays", func_L13_0030D468);
INCLUDE_ASM("asm/overlays", func_L13_0030D528);
INCLUDE_ASM("asm/overlays", func_L13_0030D600);
INCLUDE_ASM("asm/overlays", func_L13_0030D880);
INCLUDE_ASM("asm/overlays", func_L13_0030E280);
