/* Level 05 (Rilgar) code following partupd; generated by tools/overlay_src.py, stubs replaced by C as functions are matched. */
#include "common.h"
#include "include_asm.h"

INCLUDE_ASM("asm/overlays", func_L05_0029CA28);
INCLUDE_ASM("asm/overlays", func_L05_0029CCB8);
