/* Level 17 (Drek's Fleet) code following vendor; generated by tools/overlay_src.py, stubs replaced by C as functions are matched. */
#include "common.h"
#include "include_asm.h"

INCLUDE_ASM("asm/overlays", func_L17_002AA068);
INCLUDE_ASM("asm/overlays", func_L17_002AA880);
INCLUDE_ASM("asm/overlays", func_L17_002CC788);
INCLUDE_ASM("asm/overlays", func_L17_002CD088);
INCLUDE_ASM("asm/overlays", func_L17_002CD1B0);
INCLUDE_ASM("asm/overlays", func_L17_002D8CC8);
INCLUDE_ASM("asm/overlays", func_L17_002D91C8);
INCLUDE_ASM("asm/overlays", func_L17_002DD8D0);
INCLUDE_ASM("asm/overlays", func_L17_002EA2C8);
INCLUDE_ASM("asm/overlays", func_L17_002EA8F8);
INCLUDE_ASM("asm/overlays", func_L17_002EAFC8);
INCLUDE_ASM("asm/overlays", func_L17_002EC5D0);
INCLUDE_ASM("asm/overlays", func_L17_002EC7D8);
INCLUDE_ASM("asm/overlays", func_L17_002ED258);
INCLUDE_ASM("asm/overlays", func_L17_002ED498);
INCLUDE_ASM("asm/overlays", func_L17_002EDAF0);
INCLUDE_ASM("asm/overlays", func_L17_002EDC40);
INCLUDE_ASM("asm/overlays", func_L17_002EDE50);
INCLUDE_ASM("asm/overlays", func_L17_002EEB08);
INCLUDE_ASM("asm/overlays", func_L17_002EFA20);
INCLUDE_ASM("asm/overlays", func_L17_002EFDC0);
INCLUDE_ASM("asm/overlays", func_L17_002F04D0);
INCLUDE_ASM("asm/overlays", func_L17_002F0580);
INCLUDE_ASM("asm/overlays", func_L17_002F0678);
