/* Level 02 (Aridia) code following hud; generated by tools/overlay_src.py, stubs replaced by C as functions are matched. */
#include "common.h"
#include "include_asm.h"

INCLUDE_ASM("asm/overlays", func_L02_0023D600);
INCLUDE_ASM("asm/overlays", func_L02_0023D6E0);
