/* Level 00 (Veldin) code following vendor; generated by tools/overlay_src.py, stubs replaced by C as functions are matched. */
#include "common.h"
#include "include_asm.h"

INCLUDE_ASM("asm/overlays", func_L00_002DB278);
INCLUDE_ASM("asm/overlays", func_L00_002E1E38);
INCLUDE_ASM("asm/overlays", func_L00_002E2038);
INCLUDE_ASM("asm/overlays", func_L00_002E2B28);
INCLUDE_ASM("asm/overlays", func_L00_002E2F58);
INCLUDE_ASM("asm/overlays", func_L00_002E3128);
INCLUDE_ASM("asm/overlays", func_L00_002E32A0);
INCLUDE_ASM("asm/overlays", func_L00_002E4CB0);
