/* Level 18 (Veldin (return)) code following vendor; generated by tools/overlay_src.py, stubs replaced by C as functions are matched. */
#include "common.h"
#include "include_asm.h"

INCLUDE_ASM("asm/overlays", func_L18_002F9D48);
INCLUDE_ASM("asm/overlays", func_L18_002FABE0);
INCLUDE_ASM("asm/overlays", func_L18_002FAEF8);
INCLUDE_ASM("asm/overlays", func_L18_002FB080);
INCLUDE_ASM("asm/overlays", func_L18_002FB318);
INCLUDE_ASM("asm/overlays", func_L18_002FB6B0);
INCLUDE_ASM("asm/overlays", func_L18_002FBAA0);
INCLUDE_ASM("asm/overlays", func_L18_002FBB88);
INCLUDE_ASM("asm/overlays", func_L18_002FBCE8);
INCLUDE_ASM("asm/overlays", func_L18_002FBD40);
INCLUDE_ASM("asm/overlays", func_L18_002FC188);
INCLUDE_ASM("asm/overlays", func_L18_002FD058);
INCLUDE_ASM("asm/overlays", func_L18_002FD5C0);
INCLUDE_ASM("asm/overlays", func_L18_002FD9A0);
INCLUDE_ASM("asm/overlays", func_L18_002FDB28);
INCLUDE_ASM("asm/overlays", func_L18_002FDCA0);
INCLUDE_ASM("asm/overlays", func_L18_002FDCC4);
INCLUDE_ASM("asm/overlays", func_L18_002FDD20);
INCLUDE_ASM("asm/overlays", func_L18_002FDF58);
