/* Level 02 code following vendor; generated by tools/overlay_src.py, stubs replaced by C as functions are matched. */
#include "common.h"
#include "include_asm.h"

INCLUDE_ASM("asm/overlays", func_L02_002E21F8);
INCLUDE_ASM("asm/overlays", func_L02_002E2D88);
INCLUDE_ASM("asm/overlays", func_L02_002E33F0);
INCLUDE_ASM("asm/overlays", func_L02_002E3660);
INCLUDE_ASM("asm/overlays", func_L02_002EB480);
extern void func_L02_002A59D8(float);
extern void func_L02_002EB480(void);
extern void func_001F49B0(void (*)(void), void *);

void func_L02_002EB5D0(unsigned char *moby) {
    switch (moby[0x20]) {
    case 0:
        func_L02_002A59D8(0.16666667f);
        moby[0x20] = 1;
        moby[0x30] = 0xFF;
        break;
    case 1:
        func_001F49B0(func_L02_002EB480, moby);
        break;
    }
}
INCLUDE_ASM("asm/overlays", func_L02_002ED358);
INCLUDE_ASM("asm/overlays", func_L02_002ED660);
INCLUDE_ASM("asm/overlays", func_L02_002EFCC8);
INCLUDE_ASM("asm/overlays", func_L02_002F0458);
INCLUDE_ASM("asm/overlays", func_L02_002F9E40);
INCLUDE_ASM("asm/overlays", func_L02_002F9E50);
