/* Shared code following help; generated by tools/overlay_src.py, stubs replaced by C as functions are matched. */
#include "common.h"
#include "include_asm.h"

INCLUDE_ASM("asm/overlays", func_L00_00203E98);
INCLUDE_ASM("asm/overlays", func_L00_00203ED8);
INCLUDE_ASM("asm/overlays", func_L00_00203F08);
extern char D_L00_00179510[] NOT_SDA;
extern unsigned char D_0014171B[] NOT_SDA;
extern void func_001FF560(int);
int func_L00_00203F20(int a, int b) {
    int c;
    unsigned char *h;
    if (*(int *)D_L00_00179510 != 0) return 0;
    c = *(int *)(D_L00_00179510 + 0x24);
    if (c != -1) return 0;
    h = D_0014171B + 0x100B5;
    if (*(int *)(h + 0x50) != 0) return 0;
    if (*(int *)(h + 0x1C) != c) return 0;
    if (*(unsigned short *)(D_0014171B + 0x34D + b * 8) == 0xFFFF) return 0;
    *(int *)(D_L00_00179510 + 0x28) = b;
    *(int *)(D_L00_00179510 + 0x24) = a;
    func_001FF560(a);
    return 1;
}
extern char D_L00_00179510[] NOT_SDA;
extern char *D_L00_0015F740 MACRO_ADDR;
extern unsigned char D_0014171B[] NOT_SDA;
void func_L00_00203FB8(void) {
    if (*(int *)(D_L00_00179510) != 0) {
        int v = *(int *)((char *)(*(int *)(D_L00_00179510 + 0x20) << 4) + (int)D_L00_0015F740 + 8);
        if (v != -1) {
            char *g = (char *)D_0014171B + 0x100B5;
            if (v == *(short *)(g + 0x54) - 0x7530) {
                if ((unsigned)(*(unsigned short *)(g + 0x5A) - 6) >= 2)
                    *(short *)(g + 0x5A) = 5;
            }
        }
        *(int *)(D_L00_00179510) = 0;
        *(int *)(D_L00_00179510 + 0x24) = -1;
        *(int *)(D_L00_00179510 + 0x20) = -1;
        *(int *)(D_L00_00179510 + 4) = 0;
    }
}
INCLUDE_ASM("asm/overlays", func_L00_00204040);
extern char D_L00_00179510[] NOT_SDA;
extern int func_001F9850(int);
extern void func_L00_00203E98(void);
void func_L00_00204130(void) {
    char *g = D_L00_00179510;
    if (*(short *)(g + 0x38) == 0) {
        *(short *)(g + 0x38) = 1;
        *(int *)(g + 0x3C) = func_001F9850(0x3C);
        func_L00_00203E98();
        if (*(int *)g == 0) *(int *)g = 8;
    }
}
INCLUDE_ASM("asm/overlays", func_L00_00204190);
INCLUDE_ASM("asm/overlays", func_L00_00205110);
INCLUDE_ASM("asm/overlays", func_L00_00205158);
INCLUDE_ASM("asm/overlays", func_L00_00205278);
extern unsigned char D_0013F450[] NOT_SDA;
extern unsigned char D_0014171B[] NOT_SDA;
extern void func_L00_00232EA8(void);
extern void func_L00_00222B80(int, int);
void func_L00_00205598(void) {
    char *g = D_0013F450;
    *(float *)(g + 0x220) = 0.8f;
    *(float *)(g + 0x234) = 0.45f;
    *(float *)(g + 0x228) = 0.8f;
    *(float *)(g + 0x224) = 0.7f;
    *(float *)(g + 0x22C) = 0.7f;
    *(unsigned char *)(g + 0x22CB) = 0;
    *(int *)(g + 0x2084) = 0;
    *(int *)(D_0014171B + 0x4D) = 0;
    *(float *)(g + 0xA94) = 1.0f;
    func_L00_00232EA8();
    func_L00_00222B80(0, 1);
}
typedef struct { char pad[0x24]; int v; char pad2[0x24]; } Rec;
extern Rec D_L00_00179BC0[] NOT_SDA;
extern int func_L00_0020DB30(int);

int func_L00_00205618(int a) {
    char *g = (char *)D_0013F450;
    int c = *(unsigned char *)(g + 0x20A4);
    if (c == 2 || (c < 3 ? c == 1 : c == 3)) {
        return 0;
    }
    {
        char *g2 = (char *)D_0013F450;
        if (*(int *)(g2 + 0x22A8) == 1) {
            return 0x54;
        }
        if (*(unsigned char *)(g2 + 0x12E2) != 0) {
            return 0x6E;
        }
        if (a == 0) {
            return 0;
        }
        if (*(unsigned char *)(g2 + 0x20A8) == 0) {
            return 0;
        }
        if (*(unsigned char *)(g2 + 0x20AA) == 0) {
            return 0;
        }
        if (*(short *)(g2 + 0x22C8) != 0) {
            return 0;
        }
    }
    {
        int i = func_L00_0020DB30(0);
        return D_L00_00179BC0[i].v;
    }
}
INCLUDE_ASM("asm/overlays", func_L00_002056D0);
INCLUDE_ASM("asm/overlays", func_L00_002056D8);
INCLUDE_ASM("asm/overlays", func_L00_00205728);
INCLUDE_ASM("asm/overlays", func_L00_00205754);
INCLUDE_ASM("asm/overlays", func_L00_00205768);
INCLUDE_ASM("asm/overlays", func_L00_00205778);
INCLUDE_ASM("asm/overlays", func_L00_00205780);
INCLUDE_ASM("asm/overlays", func_L00_00205B00);
INCLUDE_ASM("asm/overlays", func_L00_00205B50);
INCLUDE_ASM("asm/overlays", func_L00_00205C18);
INCLUDE_ASM("asm/overlays", func_L00_00205CC0);
INCLUDE_ASM("asm/overlays", func_L00_00205FF0);
extern unsigned char D_0013D5DD[] NOT_SDA;
extern unsigned char D_0013E633[] NOT_SDA;
extern void func_L00_00236750(void);
extern void func_L00_0023ABB0(void);
extern void func_L00_0023AC68(void);
extern int func_001FFB38(int, int, int, int, int, int, int);

void func_L00_002064C0(void) {
    char *g;
    if (D_0013D5DD[6] == 0) {
        *(int *)(D_0013E633 + 0x2E65) = 0;
        return;
    }
    g = (char *)D_0013F450;
    if (*(float *)(g + 0x2044) < 20.0f && *(int *)(g + 0x2040) != 0) {
        *(int *)(g + 0x2048) = 1;
    } else {
        char *g3 = (char *)D_0013F450;
        *(int *)(g3 + 0x2048) = 0;
    }
    {
        char *g2 = (char *)D_0013F450;
        *(float *)(g2 + 0x2044) = 100000.0f;
        *(int *)(g2 + 0x2040) = 0;
        if (*(int *)(g2 + 0x2048) != 0) {
            func_001FFB38(7, 0x753A, (int)func_L00_00236750, (int)func_L00_0023ABB0, (int)func_L00_0023AC68, (int)(g2 + 0x2048), 1);
        }
    }
}
INCLUDE_ASM("asm/overlays", func_L00_00206578);
INCLUDE_ASM("asm/overlays", func_L00_00206698);
INCLUDE_ASM("asm/overlays", func_L00_00206808);
INCLUDE_ASM("asm/overlays", func_L00_002068C8);
INCLUDE_ASM("asm/overlays", func_L00_00207220);
INCLUDE_ASM("asm/overlays", func_L00_00207310);
INCLUDE_ASM("asm/overlays", func_L00_00207418);
INCLUDE_ASM("asm/overlays", func_L00_002076E8);
void func_L00_002078E0(void) {
    int i, j;
    char *g = (char *)D_0013F450;
    for (i = 0; i < 7; i++) {
        for (j = 0; j < 2; j++) {
            char *e = g + i * 0x50;
            int p = *(int *)(e + 0x1090);
            if (j == 1) {
                p = *(int *)(e + 0x1094);
            }
            if (p != 0) {
                *(long *)(p + 0x38) = *(long *)(*(int *)(g + 0x2080) + 0x38);
            }
        }
    }
}
INCLUDE_ASM("asm/overlays", func_L00_00207948);
INCLUDE_ASM("asm/overlays", func_L00_00207A48);
INCLUDE_ASM("asm/overlays", func_L00_00207CC0);
INCLUDE_ASM("asm/overlays", func_L00_00207EC0);
extern unsigned char D_0013F450[] NOT_SDA;
extern float D_0015EE6C MACRO_ADDR;
extern void func_L00_00263BF8(int, char *, char *, float, float, float);
void func_L00_00208000(void) {
    char *g = D_0013F450;
    if (*(int *)(g + 0x2084) == 0x7F) {
        func_L00_00263BF8(*(int *)(g + 0x2080), g + 0x6B0, g + 0x6B4, 0.1745329201221466f, D_0015EE6C * 1.5707963705062866f, D_0015EE6C * 2.094395160675049f);
    }
}
INCLUDE_ASM("asm/overlays", func_L00_00208070);
INCLUDE_ASM("asm/overlays", func_L00_00208260);
extern unsigned char D_0013F450[] NOT_SDA;
extern void func_001F49B0(void *, int);
extern void func_L00_00208358(void);
void func_L00_00208318(void) {
    char *g = D_0013F450;
    if (*(short *)(g + 0x1EB2) == 0) {
        *(short *)(g + 0x1EB2) = 1;
        func_001F49B0(func_L00_00208358, *(int *)(g + 0x2080));
    }
}
INCLUDE_ASM("asm/overlays", func_L00_00208358);
INCLUDE_ASM("asm/overlays", func_L00_00208650);
INCLUDE_ASM("asm/overlays", func_L00_002086C8);
INCLUDE_ASM("asm/overlays", func_L00_00208E98);
INCLUDE_ASM("asm/overlays", func_L00_00209088);
INCLUDE_ASM("asm/overlays", func_L00_002091D8);
extern u8 D_0013F450[] NOT_SDA;

extern f32 func_00214D28(f32 *p, f32 target, f32 maxstep);

f32 func_L00_00209598(f32 a, f32 b, f32 c, f32 d)
{
    u8 *g = D_0013F450;
    f32 thresh = *(f32 *)(g + 0xAA8);
    f32 step;
    f32 negone = -1.0f;

    if (thresh < a) {
        step = a - thresh;
    } else {
        s32 flag = *(s32 *)(g + 0xA9C);
        f32 rate = 2.0f;

        if (flag == 0) {
            rate = 0.5f / *(f32 *)(g + 0xA94);
        }

        {
            void *obj = *(void **)(g + 0x2080);
            s32 idx = *(u8 *)((u8 *)obj + 0x53);
            u8 *arr = *(u8 **)((u8 *)obj + 0x24);
            void *entry = *(void **)(arr + (idx << 2) + 0x48);
            s32 cnt = *(u8 *)((u8 *)entry + 0x10);
            step = a + (rate * (f32)cnt - thresh);
        }
    }

    if (b > 0.0f) {
        u8 *g2 = D_0013F450;
        f32 rate2 = *(f32 *)(g2 + 0xA94);

        if (*(s32 *)(g2 + 0xA9C) != 0) {
            void *obj2 = *(void **)(g2 + 0x2080);
            rate2 = *(f32 *)(*(void **)((u8 *)obj2 + 0x6C));
        }

        {
            f32 target = c * step;
            f32 speed = b * rate2;
            f32 result = target / speed;

            if (d == negone) {
                *(f32 *)(g2 + 0xA90) = result;
                return negone;
            }
            return func_00214D28((f32 *)(g2 + 0xA90), result, d);
        }
    }

    return 0.0f;
}
extern unsigned char D_0013E633[] NOT_SDA;
extern int func_001FA898(float);
extern float func_L00_002001D8(void *, float);

float func_L00_00209690(float *a, int n) {
    char buf[16] __attribute__((aligned(16)));
    char *d = (char *)D_0013E633 + 0xE1D;
    int i = func_001FA898(*(float *)(d + 0xAA8));
    int m = n - 1;
    int p = (i + m) % n;
    float w;
    if (*(int *)(d + 0xA98) & 2) {
        p = m;
    }
    w = func_L00_002001D8(buf, *(float *)(d + 0xAA8));
    return w * a[i] + (*(float *)(d + 0xAAC) - w) * a[p];
}
INCLUDE_ASM("asm/overlays", func_L00_00209748);
typedef float V[4] __attribute__((aligned(16)));

extern void func_001F9BC0(float *);
extern void func_L00_00209748(float *, float, float, float);

/* Builds a {0,0,0.6,0} param vector and forwards it (plus the caller's
   position) to func_L00_00209748. */
void func_L00_00209850(float x, float y, float z) {
    V buf;

    func_001F9BC0(buf);
    buf[2] = 0.6f;
    func_L00_00209748(buf, x, y, z);
}
typedef struct { int w[9]; } T;
extern T D_L00_001E7F90;
extern unsigned char D_0013E633[] NOT_SDA;
extern void func_L00_00250928(int, int, void *, void *);
void func_L00_002098B8(int a) {
    T t;
    if (a == 0) a = *(int *)(D_0013E633 + 0x2E9D);
    t = D_L00_001E7F90;
    func_L00_00250928(a, 9, &t, D_0013E633 + 0x18DD);
}
INCLUDE_ASM("asm/overlays", func_L00_00209940);
INCLUDE_ASM("asm/overlays", func_L00_00209BB8);
INCLUDE_ASM("asm/overlays", func_L00_00209CB0);
INCLUDE_ASM("asm/overlays", func_L00_00209EC0);
INCLUDE_ASM("asm/overlays", func_L00_0020A0B8);
INCLUDE_ASM("asm/overlays", func_L00_0020A320);
INCLUDE_ASM("asm/overlays", func_L00_0020A540);
INCLUDE_ASM("asm/overlays", func_L00_0020A858);
INCLUDE_ASM("asm/overlays", func_L00_0020A8B8);
INCLUDE_ASM("asm/overlays", func_L00_0020A990);
INCLUDE_ASM("asm/overlays", func_L00_0020AB78);
INCLUDE_ASM("asm/overlays", func_L00_0020ABB8);
INCLUDE_ASM("asm/overlays", func_L00_0020B060);
INCLUDE_ASM("asm/overlays", func_L00_0020B310);
INCLUDE_ASM("asm/overlays", func_L00_0020B850);
INCLUDE_ASM("asm/overlays", func_L00_0020BC30);
extern void func_L00_002111E8(void);
void func_L00_0020BFA8(void) {
    if (*(unsigned char *)(D_0013F450 + 0x20A4) == 3) {
        func_L00_002111E8();
    }
}
INCLUDE_ASM("asm/overlays", func_L00_0020BFD8);
INCLUDE_ASM("asm/overlays", func_L00_0020C568);
