/* Shared code following help; generated by tools/overlay_src.py, stubs replaced by C as functions are matched. */
#include "common.h"
#include "include_asm.h"

INCLUDE_ASM("asm/overlays", func_L00_0020CDF0);
INCLUDE_ASM("asm/overlays", func_L00_0020D3A0);
INCLUDE_ASM("asm/overlays", func_L00_0020D5F0);
extern void func_L00_00233EE0(float *, float, float, float);

/* OUT = the camera-space point (0.3, 0, 1.34) in world space
   (func_L00_00233EE0). */
void func_L00_0020D990(float *out) {
    func_L00_00233EE0(out, 0.3f, 0.0f, 1.34f);
}
INCLUDE_ASM("asm/overlays", func_L00_0020D9C8);
INCLUDE_ASM("asm/overlays", func_L00_0020DAF8);
INCLUDE_ASM("asm/overlays", func_L00_0020DB30);
extern int func_L00_0020DB30(int);

/* Whether func_L00_0020DB30(ARG) is one of 10, 17, 20 or 25. */
int func_L00_0020DB68(int arg) {
    int v = func_L00_0020DB30(arg);

    if (v == 0x11 || v == 10 || v == 0x14 || v == 0x19) {
        return 1;
    }
    return 0;
}
INCLUDE_ASM("asm/overlays", func_L00_0020DBB0);
INCLUDE_ASM("asm/overlays", func_L00_0020DBD8);
INCLUDE_ASM("asm/overlays", func_L00_0020DC00);
INCLUDE_ASM("asm/overlays", func_L00_0020DC50);
INCLUDE_ASM("asm/overlays", func_L00_0020DC68);
INCLUDE_ASM("asm/overlays", func_L00_0020DCB4);
extern char D_0013F450[];

typedef struct {
    char pad0[0x2128];
    float ring[32];
    int head;
    int count;
} RingBlock;

/* The value BACK entries ago (at most 31, and at most the entry count
   +0x21AC) in the 32-float ring at D_0013F450 + 0x2128 whose newest
   entry is +0x21A8. The ring as a struct array gives retail's base-first
   index add. */
float func_L00_0020DCF0(int back) {
    RingBlock *b = (RingBlock *)D_0013F450;
    int n = back < 32 ? back : 31;

    if (b->count < n) {
        n = b->count;
    }
    return b->ring[(b->head - n + 31) % 32];
}
INCLUDE_ASM("asm/overlays", func_L00_0020DD48);
INCLUDE_ASM("asm/overlays", func_L00_0020DF90);
INCLUDE_ASM("asm/overlays", func_L00_0020E0A8);
INCLUDE_ASM("asm/overlays", func_L00_0020E100);
INCLUDE_ASM("asm/overlays", func_L00_0020E3B8);
INCLUDE_ASM("asm/overlays", func_L00_0020E9F8);
INCLUDE_ASM("asm/overlays", func_L00_0020EB60);
INCLUDE_ASM("asm/overlays", func_L00_0020ED30);
INCLUDE_ASM("asm/overlays", func_L00_0020EDC0);
INCLUDE_ASM("asm/overlays", func_L00_0020F118);
INCLUDE_ASM("asm/overlays", func_L00_0020F750);
INCLUDE_ASM("asm/overlays", func_L00_0020F7F8);
INCLUDE_ASM("asm/overlays", func_L00_0020FC18);
INCLUDE_ASM("asm/overlays", func_L00_00210340);
extern int func_001F9850(int);

/* For events 9, 11, 13, 16 and 23: sets the short at D_0013F450 +
   0x22CE to 3 and +0x1DC to func_001F9850(70). */
void func_L00_00210418(int id) {
    char *base;

    switch (id) {
    case 9:
    case 11:
    case 13:
    case 16:
    case 23:
        base = D_0013F450;
        *(short *)(base + 0x22CE) = 3;
        *(short *)(base + 0x1DC) = func_001F9850(0x46);
        break;
    }
}
/* For events 9, 11, 13-16, 18, 19, 22, 23 and 26: sets the short at
   D_0013F450 + 0x1DA to func_001F9850(70). */
void func_L00_00210478(int id) {
    switch (id) {
    case 9:
    case 11:
    case 13:
    case 14:
    case 15:
    case 16:
    case 18:
    case 19:
    case 22:
    case 23:
    case 26:
        *(short *)(D_0013F450 + 0x1DA) = func_001F9850(0x46);
        break;
    }
}
INCLUDE_ASM("asm/overlays", func_L00_002104C8);
INCLUDE_ASM("asm/overlays", func_L00_00210558);
INCLUDE_ASM("asm/overlays", func_L00_00210E00);
INCLUDE_ASM("asm/overlays", func_L00_00210FE0);
INCLUDE_ASM("asm/overlays", func_L00_002110C0);
INCLUDE_ASM("asm/overlays", func_L00_002111E8);
extern void func_L00_001FF500(float *, float *, float);

/* With EACH, scales V's x and y by S and z by Z; otherwise scales its xy
   to length S (func_L00_001FF500) and sets z to Z. */
void func_L00_00211338(float *v, int each, float s, float z) {
    if (each) {
        v[0] *= s;
        v[1] *= s;
        v[2] *= z;
    } else {
        func_L00_001FF500(v, v, s);
        v[2] = z;
    }
}
INCLUDE_ASM("asm/overlays", func_L00_002113A0);
INCLUDE_ASM("asm/overlays", func_L00_00211908);
INCLUDE_ASM("asm/overlays", func_L00_00211A18);
INCLUDE_ASM("asm/overlays", func_L00_00211A38);
INCLUDE_ASM("asm/overlays", func_L00_00211D28);
extern float func_001F9CE8(void *);

/* The xy length of the vector at D_0013F450 + 0x1D20, capped at 1. */
float func_L00_00211EE8(void) {
    float len = func_001F9CE8(D_0013F450 + 0x1D20);

    if (1.0f < len) {
        len = 1.0f;
    }
    return len;
}
INCLUDE_ASM("asm/overlays", func_L00_00211F28);
INCLUDE_ASM("asm/overlays", func_L00_00211F68);
INCLUDE_ASM("asm/overlays", func_L00_00211F80);
INCLUDE_ASM("asm/overlays", func_L00_002122A0);
INCLUDE_ASM("asm/overlays", func_L00_002123B0);
INCLUDE_ASM("asm/overlays", func_L00_00212430);
INCLUDE_ASM("asm/overlays", func_L00_002124E8);
INCLUDE_ASM("asm/overlays", func_L00_00212550);
INCLUDE_ASM("asm/overlays", func_L00_002125F0);
INCLUDE_ASM("asm/overlays", func_L00_00212740);
extern float func_001F9F90(float);
extern float func_001F9FA8(float);
extern void func_001FA218(void *, void *);
extern void func_001F9EE8(void *, void *, void *);
extern void func_00215C00(void *, float, float, float);

/* D_0013E633 + 0xE1D lands on D_0013F450 (see src/game/camera.c). */
extern char D_0013F450[];

/* Builds a direction vector into D_0013F450+0xE0: either func_00215C00's
   spherical formula from D_0013F450's +0x194 radius, the clamped angle
   arg0 (falling back to +0x98 above pi) and +0x2E4, or, when +0x20B3 is
   set, a flat vector (r,0,0) rotated by the matrix func_001FA218 builds
   from the +0x2080 table's +0x40 axis. */
void func_L00_00212790(float arg0) {
    char *g = D_0013F450;
    float y;
    float r;
    float out[4];

    y = *(float *)(g + 0x98);
    if (arg0 <= 3.14159274f) {
        y = arg0;
    }
    r = *(float *)(g + 0x194);

    if (*(unsigned char *)(g + 0x20B3) != 0) {
        float matrix[16];
        float vec[4];

        vec[0] = func_001F9F90(0.0f) * r;
        vec[1] = func_001F9FA8(0.0f) * r;
        vec[2] = 0.0f;

        func_001FA218(matrix, *(char **)(g + 0x2080) + 0x40);
        func_001F9EE8(vec, vec, matrix);

        qcopy(out, vec);
    } else {
        func_00215C00(out, r, y, *(float *)(g + 0x2E4));
    }

    qcopy(D_0013F450 + 0xE0, out);
}
INCLUDE_ASM("asm/overlays", func_L00_00212878);
INCLUDE_ASM("asm/overlays", func_L00_002129D0);
INCLUDE_ASM("asm/overlays", func_L00_00212D70);
INCLUDE_ASM("asm/overlays", func_L00_00212E70);
INCLUDE_ASM("asm/overlays", func_L00_002136A8);
INCLUDE_ASM("asm/overlays", func_L00_00213970);
INCLUDE_ASM("asm/overlays", func_L00_00213A08);
INCLUDE_ASM("asm/overlays", func_L00_00213A60);
/*
 * Advances a 16-item spawn queue: for each slot, ask
 * func_L00_00213A60(i) to process it; stop early once it reports done
 * (returns 1). Otherwise copy the next entry from a 32-item circular
 * table (D_0013F450 + 0x1B00) into the working record at
 * D_0013F450 + 0x80, decrementing the countdown at +0x21B4 and
 * stepping the circular index at +0x21B0 backwards (mod 32) once every
 * two slots.
 *
 * D_0013F450 is D_0013E633 + 0xE1D, the big shared blob already declared
 * this way in src/game/camera.c and src/game/pause.c.
 */
extern char D_0013F450[];
extern int func_L00_00213A60(int index);

typedef struct {
    int x, y, z, w;
} Quad;

void func_L00_00213E60(void) {
    Quad *dst = (Quad *)(D_0013F450 + 0x80);
    Quad *table = (Quad *)((char *)dst + 0x1A80);
    int i;

    for (i = 0; i < 16; i++) {
        char *base;

        if (func_L00_00213A60(i) == 1)
            return;

        base = D_0013F450;
        if (*(int *)(base + 0x21B4) >= 2) {
            (*(int *)(base + 0x21B4))--;
            *(int *)(base + 0x21B0) = (*(int *)(base + 0x21B0) + 31) % 32;
        }
        qcopy(dst, &table[*(int *)(base + 0x21B0)]);
    }
}
INCLUDE_ASM("asm/overlays", func_L00_00213F38);
INCLUDE_ASM("asm/overlays", func_L00_002144A0);
INCLUDE_ASM("asm/overlays", func_L00_00214520);
INCLUDE_ASM("asm/overlays", func_L00_002147C0);
