/* Shared code following help; generated by tools/overlay_src.py, stubs replaced by C as functions are matched. */
#include "common.h"
#include "include_asm.h"

INCLUDE_ASM("asm/overlays", func_L01_002274A8);
INCLUDE_ASM("asm/overlays", func_L01_002283E0);
INCLUDE_ASM("asm/overlays", func_L01_00228598);
INCLUDE_ASM("asm/overlays", func_L01_00228E08);
INCLUDE_ASM("asm/overlays", func_L01_002293D0);
INCLUDE_ASM("asm/overlays", func_L01_0022D340);
INCLUDE_ASM("asm/overlays", func_L01_0022D688);
INCLUDE_ASM("asm/overlays", func_L01_0022DE30);
INCLUDE_ASM("asm/overlays", func_L01_00231960);
INCLUDE_ASM("asm/overlays", func_L01_00231A68);
INCLUDE_ASM("asm/overlays", func_L01_00231B98);
INCLUDE_ASM("asm/overlays", func_L01_002320F8);
INCLUDE_ASM("asm/overlays", func_L01_002328A8);
INCLUDE_ASM("asm/overlays", func_L01_00232F90);
INCLUDE_ASM("asm/overlays", func_L01_002333D8);
INCLUDE_ASM("asm/overlays", func_L01_00233F58);
INCLUDE_ASM("asm/overlays", func_L01_00234970);
INCLUDE_ASM("asm/overlays", func_L01_0023CE00);
INCLUDE_ASM("asm/overlays", func_L01_00240CE8);
INCLUDE_ASM("asm/overlays", func_L01_002428E0);
INCLUDE_ASM("asm/overlays", func_L01_002490E0);
INCLUDE_ASM("asm/overlays", func_L01_002490F8);
