/* Shared code following hud; generated by tools/overlay_src.py, stubs replaced by C as functions are matched. */
#include "common.h"
#include "include_asm.h"

INCLUDE_ASM("asm/overlays", func_L00_00235960);
INCLUDE_ASM("asm/overlays", func_L00_00235CA0);
INCLUDE_ASM("asm/overlays", func_L00_00235FF8);
typedef struct {
    int unk00, unk04;
    char pad08[0x18];
    int unk20, unk24;
    char pad28[0x3C];
    int unk64, unk68, unk6C;
    char pad70[0xC];
    int unk7C;
    char pad80[0x10];
} HudBank;

extern HudBank D_L00_0017DD50[];
extern int func_001FFB38(int, int, int, int, int, int, int);
extern void func_001FFC48(void *);

/* The level's HUD bank reset, a shorter func_001FF6B8 (src/game/hud.c):
   for each of the 13 bank records at D_L00_0017DD50, func_001FFB38(i,
   0xFFFF, 0, 0, 0, 0, 1), +0x7C = 0, +0x6C = -6, then reloads it with
   func_001FFC48. */
void func_L00_00236208(void) {
    int i;

    for (i = 0; i < 13; i++) {
        func_001FFB38(i, 0xFFFF, 0, 0, 0, 0, 1);
        D_L00_0017DD50[i].unk7C = 0;
        D_L00_0017DD50[i].unk6C = -6;
        func_001FFC48(&D_L00_0017DD50[i]);
    }
}
typedef struct {
    char pad0[0x48];
    short unk48;
    short unk4A;
    char pad4C[0xC];
    int w;
    int h;
    int flags;
    char pad64[0x18];
    int unk7C;
    void *unk80;
} HudElem;

/* Aligns a HUD element's anchor by its flags (+0x60): unless bit 0 or 1
   is set, *Y moves up by half the height (+0x5C); unless bit 2 is set,
   *X moves left by the width (+0x58) with bit 3, else by half of it.
   Returns 0. The flags are read once for the first test and again after
   the store; `(flags ^ 1) & 1` is retail's xori / andi test of bit 0. */
int func_L00_00236400(HudElem *rec, int *x, int *y) {
    int w = rec->w;
    int h = rec->h;
    int flags = rec->flags;

    if ((flags ^ 1) & 1) {
        if (!(flags & 2)) {
            *y -= h >> 1;
        }
    }
    if (!(rec->flags & 4)) {
        if (rec->flags & 8) {
            *x -= w;
        } else {
            *x -= w >> 1;
        }
    }
    return 0;
}
INCLUDE_ASM("asm/overlays", func_L00_00236468);
INCLUDE_ASM("asm/overlays", func_L00_00236610);
INCLUDE_ASM("asm/overlays", func_L00_002366DC);
INCLUDE_ASM("asm/overlays", func_L00_00236710);
INCLUDE_ASM("asm/overlays", func_L00_00236750);
INCLUDE_ASM("asm/overlays", func_L00_002367A8);
INCLUDE_ASM("asm/overlays", func_L00_00236830);
INCLUDE_ASM("asm/overlays", func_L00_00236AB8);
INCLUDE_ASM("asm/overlays", func_L00_00236BF8);
INCLUDE_ASM("asm/overlays", func_L00_00236DE8);
INCLUDE_ASM("asm/overlays", func_L00_00236F38);
INCLUDE_ASM("asm/overlays", func_L00_002377E0);
INCLUDE_ASM("asm/overlays", func_L00_00237B70);
INCLUDE_ASM("asm/overlays", func_L00_00237B90);
INCLUDE_ASM("asm/overlays", func_L00_00238148);
INCLUDE_ASM("asm/overlays", func_L00_002381D0);
INCLUDE_ASM("asm/overlays", func_L00_00238478);
INCLUDE_ASM("asm/overlays", func_L00_00238530);
INCLUDE_ASM("asm/overlays", func_L00_00238C30);
INCLUDE_ASM("asm/overlays", func_L00_002394A8);
INCLUDE_ASM("asm/overlays", func_L00_00239510);
INCLUDE_ASM("asm/overlays", func_L00_00239918);
INCLUDE_ASM("asm/overlays", func_L00_00239F40);
INCLUDE_ASM("asm/overlays", func_L00_00239FC0);
INCLUDE_ASM("asm/overlays", func_L00_0023A1A0);
INCLUDE_ASM("asm/overlays", func_L00_0023A658);
INCLUDE_ASM("asm/overlays", func_L00_0023A690);
INCLUDE_ASM("asm/overlays", func_L00_0023A788);
INCLUDE_ASM("asm/overlays", func_L00_0023AB88);
INCLUDE_ASM("asm/overlays", func_L00_0023ABB0);
INCLUDE_ASM("asm/overlays", func_L00_0023AC68);
INCLUDE_ASM("asm/overlays", func_L00_0023AFD8);
INCLUDE_ASM("asm/overlays", func_L00_0023B0F8);
INCLUDE_ASM("asm/overlays", func_L00_0023B140);
INCLUDE_ASM("asm/overlays", func_L00_0023B430);
INCLUDE_ASM("asm/overlays", func_L00_0023B440);
INCLUDE_ASM("asm/overlays", func_L00_0023B610);
INCLUDE_ASM("asm/overlays", func_L00_0023B750);
INCLUDE_ASM("asm/overlays", func_L00_0023B890);
INCLUDE_ASM("asm/overlays", func_L00_0023BAB8);
INCLUDE_ASM("asm/overlays", func_L00_0023C058);
INCLUDE_ASM("asm/overlays", func_L00_0023C458);
INCLUDE_ASM("asm/overlays", func_L00_0023D750);
INCLUDE_ASM("asm/overlays", func_L00_0023D838);
INCLUDE_ASM("asm/overlays", func_L00_0023D9C0);
INCLUDE_ASM("asm/overlays", func_L00_0023DB30);
INCLUDE_ASM("asm/overlays", func_L00_0023DD70);
