/* Shared code following lights; generated by tools/overlay_src.py, stubs replaced by C as functions are matched. */
#include "common.h"
#include "include_asm.h"

INCLUDE_ASM("asm/overlays", func_L00_0023FA70);
INCLUDE_ASM("asm/overlays", func_L00_0023FAB8);
