/* Shared code following mobyutil; generated by tools/overlay_src.py, stubs replaced by C as functions are matched. */
#include "common.h"
#include "include_asm.h"

INCLUDE_ASM("asm/overlays", func_L05_0028AA68);
INCLUDE_ASM("asm/overlays", func_L05_0028AADC);
INCLUDE_ASM("asm/overlays", func_L05_0028CEE8);
