/* Shared code following mobyutil; generated by tools/overlay_src.py, stubs replaced by C as functions are matched. */
#include "common.h"
#include "include_asm.h"

INCLUDE_ASM("asm/overlays", func_L00_00258BC8);
extern int func_001160D8(void);

/* Random float in [lo, hi], randomly negated: uses a 12-bit fraction
   (bits 16-27 of the RNG word) for the magnitude and bit 16 for the
   sign. */
float func_L00_00258C80(float lo, float hi) {
    int v = func_001160D8() >> 16;
    float range = hi - lo;
    float r = lo + (float)(v & 0xFFF) * range * 0.000244140625f;

    if (v & 1) {
        r = -r;
    }
    return r;
}
INCLUDE_ASM("asm/overlays", func_L00_00258DB0);
INCLUDE_ASM("asm/overlays", func_L00_00258E58);
INCLUDE_ASM("asm/overlays", func_L00_00258F28);
extern float func_001F9F90(float x);
extern void func_001F9BF0(void *dst, void *a, void *b); /* dst = a - b (vector) */
extern void func_001F9C30(void *, void *, float);
extern void func_001F9BD8(void *, void *, void *);

/* Vector cosine interpolation: dst = a + (b - a) * ((1 - cos(t * pi)) * 0.5).
   Scalar analogue matched at src/game/mobyutil.c:func_00214220. */
void func_L00_00258FA8(void *dst, void *a, void *b, float t) {
    float tmp[4];
    float ease;

    if (t == 0.0f) {
        qcopy(dst, a);
        return;
    }
    if (t == 1.0f) {
        qcopy(dst, b);
        return;
    }
    ease = (1.0f - func_001F9F90(t * 3.14159274f)) * 0.5f;
    func_001F9BF0(tmp, b, a);
    func_001F9C30(tmp, tmp, ease);
    func_001F9BD8(dst, a, tmp);
}
INCLUDE_ASM("asm/overlays", func_L00_00259088);
INCLUDE_ASM("asm/overlays", func_L00_00259148);
INCLUDE_ASM("asm/overlays", func_L00_002592B0);
INCLUDE_ASM("asm/overlays", func_L00_00259418);
INCLUDE_ASM("asm/overlays", func_L00_00259428);
INCLUDE_ASM("asm/overlays", func_L00_002594C8);
INCLUDE_ASM("asm/overlays", func_L00_00259868);
INCLUDE_ASM("asm/overlays", func_L00_00259B08);
INCLUDE_ASM("asm/overlays", func_L00_00259B88);
INCLUDE_ASM("asm/overlays", func_L00_0025A060);
INCLUDE_ASM("asm/overlays", func_L00_0025A1D8);
INCLUDE_ASM("asm/overlays", func_L00_0025A208);
INCLUDE_ASM("asm/overlays", func_L00_0025A2F0);
INCLUDE_ASM("asm/overlays", func_L00_0025A344);
INCLUDE_ASM("asm/overlays", func_L00_0025A43C);
INCLUDE_ASM("asm/overlays", func_L00_0025A458);
INCLUDE_ASM("asm/overlays", func_L00_0025A468);
INCLUDE_ASM("asm/overlays", func_L00_0025A4A0);
INCLUDE_ASM("asm/overlays", func_L00_0025A540);
INCLUDE_ASM("asm/overlays", func_L00_0025A5D8);
INCLUDE_ASM("asm/overlays", func_L00_0025A748);
INCLUDE_ASM("asm/overlays", func_L00_0025A778);
INCLUDE_ASM("asm/overlays", func_L00_0025A848);
INCLUDE_ASM("asm/overlays", func_L00_0025A868);
extern void func_001F9BC0(void *);
void func_L00_0025A890(char *a, int b, int c, float d) {
    *(int *)(a + 0x10) = b;
    *(int *)(a + 0x14) = c;
    *(float *)(a + 0x1C) = d;
    *(int *)(a + 0x20) = 0;
    func_001F9BC0(a);
}
INCLUDE_ASM("asm/overlays", func_L00_0025A8C0);
INCLUDE_ASM("asm/overlays", func_L00_0025A8E8);
INCLUDE_ASM("asm/overlays", func_L00_0025AA20);
INCLUDE_ASM("asm/overlays", func_L00_0025AAC0);
INCLUDE_ASM("asm/overlays", func_L00_0025AC00);
INCLUDE_ASM("asm/overlays", func_L00_0025AD38);
INCLUDE_ASM("asm/overlays", func_L00_0025AD60);
INCLUDE_ASM("asm/overlays", func_L00_0025AFA8);
INCLUDE_ASM("asm/overlays", func_L00_0025B040);
INCLUDE_ASM("asm/overlays", func_L00_0025B168);
INCLUDE_ASM("asm/overlays", func_L00_0025B178);
INCLUDE_ASM("asm/overlays", func_L00_0025B478);
INCLUDE_ASM("asm/overlays", func_L00_0025B4AC);
INCLUDE_ASM("asm/overlays", func_L00_0025B4D0);
INCLUDE_ASM("asm/overlays", func_L00_0025BA50);
INCLUDE_ASM("asm/overlays", func_L00_0025BBA0);
INCLUDE_ASM("asm/overlays", func_L00_0025BC48);
INCLUDE_ASM("asm/overlays", func_L00_0025BCF8);
INCLUDE_ASM("asm/overlays", func_L00_0025C488);
INCLUDE_ASM("asm/overlays", func_L00_0025C498);
INCLUDE_ASM("asm/overlays", func_L00_0025C700);
INCLUDE_ASM("asm/overlays", func_L00_0025C710);
INCLUDE_ASM("asm/overlays", func_L00_0025C7A8);
extern float func_001F9B88(float arg0);

void func_L00_0025C7F0(float *ptr, float rate, float b, float c, float limit) {
    float v = *ptr + (b * rate - c * (*ptr));

    *ptr = v;
    if (0.0f < limit) {
        if (limit < v) {
            *ptr = limit;
        } else if (v < -limit) {
            *ptr = -limit;
        }
    }
    if (func_001F9B88(rate) < *ptr) {
        *ptr = func_001F9B88(rate);
    } else if (*ptr < -func_001F9B88(rate)) {
        *ptr = -func_001F9B88(rate);
    }
}
INCLUDE_ASM("asm/overlays", func_L00_0025C918);
INCLUDE_ASM("asm/overlays", func_L00_0025CB90);
INCLUDE_ASM("asm/overlays", func_L00_0025CC58);
INCLUDE_ASM("asm/overlays", func_L00_0025CCF0);
INCLUDE_ASM("asm/overlays", func_L00_0025CE58);
INCLUDE_ASM("asm/overlays", func_L00_0025D038);
INCLUDE_ASM("asm/overlays", func_L00_0025D0E0);
INCLUDE_ASM("asm/overlays", func_L00_0025D140);
INCLUDE_ASM("asm/overlays", func_L00_0025D288);
INCLUDE_ASM("asm/overlays", func_L00_0025D308);
INCLUDE_ASM("asm/overlays", func_L00_0025D390);
INCLUDE_ASM("asm/overlays", func_L00_0025D3A0);
INCLUDE_ASM("asm/overlays", func_L00_0025D3F0);
INCLUDE_ASM("asm/overlays", func_L00_0025D5B0);
INCLUDE_ASM("asm/overlays", func_L00_0025D6F0);
INCLUDE_ASM("asm/overlays", func_L00_0025E210);
INCLUDE_ASM("asm/overlays", func_L00_0025E290);
INCLUDE_ASM("asm/overlays", func_L00_0025E4B0);
INCLUDE_ASM("asm/overlays", func_L00_0025E590);
INCLUDE_ASM("asm/overlays", func_L00_0025E7F8);
INCLUDE_ASM("asm/overlays", func_L00_0025E828);
INCLUDE_ASM("asm/overlays", func_L00_0025E860);
INCLUDE_ASM("asm/overlays", func_L00_0025EAC8);
INCLUDE_ASM("asm/overlays", func_L00_0025EB58);
INCLUDE_ASM("asm/overlays", func_L00_0025ED30);
INCLUDE_ASM("asm/overlays", func_L00_0025EFC0);
INCLUDE_ASM("asm/overlays", func_L00_0025F360);
INCLUDE_ASM("asm/overlays", func_L00_0025F368);
INCLUDE_ASM("asm/overlays", func_L00_0025F3C0);
INCLUDE_ASM("asm/overlays", func_L00_0025F410);
INCLUDE_ASM("asm/overlays", func_L00_0025F420);
INCLUDE_ASM("asm/overlays", func_L00_0025F450);
INCLUDE_ASM("asm/overlays", func_L00_0025F4A8);
INCLUDE_ASM("asm/overlays", func_L00_00260108);
INCLUDE_ASM("asm/overlays", func_L00_00260460);
INCLUDE_ASM("asm/overlays", func_L00_002607A8);
INCLUDE_ASM("asm/overlays", func_L00_002607F8);
INCLUDE_ASM("asm/overlays", func_L00_00260878);
INCLUDE_ASM("asm/overlays", func_L00_002608D0);
INCLUDE_ASM("asm/overlays", func_L00_002608F0);
INCLUDE_ASM("asm/overlays", func_L00_0026093C);
INCLUDE_ASM("asm/overlays", func_L00_00260958);
INCLUDE_ASM("asm/overlays", func_L00_00260AB0);
INCLUDE_ASM("asm/overlays", func_L00_00260B68);
INCLUDE_ASM("asm/overlays", func_L00_00260D30);
INCLUDE_ASM("asm/overlays", func_L00_00260FB0);
INCLUDE_ASM("asm/overlays", func_L00_00261458);
INCLUDE_ASM("asm/overlays", func_L00_00261478);
INCLUDE_ASM("asm/overlays", func_L00_00261568);
INCLUDE_ASM("asm/overlays", func_L00_002616E0);
INCLUDE_ASM("asm/overlays", func_L00_002617B0);
INCLUDE_ASM("asm/overlays", func_L00_00261848);
INCLUDE_ASM("asm/overlays", func_L00_002618D8);
