/* Shared code following partupd; generated by tools/overlay_src.py, stubs replaced by C as functions are matched. */
#include "common.h"
#include "include_asm.h"

INCLUDE_ASM("asm/overlays", func_L00_0026A130);
INCLUDE_ASM("asm/overlays", func_L00_0026A398);
INCLUDE_ASM("asm/overlays", func_L00_0026A7F8);
INCLUDE_ASM("asm/overlays", func_L00_0026A910);
INCLUDE_ASM("asm/overlays", func_L00_0026AA10);
INCLUDE_ASM("asm/overlays", func_L00_0026AB10);
INCLUDE_ASM("asm/overlays", func_L00_0026ABC0);
INCLUDE_ASM("asm/overlays", func_L00_0026B368);
INCLUDE_ASM("asm/overlays", func_L00_0026B458);
INCLUDE_ASM("asm/overlays", func_L00_0026B590);
INCLUDE_ASM("asm/overlays", func_L00_0026B720);
INCLUDE_ASM("asm/overlays", func_L00_0026B890);
INCLUDE_ASM("asm/overlays", func_L00_0026BB18);
INCLUDE_ASM("asm/overlays", func_L00_0026C0D0);
INCLUDE_ASM("asm/overlays", func_L00_0026C3A0);
INCLUDE_ASM("asm/overlays", func_L00_0026C630);
INCLUDE_ASM("asm/overlays", func_L00_0026C7B0);
INCLUDE_ASM("asm/overlays", func_L00_0026C908);
INCLUDE_ASM("asm/overlays", func_L00_0026CA10);
INCLUDE_ASM("asm/overlays", func_L00_0026CB48);
INCLUDE_ASM("asm/overlays", func_L00_0026CD70);
INCLUDE_ASM("asm/overlays", func_L00_0026CF28);
INCLUDE_ASM("asm/overlays", func_L00_0026D270);
INCLUDE_ASM("asm/overlays", func_L00_0026D3F8);
INCLUDE_ASM("asm/overlays", func_L00_0026D588);
extern void func_001F9BD8(void *, void *, void *);
extern void func_L00_002688A8(void *);
void func_L00_0026D690(char *a) {
    int t;
    func_001F9BD8(a + 0x10, a + 0x10, a + 0x30);
    func_001F9BD8(a + 0x20, a + 0x20, a + 0x30);
    t = *(int *)(a + 4) + 0xFA000000;
    *(int *)(a + 4) = t;
    *(int *)(a + 0xC) = t;
    if (t < 0) func_L00_002688A8(a);
}
INCLUDE_ASM("asm/overlays", func_L00_0026D700);
INCLUDE_ASM("asm/overlays", func_L00_0026DA50);
INCLUDE_ASM("asm/overlays", func_L00_0026DB50);
INCLUDE_ASM("asm/overlays", func_L00_0026DD70);
INCLUDE_ASM("asm/overlays", func_L00_0026DEA0);
INCLUDE_ASM("asm/overlays", func_L00_0026E050);
INCLUDE_ASM("asm/overlays", func_L00_0026E310);
INCLUDE_ASM("asm/overlays", func_L00_0026E438);
INCLUDE_ASM("asm/overlays", func_L00_0026E5A0);
INCLUDE_ASM("asm/overlays", func_L00_0026E940);
INCLUDE_ASM("asm/overlays", func_L00_0026EA80);
INCLUDE_ASM("asm/overlays", func_L00_0026EBC0);
INCLUDE_ASM("asm/overlays", func_L00_0026ECA0);
INCLUDE_ASM("asm/overlays", func_L00_0026ED30);
INCLUDE_ASM("asm/overlays", func_L00_0026EFF0);
INCLUDE_ASM("asm/overlays", func_L00_0026F248);
INCLUDE_ASM("asm/overlays", func_L00_0026F510);
INCLUDE_ASM("asm/overlays", func_L00_0026FA28);
extern void *func_00218928(int);
extern float func_002140F8(float, float);
extern int func_L00_0025D038(float, float, float, float);
extern int func_001FA898_r(float) __asm__("func_001FA898");
extern float D_0015EE60 MACRO_ADDR;
extern unsigned char *D_L00_001B2420;

void *func_L00_0026FBC8(void *arg0) {
    char *p = func_00218928(0x20);

    if (p != 0) {
        float scaled = D_0015EE60 * 0.016f;
        char *q = p + 0x20;

        *(void **)(p + 0x20) = arg0;
        *(float *)(q + 4) = 0.0f;
        *(float *)(q + 8) = scaled;
        *(float *)(q + 0xC) = func_002140F8(*(float *)(q + 4), 1.0f);
        *(float *)(q + 0x10) = 1.0f;
        *(float *)(q + 0x14) = 1.0f;
        *(float *)(q + 0x18) = 1.0f;
        qcopy(p + 0x10, (char *)arg0 + 0x10);

        *(int *)(p + 4) = func_L00_0025D038(1.0f, 1.0f, 1.0f, *(float *)(q + 4));
        p[9] = (char)(func_001FA898_r(4.0f) + 0x40);
        p[1] = 0;
        p[3] = 0x48;
        *(float *)(p + 0xC) = func_002140F8(50000.0f, 50000.0f);
        p[8] = (char)func_001FA898_r(*(float *)(q + 0xC) * 255.0f);
        p[2] = *D_L00_001B2420;
    }

    return p;
}
INCLUDE_ASM("asm/overlays", func_L00_0026FCE8);
extern int func_001F9938(void *);
extern void func_L00_002688A8(void *);
void func_L00_0026FEE8(char *a) {
    if (func_001F9938(a + 10) != 0) {
        func_L00_002688A8(a);
    }
}
INCLUDE_ASM("asm/overlays", func_L00_0026FF20);
INCLUDE_ASM("asm/overlays", func_L00_00270120);
INCLUDE_ASM("asm/overlays", func_L00_002703E8);
INCLUDE_ASM("asm/overlays", func_L00_00270500);
INCLUDE_ASM("asm/overlays", func_L00_00270738);
INCLUDE_ASM("asm/overlays", func_L00_002708A0);
INCLUDE_ASM("asm/overlays", func_L00_002709A0);
INCLUDE_ASM("asm/overlays", func_L00_00270AD8);
INCLUDE_ASM("asm/overlays", func_L00_00270BC8);
INCLUDE_ASM("asm/overlays", func_L00_00270DB0);
void func_L00_002715B0(char *a) {
    if (*(short *)(a + 0xA) != -1) {
        if (func_001F9938(a + 0xA) != 0) {
            func_L00_002688A8(a);
        }
    }
}
INCLUDE_ASM("asm/overlays", func_L00_002715F8);
INCLUDE_ASM("asm/overlays", func_L00_002717E8);
INCLUDE_ASM("asm/overlays", func_L00_00271F40);
