/* Shared code following partupd; generated by tools/overlay_src.py, stubs replaced by C as functions are matched. */
#include "common.h"
#include "include_asm.h"

INCLUDE_ASM("asm/overlays", func_L00_00272158);
INCLUDE_ASM("asm/overlays", func_L00_002722F0);
INCLUDE_ASM("asm/overlays", func_L00_00272488);
INCLUDE_ASM("asm/overlays", func_L00_002725E8);
INCLUDE_ASM("asm/overlays", func_L00_00272770);
INCLUDE_ASM("asm/overlays", func_L00_00272890);
extern char *D_L00_001B24BC;
extern unsigned char *func_00218928(int);
extern int func_002140B0(int);
extern int func_001FA898(float);

unsigned char *func_L00_002729B8(void *a, void *b, float f) {
    unsigned char *r = func_00218928(0x2F);
    if (r != 0) {
        qcopy(r + 0x10, a);
        *(int *)(r + 4) = ((random_integer_below(8) + 0x28) << 24) | 0x808080;
        r[9] = truncate_float_to_s32(2.0f) + 0x20;
        r[3] = 0x48;
        r[1] = 0;
        r[2] = *(unsigned char *)D_L00_001B24BC;
        *(float *)(r + 0xC) = f;
        qcopy(r + 0x20, b);
        r[8] = random_integer_below(0x100);
    }
    return r;
}
extern void func_001F9C30(void *, void *, float);
extern void func_001F9BD8(void *, void *, void *);
extern void func_L00_002688A8(void *);
void func_L00_00272A88(char *m) {
    char *v = m + 0x20;
    int t;
    FastVecScale(v, v, 0.975f);
    FastVecAdd(m + 0x10, m + 0x10, v);
    *(float *)(m + 0xC) += 14700.0f;
    m[8] += v[0x10];
    t = *(int *)(m + 4) + 0xFE000000;
    *(int *)(m + 4) = t;
    if (t < 0) {
        KillPart(m);
    }
}
extern void func_001F9BD8(void *, void *, void *);
extern float func_001FA888(int);
extern float func_001F9B88(float);
extern int func_001FA8A8(int, int, float);
extern int func_001F9938(void *);
extern void func_L00_002688A8(void *);
void func_L00_00272B28(char *m) {
    char *v = m + 0x20;
    m[8] += v[0x1C];
    FastVecAdd(m + 0x10, m + 0x10, v);
    *(int *)(m + 4) = FastTweenColor(*(int *)(v + 0x18), *(int *)(v + 0x14),
        FastAbsF(func_001FA888(*(short *)(m + 0xA)) * *(float *)(v + 0x10) - 1.0f));
    if (FastDecTimer(m + 0xA)) {
        KillPart(m);
    }
}
INCLUDE_ASM("asm/overlays", func_L00_00272BC0);
INCLUDE_ASM("asm/overlays", func_L00_00272C98);
INCLUDE_ASM("asm/overlays", func_L00_00272D68);
void func_L00_00272E60(char *m) {
    char *v;
    float f;
    if (FastDecTimer(m + 0xA)) {
        KillPart(m);
    } else {
        v = m + 0x20;
        f = func_001FA888(*(short *)(m + 0xA)) * *(float *)(v + 0x10);
        *(int *)(m + 4) = FastTweenColor(*(int *)(v + 0xC), *(int *)(v + 8), f);
        *(float *)(m + 0xC) = ((*(float *)(m + 0x20) - *(float *)(v + 4)) * f + *(float *)(v + 4)) * 210000.0f;
    }
}
INCLUDE_ASM("asm/overlays", func_L00_00272F00);
INCLUDE_ASM("asm/overlays", func_L00_00273090);
INCLUDE_ASM("asm/overlays", func_L00_002732D8);
INCLUDE_ASM("asm/overlays", func_L00_00273478);
INCLUDE_ASM("asm/overlays", func_L00_00273578);
INCLUDE_ASM("asm/overlays", func_L00_002736D8);
INCLUDE_ASM("asm/overlays", func_L00_00273788);
INCLUDE_ASM("asm/overlays", func_L00_00273868);
INCLUDE_ASM("asm/overlays", func_L00_00273A60);
INCLUDE_ASM("asm/overlays", func_L00_00273E08);
INCLUDE_ASM("asm/overlays", func_L00_00273F28);
INCLUDE_ASM("asm/overlays", func_L00_00273F80);
INCLUDE_ASM("asm/overlays", func_L00_00274138);
INCLUDE_ASM("asm/overlays", func_L00_002742E8);
INCLUDE_ASM("asm/overlays", func_L00_002745A8);
void func_L00_002746A0(char *a) {
    char *s = a + 0x20;
    int w;
    int t;
    if (*(short *)(s + 2) == 1) {
        return;
    }
    if (*(short *)(s + 2) == 2) {
        *(float *)(a + 0x10) = *(float *)(*(char **)(s + 4) + 0x10) + *(float *)(s + 0x10);
        *(float *)(a + 0x14) = *(float *)(*(char **)(s + 4) + 0x14) + *(float *)(s + 0x14);
        *(float *)(a + 0x18) = *(float *)(*(char **)(s + 4) + 0x18) + *(float *)(s + 0x18);
    }
    w = *(int *)(a + 4);
    t = w >> 24;
    t -= *(short *)(a + 0x20);
    if (t <= 0) {
        KillPart(a);
    } else {
        *(int *)(a + 4) = (w & 0xFFFFFF) | (t << 24);
    }
}
INCLUDE_ASM("asm/overlays", func_L00_00274788);
INCLUDE_ASM("asm/overlays", func_L00_00274908);
INCLUDE_ASM("asm/overlays", func_L00_00274D80);
INCLUDE_ASM("asm/overlays", func_L00_00275040);
void func_L00_002751A8(char *m) {
    char *v = m + 0x20;
    int t;
    FastVecAdd(m + 0x10, m + 0x10, v);
    *(float *)(m + 0xC) += *(float *)(v + 0x10);
    m[8] += 1;
    t = *(unsigned short *)(m + 0xA) - 1;
    *(unsigned short *)(m + 0xA) = t;
    if ((short)t == 0) {
        *(int *)(m + 4) += 0xFF000000;
        *(short *)(m + 0xA) = 2;
    }
    if ((*(int *)(m + 4) & 0xFF000000) == 0) {
        KillPart(m);
    }
}
INCLUDE_ASM("asm/overlays", func_L00_00275248);
INCLUDE_ASM("asm/overlays", func_L00_002753B8);
INCLUDE_ASM("asm/overlays", func_L00_002756B8);
INCLUDE_ASM("asm/overlays", func_L00_002757E8);
INCLUDE_ASM("asm/overlays", func_L00_00275910);
INCLUDE_ASM("asm/overlays", func_L00_00275B98);
extern void func_L00_002688A8(void *);
void func_L00_00275C80(char *a) {
    int t = *(unsigned short *)(a + 0xA) - 1;
    *(short *)(a + 0xA) = t;
    if ((short)t == 0) {
        *(int *)(a + 4) += 0xFF000000;
        *(short *)(a + 0xA) = 2;
    }
    if ((*(int *)(a + 4) & 0xFF000000) == 0) KillPart(a);
}
INCLUDE_ASM("asm/overlays", func_L00_00275CE8);
INCLUDE_ASM("asm/overlays", func_L00_00275FF8);
extern void func_L00_002688A8(void *);
void func_L00_00276180(char *a) {
    *(unsigned char *)(a + 8) = *(unsigned char *)(a + 8) + *(unsigned char *)(a + 0x38);
    if (*(float *)(a + 0xC) <= 0.0f) {
        *(float *)(a + 0xC) = 0.0f;
        KillPart(a);
    }
}
INCLUDE_ASM("asm/overlays", func_L00_002761C0);
INCLUDE_ASM("asm/overlays", func_L00_002763B0);
INCLUDE_ASM("asm/overlays", func_L00_00276590);
extern void func_L00_0025A468(void *, void *);
extern int func_001F9938(void *);
extern short D_L00_00160300;
void func_L00_002766B0(char *a) {
    func_L00_0025A468(a + 4, *(void **)&D_L00_00160300);
    if (FastDecTimer(a + 0xA) != 0) {
        KillPart(a);
    }
}
typedef struct { float x, y, z, w; } Vx __attribute__((aligned(16)));
extern int func_001FA898(float);

void func_L00_00276700(char *m) {
    Vx v;
    float w, t;
    v = *(Vx *)(m + 0x20);
    w = v.w;
    v.w = 0;
    t = func_001FA888(*(short *)(m + 0xA)) / w;
    *(int *)(m + 4) = (truncate_float_to_s32(t * 38.0f) << 24) | 0x808080;
    *(char *)(m + 8) = truncate_float_to_s32(t * 33.0f);
    FastVecAdd(m + 0x10, m + 0x10, &v);
    if (FastDecTimer(m + 0xA)) {
        KillPart(m);
    }
}
INCLUDE_ASM("asm/overlays", func_L00_002767B0);
INCLUDE_ASM("asm/overlays", func_L00_00276940);
INCLUDE_ASM("asm/overlays", func_L00_00276C08);
INCLUDE_ASM("asm/overlays", func_L00_00276D50);
INCLUDE_ASM("asm/overlays", func_L00_00276EB0);
INCLUDE_ASM("asm/overlays", func_L00_00276F18);
