/* Shared code following stash; generated by tools/overlay_src.py, stubs replaced by C as functions are matched. */
#include "common.h"
#include "include_asm.h"

INCLUDE_ASM("asm/overlays", func_L00_00295010);
INCLUDE_ASM("asm/overlays", func_L00_002951A8);
INCLUDE_ASM("asm/overlays", func_L00_002951C8);
