/* Shared code following stub; generated by tools/overlay_src.py, stubs replaced by C as functions are matched. */
#include "common.h"
#include "include_asm.h"

INCLUDE_ASM("asm/overlays", func_L00_001EB430);
INCLUDE_ASM("asm/overlays", func_L00_001EB438);
INCLUDE_ASM("asm/overlays", func_L00_001EB440);
INCLUDE_ASM("asm/overlays", func_L00_001EB448);
