/* Shared code following vendor; generated by tools/overlay_src.py, stubs replaced by C as functions are matched. */
#include "common.h"
#include "include_asm.h"

INCLUDE_ASM("asm/overlays", func_L00_0029FD68);
INCLUDE_ASM("asm/overlays", func_L00_002A0C20);
INCLUDE_ASM("asm/overlays", func_L00_002A0F60);
INCLUDE_ASM("asm/overlays", func_L00_002A11E8);
INCLUDE_ASM("asm/overlays", func_L00_002A1540);
