/* Shared code following vendor; generated by tools/overlay_src.py, stubs replaced by C as functions are matched. */
#include "common.h"
#include "include_asm.h"

extern int D_0015EED0[] MACRO_ADDR;
extern short D_L00_00161E80;
extern short D_L00_0015F044;
extern void func_L00_002E5B68();
extern void func_L00_002E74B0(void *);
extern void func_001E9768();
extern void func_L00_002E6CE0(void *);
extern void func_L00_002EB060(void *);
extern void func_L00_002E72E8(void *);
void func_L00_002EB0D8(char *m) {
    char *p = *(char **)(m + 0x70) + 0x1D0;
    *(float *)&D_L00_0015F044 = ((float *)&D_L00_00161E80)[D_0015EED0[5]];
    func_L00_002E5B68(m);
    func_L00_002E74B0(m);
    func_001E9768(m);
    func_L00_002E6CE0(m);
    func_001E9768(m, p);
    func_L00_002EB060(m);
    func_001E9768(m);
    func_L00_002E72E8(m);
}
INCLUDE_ASM("asm/overlays", func_L00_002EB170);
INCLUDE_ASM("asm/overlays", func_L00_002EB280);
INCLUDE_ASM("asm/overlays", func_L00_002EB3A0);
INCLUDE_ASM("asm/overlays", func_L00_002EB3E8);
INCLUDE_ASM("asm/overlays", func_L00_002EB938);
typedef struct { char pad[0x254]; int p; char pad2[0x18]; short s; char pad3[1]; char c; char pad4[0x14]; float f0; char pad5[8]; float f1; } S;
extern S D_L00_00166D80;
extern void func_L00_002EB3A0(void);
extern void func_0022ED80(int, int, int);

void func_L00_002EBC50(void) {
    S *g = &D_L00_00166D80;
    S *h;
    if (g->s == 0) g->s = 1; else g->s = 2;
    h = &D_L00_00166D80;
    h->c = 0;
    h->f1 = 0.05f;
    h->f0 = 0.05f;
    func_L00_002EB3A0();
    if (h->p != 0) func_0022ED80(0, 0, h->p);
}
INCLUDE_ASM("asm/overlays", func_L00_002EBCC0);
INCLUDE_ASM("asm/overlays", func_L00_002EBE88);
INCLUDE_ASM("asm/overlays", func_L00_002EBF38);
INCLUDE_ASM("asm/overlays", func_L00_002EBF50);
INCLUDE_ASM("asm/overlays", func_L00_002EC0C8);
INCLUDE_ASM("asm/overlays", func_L00_002EC208);
extern void func_001F9BC0(void *);
extern void func_001FA218(void *, void *);
extern void func_001FA480(void *, void *);

void func_L00_002EC210(char *m) {
    float v[16];
    char *q;
    char *p;
    *(int *)(*(char **)(m + 0x70) + 0xC0) = 4;
    q = *(char **)(m + 0x70) + 0x30;
    *(float *)(q + 0x20) = 0.05f;
    *(float *)(q + 0x24) = 0.3f;
    *(float *)(q + 0x28) = 1.0f;
    *(short *)(q + 0x2C) = 1;
    func_001F9BC0(q);
    p = *(char **)(m + 0x70);
    *(float *)(p + 0x10) = 0.3f;
    *(float *)(p + 0x14) = 0.3f;
    *(float *)(p + 0x18) = 1.0f;
    *(short *)(p + 0x1C) = 1;
    func_001F9BC0(p);
    func_001FA218(v, m + 0x40);
    func_001FA480(m, v);
    *(short *)(m + 0x7E) = 0;
}
INCLUDE_ASM("asm/overlays", func_L00_002EC2D0);
extern void func_L00_002EC2D0(void *);
extern void func_L00_001EDA28(void *, float);
void func_L00_002EC6C8(char *a) {
    char *p = *(char **)(a + 0x70) + 0xE0;
    func_L00_002EC2D0(a);
    if (*(int *)(p + 0x40) != 0) {
        a[0x89] = 0;
        func_L00_001EDA28(a + 0x30, 0.5f);
    }
}
extern void func_L00_001ED900(void *, void *, void *);
extern float func_001FA748(float, float);
extern void func_001FA218(void *, void *);
extern void func_001FA480(void *, void *);
void func_L00_002EC728(void *arg) {
    char *a = arg;
    float m[16];
    char *p = *(char **)(a + 0x70) + 0xB0;
    func_L00_001ED900(a + 0x30, a + 0x50, p);
    *(float *)(a + 0x50) = func_001FA748(*(float *)(a + 0x50), *(float *)(p + 0x18));
    *(int *)(a + 0x40) = 0;
    *(float *)(a + 0x44) = func_001FA748(*(float *)(a + 0x54), *(float *)(a + 0x5C));
    *(float *)(a + 0x48) = func_001FA748(3.14159274101257324f, *(float *)(a + 0x50));
    *(float *)(a + 0x48) = func_001FA748(*(float *)(a + 0x48), *(float *)(a + 0x60));
    *(int *)(a + 0x4C) = 0;
    func_001FA218(m, a + 0x40);
    func_001FA480(a, m);
}
extern void func_L00_001EB448(void *, void *, float);
extern void func_L00_001EB430(void *);
extern void func_L00_001FF200(void *);
extern void func_L00_002EC728(void *);
void func_L00_002EC7D0(char *a, void *b, void *c, float f) {
    char *p = *(char **)(a + 0x70);
    char *q = p + 0xB0;
    qcopy(q, c);
    qcopy(p + 0x80, c);
    *(float *)(q + 0x18) = f;
    func_L00_001EB448(p + 0x14, b, f);
    func_L00_001EB448(a + 0x50, b, 0.0f);
    func_L00_001EB430(p);
    func_L00_001FF200(p + 0x90);
    func_L00_002EC728(a);
}
INCLUDE_ASM("asm/overlays", func_L00_002EC860);
INCLUDE_ASM("asm/overlays", func_L00_002EC930);
INCLUDE_ASM("asm/overlays", func_L00_002ECAF8);
INCLUDE_ASM("asm/overlays", func_L00_002ECDE0);
INCLUDE_ASM("asm/overlays", func_L00_002ECEC8);
extern char D_0013F450[];
extern void func_L00_002EC860(void *);
void func_L00_002ECFB0(void *arg) {
    char *a = arg;
    char *g = D_0013F450 + 0x80;
    char *p0 = *(char **)(a + 0x70);
    char *q = p0 + 0xB0;
    char *p;
    qcopy(q, g);
    *(float *)(q + 8) += 2.0f;
    qcopy(p0 + 0xC0, g + 0x10);
    p = *(char **)(a + 0x70);
    qcopy(p + 0x80, q);
    func_L00_001EB430(p + 0x14);
    *(float *)(p + 0x1C) = 4.639999866485596f;
    func_L00_001EB448(a + 0x50, p + 0x14, 0.0f);
    func_L00_002EC860(a);
}
INCLUDE_ASM("asm/overlays", func_L00_002ED088);
INCLUDE_ASM("asm/overlays", func_L00_002ED320);
INCLUDE_ASM("asm/overlays", func_L00_002ED958);
INCLUDE_ASM("asm/overlays", func_L00_002EDB58);
INCLUDE_ASM("asm/overlays", func_L00_002EDB70);
extern char D_0013F450[];
void func_L00_002EDC60(char *a) {
    char *g = D_0013F450;
    if (*(int *)(g + 0x2284) != *(short *)(a + 0x86) && *(int *)(g + 0x2084) != 6) {
        *(char *)(a + 0x7D) = 0;
        *(short *)(a + 0x7E) = 3;
    }
}
INCLUDE_ASM("asm/overlays", func_L00_002EDC98);
INCLUDE_ASM("asm/overlays", func_L00_002EDE38);
INCLUDE_ASM("asm/overlays", func_L00_002EE6E0);
INCLUDE_ASM("asm/overlays", func_L00_002EE7F8);
INCLUDE_ASM("asm/overlays", func_L00_002EE948);
extern char *D_L00_0015F050 MACRO_ADDR;
extern int D_L00_0015F6A8 MACRO_ADDR;
extern int func_L00_002EE7F8(void *);
extern void func_L00_002EE948(void *);
int func_L00_002EED60(char *a) {
    char *p = *(char **)(D_L00_0015F050 + *(short *)(a + 0x84) * 32 + 0x1C);
    if (*(short *)(p + 0x26) != 0) return 0;
    if (D_L00_0015F6A8 != 0) {
        if (func_L00_002EE7F8(a) != 0) {
            *(short *)(p + 0x26) = 0;
            *(int *)(p + 0x20) = 0;
            return 0;
        }
    }
    func_L00_002EE948(a);
    return 0;
}
INCLUDE_ASM("asm/overlays", func_L00_002EEE00);
INCLUDE_ASM("asm/overlays", func_L00_002EEF88);
