/* Shared code following vendor; generated by tools/overlay_src.py, stubs replaced by C as functions are matched. */
#include "common.h"
#include "include_asm.h"

INCLUDE_ASM("asm/overlays", func_L00_002C96D0);
INCLUDE_ASM("asm/overlays", func_L00_002C9820);
INCLUDE_ASM("asm/overlays", func_L00_002C9DC8);
INCLUDE_ASM("asm/overlays", func_L00_002CA6B8);
INCLUDE_ASM("asm/overlays", func_L00_002CA728);
INCLUDE_ASM("asm/overlays", func_L00_002CABB8);
INCLUDE_ASM("asm/overlays", func_L00_002CABC0);
INCLUDE_ASM("asm/overlays", func_L00_002CC210);
INCLUDE_ASM("asm/overlays", func_L00_002CC2B0);
extern int func_L00_002DD2D0(void *);
int func_L00_002CC360(char *a) {
    int r = func_L00_002DD2D0(a);
    a[0x20] = 5;
    return r;
}
INCLUDE_ASM("asm/overlays", func_L00_002CC390);
INCLUDE_ASM("asm/overlays", func_L00_002CC3C0);
INCLUDE_ASM("asm/overlays", func_L00_002CC868);
INCLUDE_ASM("asm/overlays", func_L00_002CD110);
INCLUDE_ASM("asm/overlays", func_L00_002CD3B8);
INCLUDE_ASM("asm/overlays", func_L00_002CD660);
INCLUDE_ASM("asm/overlays", func_L00_002CD7B0);
INCLUDE_ASM("asm/overlays", func_L00_002CDAB8);
INCLUDE_ASM("asm/overlays", func_L00_002CE390);
INCLUDE_ASM("asm/overlays", func_L00_002CE6A0);
INCLUDE_ASM("asm/overlays", func_L00_002CF170);
INCLUDE_ASM("asm/overlays", func_L00_002CF328);
INCLUDE_ASM("asm/overlays", func_L00_002CF3D8);
INCLUDE_ASM("asm/overlays", func_L00_002CF6A0);
INCLUDE_ASM("asm/overlays", func_L00_002CF808);
INCLUDE_ASM("asm/overlays", func_L00_002D06C8);
