/* Shared code following vendor; generated by tools/overlay_src.py, stubs replaced by C as functions are matched. */
#include "common.h"
#include "include_asm.h"

INCLUDE_ASM("asm/overlays", func_L09_002C6B30);
INCLUDE_ASM("asm/overlays", func_L09_002C73D0);
INCLUDE_ASM("asm/overlays", func_L09_002E39E0);
typedef int OvlQuad_08F58 __attribute__((mode(TI)));
typedef union {
    OvlQuad_08F58 q;
    f32 f[4];
    s32 i[4];
} OvlVec4_08F58;
typedef struct {
    f32 x;
    f32 y;
    f32 z;
    f32 w;
} Vec4f_08F58;
struct Manip_08F58;
struct GifEntry_08F58;
struct AnimSeq_08F58;
struct MobyClass_08F58 {
    u8 pad_0[0xC];
    u8 seq_count; /* number of entries in seqs[] (menu previews clamp the sequence to it) */
    u8 pad_D[3];
    u32 unk10; /* copied into Moby.unk94 when a moby is (re)classed */
    u8 pad_14[0x8];
    void *unk1C; /* word table, indexed id * 4 + 4 (0024eec0) */
    struct GifEntry_08F58 *gifs; /* patched by patch_moby_gifs */
    f32 scale; /* default draw scale: copied into Moby.scale, divides it */
    s32 unk28;
    void **callbacks; /* function-pointer table, called with the moby */
    u8 pad_30[0x14];
    u16 flags; /* initial Moby.flags */
    s16 unk46; /* class category; 5 is tested by targeting code */
    struct AnimSeq_08F58 *seqs[1]; /* animation sequences, indexed by Moby.seq */
};
struct Moby_08F58 {
    Vec4f_08F58 bsphere;
    Vec4f_08F58 pos;
    u8 state; /* >= 0xFE: dead, waiting to respawn */
    u8 group; /* linked group: index into the level moby-list table D_Lxx_001ABCC0 (0xFF: none) */
    u8 unk22; /* class slot: pclass = D_L00_00197300[unk22] (FUN_L00_002cf218) */
    u8 unk23; /* 0x40 for the smoke trail FUN_L09_00307ba8 spawns */
    struct MobyClass_08F58 *pclass;
    struct Moby_08F58 *next;
    f32 scale; /* draw scale (FUN_L01_002fa068 halves it, FUN_L00_00215ef8 divides by it) */
    u8 unk30; /* set to 0xFF (0x7F for beams) by spawners */
    u8 unk31; /* set to 1 by spawners */
    s16 unk32; /* set to 0xFF (0x7F for beams) by spawners */
    u16 flags;
    u16 unk36; /* set to 0x7F80 by spawners */
    u64 spawn_frame; /* frame count at which it may respawn */
    Vec4f_08F58 rot; /* z: yaw (FUN_L00_00266448 compares it with atan2 to the hero) */
    u8 frame; /* animation frame */
    u8 prev_frame; /* frame index in prev_seq */
    u8 seq; /* animation sequence id */
    u8 prev_seq;
    f32 unk54;
    f32 unk58;
    u8 pad5C[8];
    struct Manip_08F58 *manips;
    void *cur_frame_data;
    void *prev_frame_data;
    u8 unk70;
    u8 unk71; /* set to 0xFF when a moby changes class */
    u8 unk72;
    u8 unk73;
    void (*update)(struct Moby_08F58 *moby);
    u8 *pvars;
    u8 unk7C;
    u8 pad7D;
    u8 unk7E;
    u8 unk7F; /* set to 0x17 by FUN_L09_002c5990 near D_L09_00166F40 */
    u8 pad80[0x10];
    s32 unk90;
    u32 unk94; /* set from the class header's word 0x10 */
    s32 unk98; /* set to 1 while a carrier holds the moby (FUN_L00_002c7a58) */
    u8 pad9C[8];
    u8 unkA4;
    u8 padA5;
    s16 oclass;
    u8 padA8[8];
    u8 unkB0; /* 0xB0: index into the level's D_0014C050 row (0xFF: not spawned) */
    u8 padB1;
    u16 save_id; /* index into the level collected[]/killed[] tables and save bits D_0014C190[level][id >> 5] */
    s16 unkB4;
    u8 padB6[2];
    void *unkB8; /* 0xB8: bolt source record; its byte 0xB1 is a per-level id (FUN_L00_002a6b70) */
    u8 unkBC;
    u8 padBD[3];
    Vec4f_08F58 unkC0; /* 0xC0: first row of a matrix built from rot (FUN_001fa030) */
    Vec4f_08F58 unkD0;
    Vec4f_08F58 unkE0;
    u8 padF0[0x10];
};
typedef struct {
    OvlVec4_08F58 vel; /* 0x00 */
    f32 spin; /* 0x10 */
    s32 unk14; /* 0x14 */
    void *owner; /* 0x18 */
    s16 life; /* 0x1C */
    s16 life_max; /* 0x1E */
    f32 dist; /* 0x20: distance from the hero at spawn */
    s32 unk24; /* 0x24 */
    s32 unk28; /* 0x28 */
} ShotVars_307ba8_08F58;
extern f32 D_0015EE6C_08F58 __asm__("D_0015EE6C") MACRO_ADDR;
extern OvlVec4_08F58 D_0013F4D0_08F58 __asm__("D_0013F4D0");
extern struct Moby_08F58 *func_0020D348_08F58(s32) __asm__("func_0020D348");
extern f32 func_001F9CE8_08F58(OvlVec4_08F58 *) __asm__("func_001F9CE8");
extern f32 func_L00_001FF860_08F58(f32, f32) __asm__("func_L00_001FF860");
extern f32 func_002140F8_08F58(f32, f32) __asm__("func_002140F8");
extern f32 func_001F9D10_08F58(OvlVec4_08F58 *, OvlVec4_08F58 *) __asm__("func_001F9D10");
extern u8 *func_L00_0026E940_08F58(f32, struct Moby_08F58 *, u32, s32, s32) __asm__("func_L00_0026E940");
extern void func_L00_00251E30_08F58(struct Moby_08F58 *) __asm__("func_L00_00251E30");

/* Adapted from Lombyte (MIT) for PAL by OpenRAC's tools/port.py: src/overlays/shared/gameplay/vendor/00307ba8.c, FUN_L09_00307ba8. */
struct Moby_08F58 *func_L09_00308F58(void *owner, OvlVec4_08F58 *pos, OvlVec4_08F58 *vel, s32 life) {
    OvlVec4_08F58 p;
    OvlVec4_08F58 v;
    OvlVec4_08F58 *pp = &p;
    OvlVec4_08F58 *vp = &v;
    struct Moby_08F58 *m;
    ShotVars_307ba8_08F58 *pv;
    f32 r;
    s32 trail;

    p.q = pos->q;
    v.q = vel->q;
    m = func_0020D348_08F58(0x4EA);
    if (m != 0) {
        pv = (ShotVars_307ba8_08F58 *)m->pvars;
        pv->owner = owner;
        m->rot.x = 0.0f;
        m->scale *= 4.0f;
        m->unk30 = 0xFF;
        m->unk32 = 0xFF;
        m->unk31 = 1;
        m->rot.y = -func_L00_001FF860_08F58(func_001F9CE8_08F58(vp), vp->f[2]);
        m->rot.z = func_L00_001FF860_08F58(v.f[0], vp->f[1]);
        qcopy(&m->pos, pp);
        qcopy(&pv->vel, vp);
        r = D_0015EE6C_08F58 * 1.5707964f;
        pv->spin = func_002140F8_08F58(-r, r);
        pv->unk14 = 0;
        pv->life = life;
        pv->life_max = life;
        pv->dist = func_001F9D10_08F58((OvlVec4_08F58 *)&m->pos, &D_0013F4D0_08F58);
        pv->unk24 = 0;
        pv->unk28 = 0;
        trail = life * 5 / 4;
        m->flags |= 0x200;
        m->unk23 = 0x40;
        func_L00_0026E940_08F58(400000.0f, m, 0x2F7F4F4F, trail, -1);
        func_L00_0026E940_08F58(160000.0f, m, 0x4F7F7F7F, trail, -1);
        func_L00_00251E30_08F58(m);
    }
    return m;
}
typedef int OvlQuad_09118 __attribute__((mode(TI)));
typedef union {
    OvlQuad_09118 q;
    f32 f[4];
    s32 i[4];
} OvlVec4_09118;
typedef struct {
    f32 x;
    f32 y;
    f32 z;
    f32 w;
} Vec4f_09118;
struct Manip_09118;
struct GifEntry_09118;
struct AnimSeq_09118;
struct MobyClass_09118 {
    u8 pad_0[0xC];
    u8 seq_count; /* number of entries in seqs[] (menu previews clamp the sequence to it) */
    u8 pad_D[3];
    u32 unk10; /* copied into Moby.unk94 when a moby is (re)classed */
    u8 pad_14[0x8];
    void *unk1C; /* word table, indexed id * 4 + 4 (0024eec0) */
    struct GifEntry_09118 *gifs; /* patched by patch_moby_gifs */
    f32 scale; /* default draw scale: copied into Moby.scale, divides it */
    s32 unk28;
    void **callbacks; /* function-pointer table, called with the moby */
    u8 pad_30[0x14];
    u16 flags; /* initial Moby.flags */
    s16 unk46; /* class category; 5 is tested by targeting code */
    struct AnimSeq_09118 *seqs[1]; /* animation sequences, indexed by Moby.seq */
};
struct Moby_09118 {
    Vec4f_09118 bsphere;
    Vec4f_09118 pos;
    u8 state; /* >= 0xFE: dead, waiting to respawn */
    u8 group; /* linked group: index into the level moby-list table D_Lxx_001ABCC0 (0xFF: none) */
    u8 unk22; /* class slot: pclass = D_L00_00197300[unk22] (FUN_L00_002cf218) */
    u8 unk23; /* 0x40 for the smoke trail FUN_L09_00307ba8 spawns */
    struct MobyClass_09118 *pclass;
    struct Moby_09118 *next;
    f32 scale; /* draw scale (FUN_L01_002fa068 halves it, FUN_L00_00215ef8 divides by it) */
    u8 unk30; /* set to 0xFF (0x7F for beams) by spawners */
    u8 unk31; /* set to 1 by spawners */
    s16 unk32; /* set to 0xFF (0x7F for beams) by spawners */
    u16 flags;
    u16 unk36; /* set to 0x7F80 by spawners */
    u64 spawn_frame; /* frame count at which it may respawn */
    Vec4f_09118 rot; /* z: yaw (FUN_L00_00266448 compares it with atan2 to the hero) */
    u8 frame; /* animation frame */
    u8 prev_frame; /* frame index in prev_seq */
    u8 seq; /* animation sequence id */
    u8 prev_seq;
    f32 unk54;
    f32 unk58;
    u8 pad5C[8];
    struct Manip_09118 *manips;
    void *cur_frame_data;
    void *prev_frame_data;
    u8 unk70;
    u8 unk71; /* set to 0xFF when a moby changes class */
    u8 unk72;
    u8 unk73;
    void (*update)(struct Moby_09118 *moby);
    u8 *pvars;
    u8 unk7C;
    u8 pad7D;
    u8 unk7E;
    u8 unk7F; /* set to 0x17 by FUN_L09_002c5990 near D_L09_00166F40 */
    u8 pad80[0x10];
    s32 unk90;
    u32 unk94; /* set from the class header's word 0x10 */
    s32 unk98; /* set to 1 while a carrier holds the moby (FUN_L00_002c7a58) */
    u8 pad9C[8];
    u8 unkA4;
    u8 padA5;
    s16 oclass;
    u8 padA8[8];
    u8 unkB0; /* 0xB0: index into the level's D_0014C050 row (0xFF: not spawned) */
    u8 padB1;
    u16 save_id; /* index into the level collected[]/killed[] tables and save bits D_0014C190[level][id >> 5] */
    s16 unkB4;
    u8 padB6[2];
    void *unkB8; /* 0xB8: bolt source record; its byte 0xB1 is a per-level id (FUN_L00_002a6b70) */
    u8 unkBC;
    u8 padBD[3];
    Vec4f_09118 unkC0; /* 0xC0: first row of a matrix built from rot (FUN_001fa030) */
    Vec4f_09118 unkD0;
    Vec4f_09118 unkE0;
    u8 padF0[0x10];
};
typedef struct {
    OvlVec4_09118 vel; /* 0x00 */
    f32 spin; /* 0x10 */
    s32 unk14; /* 0x14 */
    void *owner; /* 0x18 */
    s16 life; /* 0x1C */
    s16 life_max; /* 0x1E */
    f32 dist; /* 0x20: distance from the hero at spawn */
    s32 unk24; /* 0x24 */
    s32 unk28; /* 0x28 */
} ShotVars_307ba8_09118;
typedef struct {
    OvlVec4_09118 dir; /* 0x00: unit direction; z/w overwritten with 1 and a range */
    struct Moby_09118 *self; /* 0x10: moby to ignore */
    s32 mask; /* 0x14: collision classes */
    u8 unk18;
    u8 unk19;
    s16 oclass; /* 0x1A */
    f32 radius; /* 0x1C */
    s32 unk20;
} CollisionProbe_307d68_09118;
extern f32 D_0015EE6C_09118 __asm__("D_0015EE6C") MACRO_ADDR;
extern OvlVec4_09118 D_0013F4D0_09118 __asm__("D_0013F4D0");
extern OvlVec4_09118 D_L09_00166FC0_09118 __asm__("D_L09_00166FC0");
extern OvlVec4_09118 D_L09_00174060_09118 __asm__("D_L09_00174060");
extern u8 D_L09_00174080_09118[] __asm__("D_L09_00174080");
extern f32 func_001F9D10_09118(void *, void *) __asm__("func_001F9D10");
extern f32 func_001F9D48_09118(void *, void *) __asm__("func_001F9D48");
extern void func_001F9BD8_09118(void *, void *, void *) __asm__("func_001F9BD8");
extern void func_001F9BF0_09118(void *, void *, void *) __asm__("func_001F9BF0");
extern void func_L00_001FF500_09118(void *, void *, f32) __asm__("func_L00_001FF500");
extern s32 func_0022ED80_09118(s32, s32, void *) __asm__("func_0022ED80");
extern void func_0020D678_09118(struct Moby_09118 *) __asm__("func_0020D678");
extern s32 func_001F9938_09118(s16 *) __asm__("func_001F9938");
extern s32 func_L00_001EFFF0_09118(void *, void *, s32, void *, CollisionProbe_307d68_09118 *) __asm__("func_L00_001EFFF0");
extern f32 func_002140F8_09118(f32, f32) __asm__("func_002140F8");
extern void func_L00_001FF610_09118(void *, void *, void *) __asm__("func_L00_001FF610");
extern f32 func_001F9CB8_09118(void *) __asm__("func_001F9CB8");
extern void func_L00_001FF4B0_09118(void *, void *, f32) __asm__("func_L00_001FF4B0");
extern s32 func_001F9850_09118(s32) __asm__("func_001F9850");
extern s32 func_L00_00258BC8_09118(s32, s32) __asm__("func_L00_00258BC8");
extern void func_L00_0026EBC0_09118(void *, void *, u32, s32, f32) __asm__("func_L00_0026EBC0");
extern void func_L00_0025F4A8_09118(void *, void *, void *, f32, f32, s32, s32, s32, f32, f32, f32, s32, f32, f32, s32, s32, s32, s32) __asm__("func_L00_0025F4A8");
extern s32 func_L00_001F2BE8_09118(f32, void *, s32, void *, void *) __asm__("func_L00_001F2BE8");

/* Update of the shot FUN_L09_00307ba8 spawns (cf. FUN_L04_002af058): moves along vel, plays its sound once it starts moving away from the hero within 3 units, dies outside the level box, and on a hit (probing along the line from the hero until the timer runs out) bursts into five sparks and a flash, damages around the hit and is removed.
   Adapted from Lombyte (MIT) for PAL by OpenRAC's tools/port.py: src/overlays/shared/gameplay/vendor/00307ba8.c, FUN_L09_00307d68. */
void func_L09_00309118(struct Moby_09118 *m)
{
    OvlVec4_09118 old;
    CollisionProbe_307d68_09118 pr;
    OvlVec4_09118 push;
    OvlVec4_09118 r;
    ShotVars_307ba8_09118 *v = (ShotVars_307ba8_09118 *)m->pvars;
    CollisionProbe_307d68_09118 *probe;
    f32 d;
    s32 i;

    d = func_001F9D10_09118(&m->pos, &D_0013F4D0_09118);
    qcopy(&old, &m->pos);
    func_001F9BD8_09118(&m->pos, &m->pos, &v->vel);
    if (v->unk28 == 0 && v->unk24 != 0 && v->dist < d && d < 3.0f) {
        func_0022ED80_09118(0, 0, m);
        v->unk28 = 1;
    }
    if (d < v->dist)
        v->unk24 = 1;
    v->dist = d;
    if (m->pos.x < 2.0f || 1021.0f < m->pos.x || m->pos.y < 2.0f || 1021.0f < m->pos.y
        || m->pos.z < 2.0f || 1021.0f < m->pos.z
        || 255.0f < func_001F9D48_09118(&m->pos, &D_L09_00166FC0_09118)) {
        func_0020D678_09118(m);
        return;
    }

    probe = 0;
    if (m->unkBC == 0) {
        pr.mask = 0x70001;
        pr.radius = 3.0f;
        pr.self = m;
        pr.unk20 = 1;
        qcopy(&pr.dir, &v->vel);
        func_001F9BF0_09118(&pr.dir, &m->pos, &D_0013F4D0_09118);
        func_L00_001FF500_09118(&pr.dir, &pr.dir, 1.0f);
        probe = &pr;
        pr.dir.f[2] = 1.0f;
        pr.dir.f[3] = 5627.9248f;
        pr.unk18 = 1;
        pr.unk19 = 3;
        pr.oclass = m->oclass;
    }
    if (func_001F9938_09118(&v->life) && m->unkBC == 0) {
        m->unkBC = 1;
        v->life = v->life_max / 4;
    } else if (v->life <= 0 && m->unkBC != 0) {
        func_0020D678_09118(m);
        return;
    }
    if (func_L00_001EFFF0_09118(&old, &m->pos, 0, v->owner, probe) == 0)
        return;

    qcopy(&m->pos, &D_L09_00174060_09118);
    if (m->unkBC == 0) {
        for (i = 0; i < 5; i++) {
            r.q = 0;
            r.f[0] = func_002140F8_09118(-1.0f, 1.0f);
            r.f[1] = func_002140F8_09118(-1.0f, 1.0f);
            r.f[2] = func_002140F8_09118(-1.0f, 1.0f);
            push.q = r.q;
            func_L00_001FF610_09118(&r, v, D_L09_00174080_09118);
            func_L00_001FF4B0_09118(&push, &push, func_001F9CB8_09118(&r) * 0.5f);
            func_001F9BD8_09118(&push, &r, &push);
            func_L00_001FF4B0_09118(&push, &push, func_002140F8_09118(D_0015EE6C_09118 * 3.0f, D_0015EE6C_09118 * 6.0f));
            func_L00_0026EBC0_09118(&m->pos, &push, 0x7F2F4F6F,
                                    func_L00_00258BC8_09118(func_001F9850_09118(10), func_001F9850_09118(15)), 60000.0f);
        }
    }
    func_L00_0025F4A8_09118(m, v, 0, 0.0f, 0.0f, 4, 3, 6, 1.1f, 0.6f, 1.0f, -1, 0.9f, 0.0f, 0, 1, -1, 0);
    func_L00_001F2BE8_09118(1.1f, &m->pos, 0x10, m, probe);
    func_0020D678_09118(m);
}
INCLUDE_ASM("asm/overlays", func_L09_0030BB28);
extern char *func_L00_0025B478(void *, int, int);
extern int func_L00_0025B4D0(void *, void *, void *, int, int *, int, int, int);
extern void func_L00_0025E4B0(void *m, short *p);
extern void func_L00_0025E590(void *, void *);
extern float func_001F9B88(float);
extern void func_L00_002584A8(void *, int, int);
extern int D_0015EE84_m __asm__("D_0015EE84") MACRO_ADDR;
extern char D_0013E633[];

/* ticks down a timer against a hit check, then reacts: either ends or switches to state 2 */
void func_L09_0030BD98(char *moby, char *d) {
    int n;
    char *m = func_L00_0025B478(moby, 0xC30000, 0);
    func_L00_0025B4D0(moby, m, d + 0x20, 0, &n, 0, 0, 4);
    if (n >= 2) {
        float v = *(float *)(d + 0x20) - *(float *)(m + 0x2C);
        *(float *)(d + 0x20) = v;
        if (v > 0.0f) {
            d[0x67] = 0x5A;
            func_L00_0025E4B0(moby, (short *)(d + 0x60));
        } else {
            if (D_0015EE84_m == 0xD && FastAbsF(*(float *)(D_0013E633 + 0xEA5) - 248.0f) < 4.0f) {
                func_L00_002584A8(moby, 0x200, -1);
            } else {
                func_L00_002584A8(moby, 0, -1);
            }
            moby[0x20] = 2;
            d[0x67] = 0x78;
            func_L00_0025E4B0(moby, (short *)(d + 0x60));
        }
    }
    ((unsigned char *)moby)[0xA4] = 0xFF;
    func_L00_0025E590(moby, d + 0x60);
}
extern int func_L01_0026EFB8(int, int);

/* Counts the live level-0x75E mobys among the 20 slots at +0xB0 and returns the last slot not counted. */
int func_L09_0030BEE8(int unused, char *m) {
    int last = -1;
    int i;
    char **slot;
    m[0x91] = func_L01_0026EFB8(*(int *)(m + 0x94), -1);
    for (i = 0, slot = (char **)(m + 0xB0); i < 20; i++, slot++) {
        char *o = *slot;
        if (o != 0 && *(short *)(o + 0xA6) == 0x75E &&
            (unsigned char)o[0x20] != 0xFE && (unsigned char)o[0x20] != 0xFD) {
            m[0x91]++;
        } else {
            last = i;
        }
    }
    return last;
}
INCLUDE_ASM("asm/overlays", func_L09_0030BF88);
extern void *func_0020D348(int);
extern float func_002140F8(float, float);
extern int func_001F9850(int);
extern void func_L00_00251E30(void *);

/* Spawns a moby of class 0x75E and initialises its data. */
char *func_L09_0030C658(int owner, void *pos, void *rot, unsigned char a, unsigned char b) {
    char *m = (char *)CreateMoby(0x75E);
    if (m) {
        char *d = *(char **)(m + 0x78);
        *(int *)(d + 0x10) = owner;
        qcopy(m + 0x10, pos);
        qcopy(d, rot);
        *(float *)(m + 0x40) = random_float_between(-3.1415927f, 3.1415927f);
        *(float *)(m + 0x44) = random_float_between(-3.1415927f, 3.1415927f);
        *(int *)(d + 0x14) = 0;
        *(short *)(d + 0x18) = scale_ticks(500);
        *(unsigned char *)(m + 0x30) = 0xFF;
        *(short *)(m + 0x32) = 0x40;
        m[0x31] = 1;
        m[0x20] = 0;
        *(float *)(m + 0x2C) = *(float *)(*(char **)(m + 0x24) + 0x24) * 0.3f;
        d[0x1C] = b;
        d[0x1A] = a;
        d[0x1B] = 0;
        func_L00_00251E30(m);
    }
    return m;
}
extern void func_0020D678(void *);

void func_L09_0030C790(void *moby, char *data)
{
    char *other = *(char **)(data + 0x10);
    if (other != 0 && *(short *)(other + 0xA6) == 0x75D &&
        (unsigned char)other[0x20] != 0xFE && (unsigned char)other[0x20] != 0xFD) {
        int index = (unsigned char)data[0x1C];
        char *base = *(char **)(other + 0x78);
        base += index * 4;
        *(int *)(base + 0xB0) = 0;
    }
    DeleteMoby(moby);
}
typedef int OvlQuad __attribute__((mode(TI)));
typedef u32 u128 __attribute__((mode(TI), aligned(16)));
typedef struct {
    f32 x;
    f32 y;
    f32 z;
    f32 w;
} Vec4f;
typedef union {
    u128 q;
    f32 f[4];
    s32 i[4];
} Vec4;
struct Manip;
struct GifEntry;
struct AnimSeq;
struct MobyClass {
    u8 pad_0[0xC];
    u8 seq_count; /* number of entries in seqs[] (menu previews clamp the sequence to it) */
    u8 pad_D[3];
    u32 unk10; /* copied into Moby.unk94 when a moby is (re)classed */
    u8 pad_14[0x8];
    void *unk1C; /* word table, indexed id * 4 + 4 (0024eec0) */
    struct GifEntry *gifs; /* patched by patch_moby_gifs */
    f32 scale; /* default draw scale: copied into Moby.scale, divides it */
    s32 unk28;
    void **callbacks; /* function-pointer table, called with the moby */
    u8 pad_30[0x14];
    u16 flags; /* initial Moby.flags */
    s16 unk46; /* class category; 5 is tested by targeting code */
    struct AnimSeq *seqs[1]; /* animation sequences, indexed by Moby.seq */
};
struct Moby {
    Vec4f bsphere;
    Vec4f pos;
    u8 state; /* >= 0xFE: dead, waiting to respawn */
    u8 group; /* linked group: index into the level moby-list table D_Lxx_001ABCC0 (0xFF: none) */
    u8 unk22; /* class slot: pclass = D_L00_00197300[unk22] (FUN_L00_002cf218) */
    u8 unk23; /* 0x40 for the smoke trail FUN_L09_00307ba8 spawns */
    struct MobyClass *pclass;
    struct Moby *next;
    f32 scale; /* draw scale (FUN_L01_002fa068 halves it, FUN_L00_00215ef8 divides by it) */
    u8 unk30; /* set to 0xFF (0x7F for beams) by spawners */
    u8 unk31; /* set to 1 by spawners */
    s16 unk32; /* set to 0xFF (0x7F for beams) by spawners */
    u16 flags;
    u16 unk36; /* set to 0x7F80 by spawners */
    u64 spawn_frame; /* frame count at which it may respawn */
    Vec4f rot; /* z: yaw (FUN_L00_00266448 compares it with atan2 to the hero) */
    u8 frame; /* animation frame */
    u8 prev_frame; /* frame index in prev_seq */
    u8 seq; /* animation sequence id */
    u8 prev_seq;
    f32 unk54;
    f32 unk58;
    u8 pad5C[8];
    struct Manip *manips;
    void *cur_frame_data;
    void *prev_frame_data;
    u8 unk70;
    u8 unk71; /* set to 0xFF when a moby changes class */
    u8 unk72;
    u8 unk73;
    void (*update)(struct Moby *moby);
    u8 *pvars;
    u8 unk7C;
    u8 pad7D;
    u8 unk7E;
    u8 unk7F; /* set to 0x17 by FUN_L09_002c5990 near D_L09_00166F40 */
    u8 pad80[0x10];
    s32 unk90;
    u32 unk94; /* set from the class header's word 0x10 */
    s32 unk98; /* set to 1 while a carrier holds the moby (FUN_L00_002c7a58) */
    u8 pad9C[8];
    u8 unkA4;
    u8 padA5;
    s16 oclass;
    u8 padA8[8];
    u8 unkB0; /* 0xB0: index into the level's D_0014C050 row (0xFF: not spawned) */
    u8 padB1;
    u16 save_id; /* index into the level collected[]/killed[] tables and save bits D_0014C190[level][id >> 5] */
    s16 unkB4;
    u8 padB6[2];
    void *unkB8; /* 0xB8: bolt source record; its byte 0xB1 is a per-level id (FUN_L00_002a6b70) */
    u8 unkBC;
    u8 padBD[3];
    Vec4f unkC0; /* 0xC0: first row of a matrix built from rot (FUN_001fa030) */
    Vec4f unkD0;
    Vec4f unkE0;
    u8 padF0[0x10];
};
extern f32 func_L00_001FF860(f32, f32);
void func_L09_0030C790(void *moby, char *data);
typedef struct {
    u8 pad0[0x18];
    s32 moby; /* 0x18: passed to FUN_002141f8 (reads moby+0x34, moby+0x78); 0 when no moby was hit */
    s32 unk1C; /* 0x1C: > 0 gates copying point and the normal into the hero (shared/ui/help/00226f10.c) */
    union {
        OvlQuad q;
        f32 f[4];
    } point; /* 0x20: f[2] is read as the ground height */
    u8 pad30[0x10]; /* 0x30: position after push-out (copied into hero.motion.pos) */
    f32 normal_x; /* 0x40: start of the surface normal; its angle is tested against 50 degrees (0.87266463) */
    f32 normal_y; /* 0x44: FUN_001f9e90 (atan2) of normal_x, normal_y is stored in the hero */
    f32 normal_z; /* 0x48: ledge probes compare atan2(normal_z, xy length) with 20 degrees */
} CollisionHit;
typedef struct {
    Vec4 vel; /* 0x00 */
    struct Moby *owner; /* 0x10: class 0x75D spawner; its pvars hold the bubble list at 0xB0 */
    struct Moby *held; /* 0x14: from FUN_L09_0030a778 when the bubble settles */
    s16 life; /* 0x18 */
    u8 unk1A;
    u8 sound_delay; /* 0x1B */
    u8 slot; /* 0x1C: index in the owner's bubble list */
} BubbleVars;
typedef struct {
    u8 pad0[0xB0];
    struct Moby *bubbles[20];
} BubbleOwnerVars;
extern f32 D_0015EE60 MACRO_ADDR;
extern f32 D_0015EE70 MACRO_ADDR;
extern CollisionHit D_L09_00174040;
extern s32 func_L00_001EFFF0(void *, void *, s32, struct Moby *, s32);
extern s32 func_L00_001F3958(void);
extern s32 func_001F9938(void *);
extern void func_001F9BD8(void *, void *, void *);
extern void func_001F9BF0(void *, void *, void *);
extern void func_001F9C30(void *, void *, f32);
extern f32 func_001F9CB8(void *);
extern f32 func_001F9CE8(void *);
extern void func_L00_001FF4B0(void *, void *, f32);
extern f32 func_002140F8(f32, f32);
extern f32 func_00214358(void *, s32, f32);
extern s32 func_0022ED80(s32, s32, struct Moby *);
extern s32 func_L00_001F10E0(f32, void *, s32, struct Moby *);
extern void func_L00_001FEF78(void *);
extern void func_L00_001FF610(void *, void *, void *);
extern void func_L00_0025B040(struct Moby *, f32);
extern f32 func_L00_0025F368(f32);
extern struct Moby *func_L09_0030BB28(struct Moby *, Vec4 *);
static inline void bubble_bounce(struct Moby *moby, BubbleVars *vars) {
    CollisionHit *hit = &D_L09_00174040;

    if (hit->moby == 0) {
        func_L00_001FF610(&vars->vel, &vars->vel, &hit->normal_x);
        if (func_L00_001FF860(hit->normal_z, func_001F9CE8(&hit->normal_x)) < 0.6981317f && CollType() == -1) {
            FastVecScale(&vars->vel, &vars->vel, 0.5f);
            if (FastVecLength(&vars->vel) < 0.025f) {
                moby->state = 1;
            }
        }
    } else if (((struct Moby *)hit->moby)->oclass != 0x75E) {
        func_L00_001FF610(&vars->vel, &vars->vel, &hit->normal_x);
        if (func_L00_001FF860(hit->normal_z, func_001F9CE8(&hit->normal_x)) < 0.6981317f && CollType() == -1) {
            FastVecScale(&vars->vel, &vars->vel, 1.2f);
        }
    } else {
        vars->vel.f[2] *= random_float_between(0.9f, 1.1f);
    }
    if (vars->sound_delay == 0) {
        func_0022ED80(0, 0, moby);
        vars->sound_delay = 12;
    }
}

/* Adapted from Lombyte (MIT) for PAL by OpenRAC's tools/port.py: src/overlays/shared/gameplay/vendor/00307ba8.c, FUN_L09_0030b3b0. */
void func_L09_0030C7F0(struct Moby *moby) {
    BubbleVars *vars = (BubbleVars *)moby->pvars;
    Vec4 prev;
    Vec4 step;
    Vec4 away;
    BubbleOwnerVars *owner;
    struct Moby *other;
    struct Moby *held;
    s32 i;
    f32 dist;
    f32 rate;

    func_L00_001FEF78(&vars->sound_delay);
    qcopy(&prev, &moby->pos);
    switch (moby->state) {
    case 0:
        moby->scale += (moby->pclass->scale - moby->scale) * (D_0015EE60 * 0.05f);
        FastVecAdd(&moby->pos, &moby->pos, &vars->vel);
        func_L00_001FF4B0(&step, &vars->vel, 0.2f);
        FastVecAdd(&step, &step, &moby->pos);
        moby->unk94 = 0;
        vars->owner->unk94 = 0;
        if (func_L00_001EFFF0(&prev, &step, 4, moby, 0) != 0) {
            FastVecSub(&step, &D_L09_00174040.point, &step);
            func_L00_001FF4B0(&step, &step, 0.215f);
            FastVecAdd(&moby->pos, &moby->pos, &step);
            bubble_bounce(moby, vars);
        }
        if (coll_sphere(0.2f, &moby->pos, 4, moby) != 0) {
            FastVecSub(&step, &D_L09_00174040.point, D_L09_00174040.pad30);
            func_L00_001FF4B0(&step, &step, 0.015f);
            FastVecAdd(&moby->pos, D_L09_00174040.pad30, &step);
            bubble_bounce(moby, vars);
        }
        owner = (BubbleOwnerVars *)vars->owner->pvars;
        for (i = 0; i < 20; i++) {
            other = owner->bubbles[i];
            if (other != moby && other != 0 && other->oclass == 0x75E && other->state != 0xFE &&
                other->state != 0xFD) {
                FastVecSub(&away, &moby->pos, &other->pos);
                away.f[2] = 0.0f;
                dist = FastVecLength(&away);
                if (dist < 1.8f) {
                    FastVecScale(&away, &away, (1.8f - dist) * (D_0015EE60 * -0.5f + 1.0f));
                    FastVecAdd(&moby->pos, &moby->pos, &away);
                }
            }
        }
        if (FastDecTimer(&vars->life) != 0) {
            moby->state = 2;
        }
        moby->rot.x = func_L00_0025F368(vars->vel.f[0]);
        moby->rot.y = func_L00_0025F368(vars->vel.f[1]);
        moby->unk94 = moby->pclass->unk10;
        vars->owner->unk94 = vars->owner->pclass->unk10;
        vars->vel.f[2] -= D_0015EE70 * 9.8f;
        moby->rot.x += D_0015EE60 * 0.01f;
        moby->rot.y += D_0015EE60 * 0.02f;
        break;
    case 1:
        moby->pos.z = func_00214358(&moby->pos, 0, 0.5f) + 0.2f;
        moby->pos.w = 0.0f;
        step.q = ((Vec4 *)&moby->pos)->q;
        vars->held = func_L09_0030BB28(vars->owner, &step);
        moby->state = 2;
        break;
    case 2:
        rate = D_0015EE60 * 0.05f;
        moby->scale -= moby->scale * rate;
        if (vars->held != 0 && vars->unk1A != 0) {
            vars->held->scale += (vars->held->pclass->scale - vars->held->scale) * rate;
        }
        if (moby->scale < moby->pclass->scale * (D_0015EE60 * 0.05f)) {
            moby->scale = 0.0001f;
            held = vars->held;
            if (held == 0 || held->state == 0xFE || held->state == 0xFD || vars->unk1A == 0 ||
                held->pclass->scale - 0.01f <= held->scale) {
                func_L09_0030C790(moby, (char *)vars);
            }
        }
        break;
    }
    func_L00_0025B040(moby, moby->scale * 0.3f / moby->pclass->scale);
    if (moby->pos.z < 5.0f || moby->pos.z > 500.0f) {
        func_L09_0030C790(moby, (char *)vars);
        return;
    }
    if (moby->pos.x < 5.0f) {
        moby->pos.x = 5.0f;
    }
    if (moby->pos.x > 1018.0f) {
        moby->pos.x = 1018.0f;
    }
    if (moby->pos.y < 5.0f) {
        moby->pos.y = 5.0f;
    }
    if (moby->pos.y > 1018.0f) {
        moby->pos.y = 1018.0f;
    }
    if (moby->pos.z < 5.0f) {
        moby->pos.z = 5.0f;
    }
    if (moby->pos.z > 1018.0f) {
        moby->pos.z = 1018.0f;
    }
}
