/* Shared code following vendor; generated by tools/overlay_src.py, stubs replaced by C as functions are matched. */
#include "common.h"
#include "include_asm.h"

INCLUDE_ASM("asm/overlays", func_L00_002D1168);
INCLUDE_ASM("asm/overlays", func_L00_002D19E8);
INCLUDE_ASM("asm/overlays", func_L00_002D1E68);
INCLUDE_ASM("asm/overlays", func_L00_002D28D8);
INCLUDE_ASM("asm/overlays", func_L00_002D2E60);
INCLUDE_ASM("asm/overlays", func_L00_002D3330);
INCLUDE_ASM("asm/overlays", func_L00_002D3608);
INCLUDE_ASM("asm/overlays", func_L00_002D3B20);
INCLUDE_ASM("asm/overlays", func_L00_002D3F40);
INCLUDE_ASM("asm/overlays", func_L00_002D42D8);
INCLUDE_ASM("asm/overlays", func_L00_002D4348);
INCLUDE_ASM("asm/overlays", func_L00_002D4398);
extern char D_0013E633[] NOT_SDA;
extern int func_001F9850(int);
extern void func_00213DE0(void *, int, int, int);
void func_L00_002D4C80(char *a) {
    if (*(int *)(D_0013E633 + 0x2EA1) == 8) {
        if (*(unsigned char *)(a + 0x53) != 6) {
            func_00213DE0(a, 6, 0, func_001F9850(10));
        }
    }
}
INCLUDE_ASM("asm/overlays", func_L00_002D4CE8);
INCLUDE_ASM("asm/overlays", func_L00_002D4EC0);
INCLUDE_ASM("asm/overlays", func_L00_002D5AC0);
INCLUDE_ASM("asm/overlays", func_L00_002D6610);
INCLUDE_ASM("asm/overlays", func_L00_002D6978);
int func_L00_002D6B90(char *a) {
    int r = func_L00_002DCDA8(a);
    if (r == 0) {
        if (*(unsigned char *)(a + 0x20) == 9) a[0x20] = 5;
    } else {
        a[0x20] = 9;
    }
    return r;
}
int func_L00_002D6C80(char *a) {
    int r = func_L00_002DD2D0(a);
    a[0x20] = 9;
    return r;
}
INCLUDE_ASM("asm/overlays", func_L00_002D6CB0);
INCLUDE_ASM("asm/overlays", func_L00_002D6CE0);
INCLUDE_ASM("asm/overlays", func_L00_002D6E38);
INCLUDE_ASM("asm/overlays", func_L00_002D7298);
INCLUDE_ASM("asm/overlays", func_L00_002D80A0);
INCLUDE_ASM("asm/overlays", func_L00_002D8180);
INCLUDE_ASM("asm/overlays", func_L00_002D83D8);
INCLUDE_ASM("asm/overlays", func_L00_002D8898);
INCLUDE_ASM("asm/overlays", func_L00_002D90A0);
INCLUDE_ASM("asm/overlays", func_L00_002D9208);
typedef struct { int a[4]; } Vy __attribute__((aligned(16)));
extern char *func_0020D348(int);
extern void func_L00_0025E210(void *);
extern void func_L00_00251328(void *, int, int, int);
extern float func_00214158(void);
extern void func_L00_00251E30(void *);
char *func_L00_002D9340(Vy *src, float f) {
    char *m = func_0020D348(0x307);
    if (m != 0) {
        func_L00_0025E210(m);
        func_L00_00251328(m, 0x28, 0x28, 0x46);
        *(unsigned char *)(m + 0x30) = 0xFF;
        *(short *)(m + 0x32) = 0x40;
        *(float *)(m + 0x2C) *= f;
        qcopy(m + 0x10, src);
        *(float *)(m + 0x48) = func_00214158();
        func_L00_00251E30(m);
    }
    return m;
}
extern void func_0020D678(void);
void func_L00_002D93E8(char *a) {
    *(float *)(a + 0x2C) = *(float *)(a + 0x2C) * 1.025f;
    a[0x23] = a[0x23] - 3;
    if ((unsigned char)a[0x23] < 4) func_0020D678();
}
