/* Level 14 (Oltanis) code following vendor; generated by tools/overlay_src.py, stubs replaced by C as functions are matched. */
#include "common.h"
#include "include_asm.h"

INCLUDE_ASM("asm/overlays", func_L14_002E0538);
INCLUDE_ASM("asm/overlays", func_L14_002E0858);
INCLUDE_ASM("asm/overlays", func_L14_002E0910);
INCLUDE_ASM("asm/overlays", func_L14_002E1058);
INCLUDE_ASM("asm/overlays", func_L14_002E9038);
INCLUDE_ASM("asm/overlays", func_L14_002EC3E8);
INCLUDE_ASM("asm/overlays", func_L14_002EC7E8);
INCLUDE_ASM("asm/overlays", func_L14_002EC9C8);
INCLUDE_ASM("asm/overlays", func_L14_002ECC70);
INCLUDE_ASM("asm/overlays", func_L14_002EDC70);
INCLUDE_ASM("asm/overlays", func_L14_002EE150);
INCLUDE_ASM("asm/overlays", func_L14_002EE260);
INCLUDE_ASM("asm/overlays", func_L14_002EE6E0);
INCLUDE_ASM("asm/overlays", func_L14_002EE990);
INCLUDE_ASM("asm/overlays", func_L14_002EF078);
INCLUDE_ASM("asm/overlays", func_L14_002EFB10);
INCLUDE_ASM("asm/overlays", func_L14_002EFD38);
INCLUDE_ASM("asm/overlays", func_L14_002F03E8);
INCLUDE_ASM("asm/overlays", func_L14_002F05D8);
INCLUDE_ASM("asm/overlays", func_L14_002F0868);
typedef struct {
    char pad0[0xAC];
    float value;
    char padB0[0x74];
    short field124;
} Level14VendorData;

typedef struct {
    char pad0[0x78];
    Level14VendorData *data;
    char pad7C[0x40];
    unsigned char state;
} Level14VendorMoby;

/* Select the vendor moby's state from its value and mark it initialized. */
void func_L14_002F0A00(Level14VendorMoby *moby) {
    Level14VendorData *data = moby->data;
    moby->state = data->value < 0.0f ? 2 : 1;
    data->field124 = 1;
}
INCLUDE_ASM("asm/overlays", func_L14_002F0A30);
INCLUDE_ASM("asm/overlays", func_L14_002F0AB8);
INCLUDE_ASM("asm/overlays", func_L14_002F0B78);
INCLUDE_ASM("asm/overlays", func_L14_002F19C0);
INCLUDE_ASM("asm/overlays", func_L14_002F24C8);
INCLUDE_ASM("asm/overlays", func_L14_002F25C8);
INCLUDE_ASM("asm/overlays", func_L14_002F2778);
INCLUDE_ASM("asm/overlays", func_L14_002F2880);
INCLUDE_ASM("asm/overlays", func_L14_002FCEA8);
INCLUDE_ASM("asm/overlays", func_L14_002FD578);
INCLUDE_ASM("asm/overlays", func_L14_002FD870);
INCLUDE_ASM("asm/overlays", func_L14_002FDD18);
INCLUDE_ASM("asm/overlays", func_L14_002FDE28);
INCLUDE_ASM("asm/overlays", func_L14_002FE038);
INCLUDE_ASM("asm/overlays", func_L14_002FE798);
INCLUDE_ASM("asm/overlays", func_L14_002FEDA0);
INCLUDE_ASM("asm/overlays", func_L14_002FF040);
