/* Level 09 (Gaspar) code following vendor; generated by tools/overlay_src.py, stubs replaced by C as functions are matched. */
#include "common.h"
#include "include_asm.h"

INCLUDE_ASM("asm/overlays", func_L09_0030B5E8);
INCLUDE_ASM("asm/overlays", func_L09_0030B648);
