/* Level 09 (Gaspar) code following vendor; generated by tools/overlay_src.py, stubs replaced by C as functions are matched. */
#include "common.h"
#include "include_asm.h"

extern float func_001FA790(float, float);
extern float func_001FA748(float, float);

void func_L09_0030B5E8(float *dst, float a, float b, float scale) {
    float v = FastSubRots(b, a) * scale;
    *dst = v;
    *dst = FastAddRots(v, a);
}
INCLUDE_ASM("asm/overlays", func_L09_0030B648);
INCLUDE_ASM("asm/overlays", func_L09_0030BA28);
