/* Level 01 (Novalis) code following vendor; generated by tools/overlay_src.py, stubs replaced by C as functions are matched. */
#include "common.h"
#include "include_asm.h"

INCLUDE_ASM("asm/overlays", func_L01_002BA898);
INCLUDE_ASM("asm/overlays", func_L01_002BABE8);
INCLUDE_ASM("asm/overlays", func_L01_002BE2C8);
INCLUDE_ASM("asm/overlays", func_L01_002E78F0);
INCLUDE_ASM("asm/overlays", func_L01_002E7B68);
INCLUDE_ASM("asm/overlays", func_L01_002E7FC8);
INCLUDE_ASM("asm/overlays", func_L01_002F1038);
INCLUDE_ASM("asm/overlays", func_L01_002F44F8);
INCLUDE_ASM("asm/overlays", func_L01_002F5720);
INCLUDE_ASM("asm/overlays", func_L01_002F5800);
INCLUDE_ASM("asm/overlays", func_L01_002F5AE8);
INCLUDE_ASM("asm/overlays", func_L01_002F5D38);
INCLUDE_ASM("asm/overlays", func_L01_002F74D0);
INCLUDE_ASM("asm/overlays", func_L01_002F7558);
INCLUDE_ASM("asm/overlays", func_L01_002F7C78);
INCLUDE_ASM("asm/overlays", func_L01_002F8B00);
INCLUDE_ASM("asm/overlays", func_L01_002F95A0);
INCLUDE_ASM("asm/overlays", func_L01_002F9640);
INCLUDE_ASM("asm/overlays", func_L01_002FA030);
INCLUDE_ASM("asm/overlays", func_L01_002FA3D8);
INCLUDE_ASM("asm/overlays", func_L01_002FA458);
INCLUDE_ASM("asm/overlays", func_L01_002FA998);
