/* Level 03 (Kerwan) code following vendor; generated by tools/overlay_src.py, stubs replaced by C as functions are matched. */
#include "common.h"
#include "include_asm.h"

INCLUDE_ASM("asm/overlays", func_L03_002CB280);
INCLUDE_ASM("asm/overlays", func_L03_002CBBD0);
INCLUDE_ASM("asm/overlays", func_L03_002CD270);
extern char *func_L00_0025B478(void *, int, int);

void func_L03_002CDBF0(unsigned char *arg) {
    char *item = func_L00_0025B478(arg, 0x130000, 0);
    if (item != 0) {
        char *other = *(char **)(item + 0x20);
        if (other != 0 && *(short *)(other + 0xA6) != *(short *)(arg + 0xA6)) {
            arg[0x20] = 4;
        }
    }
    arg[0xA4] = 0xFF;
}
INCLUDE_ASM("asm/overlays", func_L03_002CDC50);
INCLUDE_ASM("asm/overlays", func_L03_002D44A0);
extern void func_00215F80(int, int);

void func_L03_002D44C8(void *arg, int mode) {
    if (mode == 1) {
        try_set_help_message(8, 0xBC9);
    } else {
        try_set_help_message(8, 0xBC9);
    }
}
INCLUDE_ASM("asm/overlays", func_L03_002D4560);
extern float D_0015EE6C MACRO_ADDR;
extern char D_0013E633[];
extern void func_001F9BF0(void *, void *, void *);
extern void func_001F9BD8(void *, void *, void *);
extern void func_L00_001FF4B0(void *, void *, float);
extern float func_L00_001FF860(float, float);
extern char *D_L03_001B08B0[];
extern float D_0015EE70 MACRO_ADDR;
extern float D_L03_00161B88 SDATA(D_L03_00161B88);
extern float D_L03_00161B8C SDATA(D_L03_00161B8C);
extern float D_L03_00161B90 SDATA(D_L03_00161B90);
extern float D_L03_00161B94 SDATA(D_L03_00161B94);
extern float D_L03_00161B98 SDATA(D_L03_00161B98);
extern float D_L03_00161B9C SDATA(D_L03_00161B9C);
extern float func_001F9CB8(void *);
extern float func_001F9D10(void *, void *);
extern float func_00214D88(float *, float *, float, float, float, float);
extern float func_001F9CE8(void *);
extern float func_L00_0025CE58(float *, float, float *, float, float, float);
extern int func_L00_0028EB98(void *, int);
extern int func_L00_0028EF68(int, int, int, int);
extern void func_L00_0028EBF0(int);

typedef struct PathFollower4CE0 {
    char pad0[0x60]; float speed; int waypoint;
    float yawVelocity, pitchVelocity, rollVelocity;
} PathFollower4CE0;

/* Moves along a waypoint path and eases the orientation toward its direction. */
int func_L03_002D4CE0(char *moby, int pathIndex, int *sound) {
    char **entry = &D_L03_001B08B0[pathIndex];
    PathFollower4CE0 *data = *(PathFollower4CE0 **)(moby + 0x78);
    float target[4];
    float direction[4];
    float zero = 0.0f;
    float step, distance, accel, pitch;
    int finished = 0;
    char *position;
    qcopy(target, *entry + (data->waypoint * 16 + 0x10));
    position = moby + 0x10;
    func_001F9BF0(direction, target, position);
    distance = func_001F9CB8(direction);
    step = D_L03_00161B88 * D_0015EE6C;
    if (distance < step + step) {
        data->waypoint++;
        finished = data->waypoint == *(int *)*entry;
    }
    distance = func_001F9D10(position, *entry + (*(int *)*entry << 4));
    accel = D_L03_00161B8C * D_0015EE70;
    func_00214D88(&zero, &data->speed, distance, accel, accel, D_L03_00161B88 * D_0015EE6C);
    func_L00_001FF4B0(direction, direction, data->speed);
    func_001F9BD8(position, direction, position);
    pitch = -func_L00_001FF860(func_001F9CE8(direction), direction[2]);
    if (pitch > 0.261799395f) pitch = 0.261799395f;
    else if (pitch < -0.261799395f) pitch = -0.261799395f;
    func_L00_0025CE58((float *)(moby + 0x44), pitch, &data->pitchVelocity,
        D_L03_00161B90 * 0.017453292f * D_0015EE70,
        D_L03_00161B90 * 0.017453292f * D_0015EE70,
        D_0015EE6C * 12.566371f);
    func_L00_0025CE58((float *)(moby + 0x48),
        func_L00_001FF860(target[0] - *(float *)(moby + 0x10), target[1] - *(float *)(moby + 0x14)), &data->yawVelocity,
        D_L03_00161B94 * 0.017453292f * D_0015EE70,
        D_L03_00161B94 * 0.017453292f * D_0015EE70,
        D_0015EE6C * 12.566371f);
    func_L00_0025CE58((float *)(moby + 0x40),
        data->yawVelocity * data->speed * D_L03_00161B9C, &data->rollVelocity,
        D_L03_00161B98 * 0.017453292f * D_0015EE70,
        D_L03_00161B98 * 0.017453292f * D_0015EE70,
        D_0015EE6C * 12.566371f);
    if (finished == 0) {
        if (func_L00_0028EB98(moby, *sound) == 0)
            *sound = func_L00_0028EF68(0, 4, (int)moby, 0x330);
    } else {
        if (*sound != -1) {
            char *e = D_0013E633 + 0x1D + *sound * 0x70;
            if (*(char **)(e + 0x88) == moby && ((unsigned char *)e)[0x74] != 0)
                func_L00_0028EBF0(*sound);
        }
        *sound = -1;
    }
    return finished;
}
extern void func_L00_00263B78(float, float, char *, float *, float *);
extern void func_L00_00263BF8(void *, char *, char *, float, float, float);
extern float D_0015EE6C MACRO_ADDR;
extern short D_L03_00161B70_g __asm__("D_L03_00161B70");
extern short D_L03_00161B74_g __asm__("D_L03_00161B74");
extern short D_L03_00161B78_g __asm__("D_L03_00161B78");
extern short D_L03_00161B7C_g __asm__("D_L03_00161B7C");
extern short D_L03_00161B80_g __asm__("D_L03_00161B80");

/* Sets two speed pairs on a moby's data from level constants scaled by degrees-to-radians and the frame scale. */
void func_L03_002D5008(char *m) {
    char *d = *(char **)(m + 0x78);
    func_L00_00263B78(*(float *)&D_L03_00161B70_g, *(float *)&D_L03_00161B74_g * 0.0174532925f * D_0015EE6C, m, (float *)(d + 0xEC), (float *)(d + 0xE8));
    func_L00_00263BF8(m, d + 0xF0, d + 0xF4, *(float *)&D_L03_00161B78_g, *(float *)&D_L03_00161B7C_g * 0.0174532925f * D_0015EE6C, *(float *)&D_L03_00161B80_g * 0.0174532925f * D_0015EE6C);
}
INCLUDE_ASM("asm/overlays", func_L03_002D5220);
extern struct Moby *func_0020D348_m(int) __asm__("func_0020D348");
extern float func_L00_001FF860(float, float);
extern int func_001F9850(int);
extern int func_L00_001EFFF0(void *, void *, int, void *, void *);
extern void func_L00_00251E30(void *);
extern char D_L03_00173FE0[];

typedef int u128 __attribute__((mode(TI)));

// Spawns a moby of class 0x341 at a position, initialises its data and registers it.
char *func_L03_002D5650(char *a, char *pos, char *parent, int n, float f0, float f1, float f2) {
    char *m = (char *)func_0020D348_m(0x341);
    char *d;
    if (m != 0) {
        float v[4];
        *(unsigned char *)(m + 0x30) = 0xFF;
        *(short *)(m + 0x32) = 0x7E;
        d = *(char **)(m + 0x78);
        m[0x31] = 1;
        m[0x20] = 1;
        qcopy(m + 0x10, pos);
        qcopy(d, a);
        *(float *)(m + 0x48) = func_L00_001FF860(*(float *)d, *(float *)(d + 4));
        *(int *)(d + 0x14) = func_001F9850(n);
        *(float *)(d + 0x18) = f2;
        *(float *)(d + 0x1C) = f0;
        *(float *)(d + 0x24) = f1;
        *(char **)(d + 0x10) = parent;
        *(int *)(d + 0x28) = 0;
        *(u128 *)v = *(u128 *)(parent + 0x10);
        v[2] = *(float *)(pos + 8);
        if (func_L00_001EFFF0(v, pos, 2, parent, 0) != 0) {
            *(int *)(d + 0x14) = 0;
            *(u128 *)(m + 0x10) = *(u128 *)D_L03_00173FE0;
            *(int *)(d + 0x24) = 0;
        }
        func_L00_00251E30(m);
    }
    return m;
}
INCLUDE_ASM("asm/overlays", func_L03_002D5790);
INCLUDE_ASM("asm/overlays", func_L03_002DBAD8);
INCLUDE_ASM("asm/overlays", func_L03_002DBC38);
INCLUDE_ASM("asm/overlays", func_L03_002DC3E8);
INCLUDE_ASM("asm/overlays", func_L03_002DC560);
INCLUDE_ASM("asm/overlays", func_L03_002DC648);
INCLUDE_ASM("asm/overlays", func_L03_002DC920);
INCLUDE_ASM("asm/overlays", func_L03_002DD158);
INCLUDE_ASM("asm/overlays", func_L03_002DDE38);
INCLUDE_ASM("asm/overlays", func_L03_002DDE9C);
INCLUDE_ASM("asm/overlays", func_L03_002DDEF8);
int func_L03_002DDF10(unsigned char *moby, char *data) {
    if (moby[0x20] && *(int *)(data + 0x7C) == 1) {
        return 1;
    }
    return 0;
}
extern int func_001FFB38(int, int, int, int, int, int, int);
extern void func_L00_002367A8(int, int);
extern void func_L00_00237B20(void);
extern void func_L00_00237B70(void);
extern void func_L00_00237B90(void);

/* Shows a help message for the mode, then keeps a hud queue entry alive. */
void func_L03_002DDF90(char *m, int mode) {
    char *d = *(char **)(m + 0x78);
    int h;
    switch (mode) {
    case 1:
        func_00215F80(8, 0xBCE);
        break;
    case 2:
        func_00215F80(8, 0xBCF);
        break;
    case 3:
        func_00215F80(8, 0xBCB);
        break;
    case 4:
        func_00215F80(8, 0xBCD);
        break;
    default:
        func_00215F80(8, -1);
        break;
    }
    h = *(int *)(d + 0xA4);
    if (h == -1) {
        *(int *)(d + 0xA4) = func_001FFB38(0xC, 0, (int)func_L00_00237B20, (int)func_L00_00237B70, (int)func_L00_00237B90, 0, 0);
    } else {
        func_L00_002367A8(h, 0xA);
    }
}
INCLUDE_ASM("asm/overlays", func_L03_002DE088);
extern short D_L03_00161C58;
extern short D_L03_00161C5C;
extern short D_L03_00161C60;
extern short D_L03_00161C64;
extern short D_L03_00161C68;
extern void func_L00_00263B78(float x, float y, char *a, float *p, float *q);
/* sets two aim angles on a moby from level constants scaled by degrees-to-radians */
void func_L03_002DE4B8(char *moby) {
    char *data = *(char **)(moby + 0x78);
    func_L00_00263B78(*(float *)&D_L03_00161C58, *(float *)&D_L03_00161C5C * 0.017453292f * D_0015EE6C, moby, (float *)(data + 0xAC), (float *)(data + 0xA8));
    func_L00_00263BF8((float *)moby, (float *)(data + 0xB0), (float *)(data + 0xB4), *(float *)&D_L03_00161C60, *(float *)&D_L03_00161C64 * 0.017453292f * D_0015EE6C, *(float *)&D_L03_00161C68 * 0.017453292f * D_0015EE6C);
}
INCLUDE_ASM("asm/overlays", func_L03_002E08E8);
INCLUDE_ASM("asm/overlays", func_L03_002E1598);
extern void func_0022ED80(int, int, int);
extern void func_L01_00279790(void *);
extern void func_L00_00264EA8(void *, int, int, int, int, int, int);
extern void func_L01_00279E10(void *, int);
extern void func_0020D678(void *);
void func_L03_002E3D10(char *m) {
    int hit = 0;
    char *r = func_L00_0025B478(m, 0x10000, 0);
    switch (*(unsigned char *)(m + 0x20)) {
    case 0:
        m[0x20] = 1;
        break;
    case 1:
        if (r != 0 && *(float *)(r + 0x2C) > 0.0f) hit = 1;
        if (hit) m[0x20] = 2;
        break;
    case 2:
        func_0022ED80(0, 0, (int)m);
        func_L01_00279790(m);
        func_L00_00264EA8(m, 0x725, 1, 0x725, 1, 1, 2);
        func_L01_00279E10(m, 0x724);
        DeleteMoby(m);
        break;
    }
}
INCLUDE_ASM("asm/overlays", func_L03_002ECBA8);
extern char D_0013E633[];
typedef struct CameraSmoothECD40 {
    float position[4]; int sourceFlag; float duration;
} CameraSmoothECD40;
typedef struct CameraZoomECD40 {
    float start, pad4, end, padC, weight;
} CameraZoomECD40;
typedef struct CameraOrientationECD40 {
    float vector[4]; char pad10[0x10];
    int flags20, flags24, flags28, flags2C, flags30;
    float height;
} CameraOrientationECD40;
typedef struct CameraDataECD40 {
    float position[4], motion[4]; float speed, acceleration;
    int state, pad2C, timer; char pad34[0x7C];
    CameraSmoothECD40 origin; char padC8[8];
    CameraZoomECD40 zoom; char padE4[0xC];
    CameraOrientationECD40 orientation;
} CameraDataECD40;
typedef struct CameraMobyECD40 {
    char pad0[0x70]; CameraDataECD40 *camera;
    char pad74[0xA]; short resetFlag;
    char pad80[4]; short index;
} CameraMobyECD40;
typedef struct CameraConfigECD40 {
    char pad0[0x20]; float range, weight;
} CameraConfigECD40;
typedef struct CameraEntryECD40 {
    char pad0[0x10]; float rotation[3]; CameraConfigECD40 *config;
} CameraEntryECD40;
extern CameraEntryECD40 *D_L03_0015F050_camera __asm__("D_L03_0015F050") MACRO_ADDR;

extern int D_L03_001670F4;
extern void func_001F9BC0(void *);
extern void func_001FA1F8(void *, void *);
extern void func_L03_002ECBA8(void *);
extern int func_001F9850(int);

/* ActivateCamera_14: seed the camera's smoothing state from the current camera table entry */
void func_L03_002ECD40(char *m) {
    CameraMobyECD40 *mob = (CameraMobyECD40 *)m;
    char *g = D_0013E633 + 0xE1D;
    CameraConfigECD40 *e = D_L03_0015F050_camera[mob->index].config;
    CameraSmoothECD40 *d1;
    CameraZoomECD40 *v;
    CameraDataECD40 *a;
    CameraDataECD40 *b;
    CameraOrientationECD40 *c;
    CameraEntryECD40 *dd;
    float t, height;
    float buf[16];
    d1 = &mob->camera->origin;
    d1->duration = 1.5f;
    d1->sourceFlag = *(int *)(g + 0x2080);
    qcopy(d1, g + 0x80);
    *(int *)&d1->position[3] = 0;
    v = &mob->camera->zoom;
    t = e->range;
    v->end = t;
    v->start = t;
    v->weight = e->weight;
    a = mob->camera;
    a->state = 0;
    a->speed = 0.01f;
    a->acceleration = 0.2f;
    func_001F9BC0(a->motion);
    qcopy(a, g + 0x80);
    b = mob->camera;
    b->timer = func_001F9850(0x78);
    dd = D_L03_0015F050_camera;
    c = &mob->camera->orientation;
    c->flags30 = 0;
    c->flags28 = 0;
    c->flags2C = 0;
    height = *(float *)(g + 0x88);
    c->flags20 = 0;
    c->height = height;
    c->flags24 = 0;
    {
        int entry = mob->index << 5;
        entry += (int)dd;
        entry += 0x10;
        buf[12] = *(float *)(entry + 0);
        buf[13] = *(float *)(entry + 4);
        buf[14] = *(float *)(entry + 8);
    }
    *(int *)(buf + 15) = 0;
    func_001FA1F8(buf, buf + 12);
    qcopy(c, buf);
    func_L03_002ECBA8(m);
    mob->resetFlag = 0;
    D_L03_001670F4 = 0x78;
}
extern void func_L00_001FF4B0(void *, void *, float);
extern float func_001EC120(void *, float, float, float, float, float);
extern void func_001F9BD8(void *, void *, void *);
extern char D_0013E633[];

// Smooths a camera-like moby's position toward the player's and sets its orientation vector.
void func_L03_002ECEC8(void *arg) {
    char *m = arg;
    char *d = *(char **)(m + 0x70);
    char *a = d + 0xD0;
    char *b = d + 0xF0;
    char *g = D_0013E633 + 0xE1D;
    float v3[4];
    float v1[4];
    float v2[4];
    char *h;
    if (*(int *)(g + 0x2284) != 0x50 || *(int *)(g + 0x2084) == 0x11) {
        *(float *)(b + 0x34) = *(float *)(g + 0x88);
    }
    func_L00_001FF4B0(v1, D_0013E633 + 0x10AD, -*(float *)(a + 0x10));
    func_L00_001FF4B0(v3, b, -*(float *)a);
    h = D_0013E633 + 0xE1D;
    *(float *)d = Cam_InterpValues(d + 0x10, *(float *)d, *(float *)(h + 0x80), *(float *)(d + 0x20), *(float *)(d + 0x24), *(float *)(d + 0x28));
    *(float *)(d + 4) = Cam_InterpValues(d + 0x14, *(float *)(d + 4), *(float *)(h + 0x84), *(float *)(d + 0x20), *(float *)(d + 0x24), *(float *)(d + 0x28));
    *(float *)(d + 8) = Cam_InterpValues(d + 0x18, *(float *)(d + 8), *(float *)(b + 0x34), *(float *)(d + 0x20), *(float *)(d + 0x24), *(float *)(d + 0x28));
    FastVecAdd(v2, d, v1);
    FastVecAdd(v2, v2, v3);
    *(float *)(m + 0x30) = v2[0];
    *(float *)(m + 0x34) = v2[1];
    *(float *)(m + 0x38) = v2[2];
}
extern char D_0013E633[];
extern float func_001EC120(void *, float, float, float, float, float);
extern void func_L00_001FF4B0(void *, void *, float);
extern void func_001F9BD8(void *, void *, void *);
extern void func_001F9BF0(void *, void *, void *);
extern void func_001F9CA0(void *, void *, void *);
extern short D_L03_00161EF0;
extern short D_L03_00161EF4;
extern char D_L03_00166FC0[];

/* smooths the moby's data floats and rebuilds its orientation axes */
void func_L03_002ED020(void *arg) {
    char *m = arg;
    char *d = *(char **)(m + 0x70);
    float *p = (float *)(d + 0xB0);
    float a[4];
    float b[4];
    float c[4];
    qcopy(b, d);
    p[2] = Cam_InterpValues(d + 0xBC, p[2], *(float *)(D_0013E633 + 0xEA5), *(float *)&D_L03_00161EF0, *(float *)&D_L03_00161EF4, 0.0f);
    func_L00_001FF4B0(c, D_L03_00166FC0, p[5]);
    FastVecAdd(b, c, b);
    FastVecSub(a, b, m + 0x30);
    func_L00_001FF4B0(m, a, 1.0f);
    qcopy(m + 0x40, m);
    FastVecCross(m + 0x10, m, D_L03_00166FC0 - 0x10);
    func_L00_001FF4B0(m + 0x10, m + 0x10, 1.0f);
    FastVecCross(m + 0x20, m + 0x10, m);
}
INCLUDE_ASM("asm/overlays", func_L03_002ED138);
extern void func_L03_002ECEC8(void *);
extern void func_001E9768(void *);
extern void func_L03_002ED020(void *);

void func_L03_002ED178(void *arg) {
    func_L03_002ECEC8(arg);
    func_001E9768(arg);
    func_L03_002ED020(arg);
}
extern int D_L03_0015F050 MACRO_ADDR;
extern char D_0013E633[];
extern int func_00215570(void *, int);

void func_L03_002ED1B0(char *moby)
{
    char *entry = (char *)((*(short *)(moby + 0x84) << 5) + D_L03_0015F050);
    char *sub = *(char **)(entry + 0x1C);
    int value = *(int *)(sub + 0xC);
    if (value >= 0 && is_point_inside_clip_volume(D_0013E633 + 0xE9D, value) == 0) {
        *(short *)(moby + 0x7E) = 3;
    }
}
