/* Level 03 (Kerwan) code following vendor; generated by tools/overlay_src.py, stubs replaced by C as functions are matched. */
#include "common.h"
#include "include_asm.h"

INCLUDE_ASM("asm/overlays", func_L03_002CB280);
INCLUDE_ASM("asm/overlays", func_L03_002CBBD0);
typedef u32 u128_CD270 __attribute__((mode(TI), aligned(16)));
typedef struct {
    f32 x;
    f32 y;
    f32 z;
    f32 w;
} Vec4f;
typedef union {
    u128_CD270 q;
    f32 f[4];
    s32 i[4];
} Vec4;
struct Manip;
struct GifEntry;
struct AnimSeq;
struct MobyClass {
    u8 pad_0[0xC];
    u8 seq_count; /* number of entries in seqs[] (menu previews clamp the sequence to it) */
    u8 pad_D[3];
    u32 unk10; /* copied into Moby.unk94 when a moby is (re)classed */
    u8 pad_14[0x8];
    void *unk1C; /* word table, indexed id * 4 + 4 (0024eec0) */
    struct GifEntry *gifs; /* patched by patch_moby_gifs */
    f32 scale; /* default draw scale: copied into Moby.scale, divides it */
    s32 unk28;
    void **callbacks; /* function-pointer table, called with the moby */
    u8 pad_30[0x14];
    u16 flags; /* initial Moby.flags */
    s16 unk46; /* class category; 5 is tested by targeting code */
    struct AnimSeq *seqs[1]; /* animation sequences, indexed by Moby.seq */
};
struct Moby {
    Vec4f bsphere;
    Vec4f pos;
    u8 state; /* >= 0xFE: dead, waiting to respawn */
    u8 group; /* linked group: index into the level moby-list table D_Lxx_001ABCC0 (0xFF: none) */
    u8 unk22; /* class slot: pclass = D_L00_00197300[unk22] (FUN_L00_002cf218) */
    u8 unk23; /* 0x40 for the smoke trail FUN_L09_00307ba8 spawns */
    struct MobyClass *pclass;
    struct Moby *next;
    f32 scale; /* draw scale (FUN_L01_002fa068 halves it, FUN_L00_00215ef8 divides by it) */
    u8 unk30; /* set to 0xFF (0x7F for beams) by spawners */
    u8 unk31; /* set to 1 by spawners */
    s16 unk32; /* set to 0xFF (0x7F for beams) by spawners */
    u16 flags;
    u16 unk36; /* set to 0x7F80 by spawners */
    u64 spawn_frame; /* frame count at which it may respawn */
    Vec4f rot; /* z: yaw (FUN_L00_00266448 compares it with atan2 to the hero) */
    u8 frame; /* animation frame */
    u8 prev_frame; /* frame index in prev_seq */
    u8 seq; /* animation sequence id */
    u8 prev_seq;
    f32 unk54;
    f32 unk58;
    u8 pad5C[8];
    struct Manip *manips;
    void *cur_frame_data;
    void *prev_frame_data;
    u8 unk70;
    u8 unk71; /* set to 0xFF when a moby changes class */
    u8 unk72;
    u8 unk73;
    void (*update)(struct Moby *moby);
    u8 *pvars;
    u8 unk7C;
    u8 pad7D;
    u8 unk7E;
    u8 unk7F; /* set to 0x17 by FUN_L09_002c5990 near D_L09_00166F40 */
    u8 pad80[0x10];
    s32 unk90;
    u32 unk94; /* set from the class header's word 0x10 */
    s32 unk98; /* set to 1 while a carrier holds the moby (FUN_L00_002c7a58) */
    u8 pad9C[8];
    u8 unkA4;
    u8 padA5;
    s16 oclass;
    u8 padA8[8];
    u8 unkB0; /* 0xB0: index into the level's D_0014C050 row (0xFF: not spawned) */
    u8 padB1;
    u16 save_id; /* index into the level collected[]/killed[] tables and save bits D_0014C190[level][id >> 5] */
    s16 unkB4;
    u8 padB6[2];
    void *unkB8; /* 0xB8: bolt source record; its byte 0xB1 is a per-level id (FUN_L00_002a6b70) */
    u8 unkBC;
    u8 padBD[3];
    Vec4f unkC0; /* 0xC0: first row of a matrix built from rot (FUN_001fa030) */
    Vec4f unkD0;
    Vec4f unkE0;
    u8 padF0[0x10];
};
void func_L03_002CDBF0(unsigned char *arg);
extern float D_0015EE6C MACRO_ADDR;
struct Moby;
struct MobyTrail {
    Vec4 pos[8]; /* 0x00: ring of source positions */
    Vec4 rot[8]; /* 0x80: ring of source rotations */
    s32 copy_fade[4]; /* 0x100: start of copy moby byte 0x23; all 0 ends the trail */
    s32 delay[4]; /* 0x110: frames each copy lags behind */
    struct Moby *copies[4]; /* 0x120 */
    s16 head; /* 0x130: next ring slot */
    s16 count; /* 0x132: ring entries filled (max 8) */
    struct Moby *source; /* 0x134 */
    s32 copy_count; /* 0x138: copies in use (max 4) */
    s32 active; /* 0x13C */
};
struct HeroItemSlot {
    struct Moby *moby; /* 0x00: item moby */
    struct Moby *moby2; /* 0x04: second item moby */
    u8 pad_08[0x8];
    s32 button_mask; /* 0x10: pad buttons that hold the gadget states */
    s32 unk14; /* 0x14: set on release */
    s16 timer; /* 0x18: counts down; a slot change waits for 0 */
    u8 unk1A; /* 0x1A: cleared on a slot change */
    u8 pad_1B[0x1];
    u8 unk1C; /* 0x1C: 2 blocks a slot change, 1 reloads timer */
    u8 timer_reload; /* 0x1D: timer reload value */
    u8 pad_1E[0x2];
    s32 unk20; /* 0x20 */
    s32 state; /* 0x24: 0 empty, 2 ready, 3 released */
    s32 item_id; /* 0x28: item in the slot */
    u8 pad_2C[0x24];
};
struct HeroMotion {
    Vec4 pos; /* 0x80: world position */
    Vec4 rot; /* 0x90: rotation; z is the yaw */
    Vec4 unkA0; /* 0xA0 */
    Vec4 unkB0; /* 0xB0 */
    Vec4 unkC0; /* 0xC0 */
    Vec4 unkD0; /* 0xD0 */
    Vec4 velocity; /* 0xE0: per-frame velocity */
    Vec4 unkF0; /* 0xF0 */
    Vec4 unk100; /* 0x100 */
    Vec4 unk110; /* 0x110 */
    Vec4 unk120; /* 0x120 */
    Vec4 unk130; /* 0x130 */
    Vec4 unk140; /* 0x140 */
    Vec4 unk150; /* 0x150: copied from unk110/unk100 on hero_set_state */
    f32 unk160; /* 0x160 */
    f32 unk164; /* 0x164 */
    f32 unk168; /* 0x168 */
    f32 unk16C; /* 0x16C */
    Vec4 unk170; /* 0x170 */
    f32 unk180; /* 0x180: angle, compared with rot.z */
    f32 unk184; /* 0x184 */
    f32 unk188; /* 0x188 */
    u8 pad_18C[0x4];
};
struct HeroRandTimer {
    s32 fired; /* 0xFF0: 1 once the deadline passed */
    s32 deadline; /* 0xFF4: frame count to wait for */
    s32 range; /* 0xFF8: random span; 0 holds the timer off */
};
struct HeroState {
    s32 current; /* 0x2084: state id; hero_set_state sets it */
    s32 step; /* 0x2088: sub-step, 0 on state change */
    s32 control_mode; /* 0x208C */
    s32 prev; /* 0x2090: state before the last change */
    s32 prev_control_mode; /* 0x2094: control_mode before the last change */
    s32 prev_timer; /* 0x2098: state_timer before the last change */
    s32 prev2; /* 0x209C: state before prev */
    s32 prev2_control_mode; /* 0x20A0: control mode before prev_control_mode */
};
struct HeroHealth {
    s32 hp; /* 0x22A8: hit points; 0 = dead */
    s32 unk22AC; /* 0x22AC: swapped with health.hp */
    s16 unk22B0; /* 0x22B0: s16 copy of health.hp */
    s16 unk22B2; /* 0x22B2 */
};
struct Hero {
    u8 pad_0[0x40];
    f32 unk40[16]; /* 0x40 */
    struct HeroMotion motion; /* 0x80 */
    f32 unk190; /* 0x190 */
    f32 unk194; /* 0x194 */
    s32 state_timer; /* 0x198: frames in the current state */
    s32 unk19C; /* 0x19C */
    s32 unk1A0; /* 0x1A0 */
    s32 unk1A4; /* 0x1A4 */
    s32 unk1A8; /* 0x1A8 */
    s32 unk1AC; /* 0x1AC */
    s16 unk1B0; /* 0x1B0 */
    s16 unk1B2; /* 0x1B2 */
    s32 unk1B4; /* 0x1B4 */
    s32 unk1B8; /* 0x1B8 */
    s32 unk1BC; /* 0x1BC */
    s32 unk1C0; /* 0x1C0 */
    s32 unk1C4; /* 0x1C4 */
    s16 unk1C8; /* 0x1C8 */
    s16 unk1CA; /* 0x1CA */
    s32 unk1CC; /* 0x1CC */
    s32 unk1D0; /* 0x1D0 */
    s32 unk1D4; /* 0x1D4 */
    s16 unk1D8; /* 0x1D8 */
    s16 unk1DA; /* 0x1DA */
    s16 unk1DC; /* 0x1DC */
    s16 unk1DE; /* 0x1DE */
    s16 unk1E0; /* 0x1E0 */
    s16 unk1E2; /* 0x1E2 */
    s16 unk1E4; /* 0x1E4 */
    s16 unk1E6; /* 0x1E6 */
    s16 unk1E8; /* 0x1E8 */
    s16 unk1EA; /* 0x1EA */
    s16 unk1EC; /* 0x1EC */
    s16 unk1EE; /* 0x1EE */
    s16 unk1F0; /* 0x1F0 */
    s16 unk1F2; /* 0x1F2 */
    s16 unk1F4; /* 0x1F4 */
    s16 unk1F6; /* 0x1F6 */
    s16 unk1F8; /* 0x1F8 */
    u8 pad_1FA[0x6];
    Vec4 unk200; /* 0x200 */
    Vec4 unk210; /* 0x210 */
    f32 unk220; /* 0x220 */
    f32 unk224; /* 0x224 */
    f32 unk228; /* 0x228 */
    f32 unk22C; /* 0x22C */
    f32 unk230; /* 0x230 */
    f32 unk234; /* 0x234 */
    u8 pad_238[0x4];
    u8 *coll_hit_moby; /* 0x23C: moby of the last push-out collision hit */
    s32 unk240; /* 0x240 */
    u8 pad_244[0x4];
    f32 unk248; /* 0x248 */
    u8 pad_24C[0xB];
    u8 unk257; /* 0x257 */
    u8 pad_258[0x18];
    Vec4 unk270; /* 0x270 */
    Vec4 unk280; /* 0x280 */
    Vec4 unk290; /* 0x290 */
    Vec4 unk2A0; /* 0x2A0 */
    Vec4 unk2B0; /* 0x2B0 */
    union { f32 f[2]; s32 i[2]; } unk2C0; /* 0x2C0: written as floats and zeroed as ints */
    union { f32 f[2]; s32 i[2]; } unk2C8; /* 0x2C8: written as floats and zeroed as ints */
    union { f32 f[2]; s32 i[2]; } unk2D0; /* 0x2D0: written as floats and zeroed as ints */
    union { f32 f; s32 i; } unk2D8; /* 0x2D8: written as a float and zeroed as an int */
    f32 unk2DC; /* 0x2DC */
    union { f32 f; s32 i; } unk2E0; /* 0x2E0: written as a float and zeroed as an int */
    union { f32 f; s32 i; } unk2E4; /* 0x2E4: written as a float and zeroed as an int */
    union { f32 f; s32 i; } unk2E8; /* 0x2E8: written as a float and zeroed as an int */
    f32 unk2EC; /* 0x2EC */
    f32 height_threshold; /* 0x2F0 */
    f32 unk2F4; /* 0x2F4 */
    s32 unk2F8; /* 0x2F8 */
    struct Moby *unk2FC; /* 0x2FC */
    s32 unk300; /* 0x300 */
    f32 unk304; /* 0x304 */
    s16 unk308; /* 0x308 */
    s16 unk30A; /* 0x30A */
    union { s16 s; u16 u; } unk30C; /* 0x30C: read signed, incremented unsigned */
    union { s16 s; u16 u; } unk30E; /* 0x30E: read signed, incremented unsigned */
    u8 pad_310[0xA0];
    f32 unk3B0; /* 0x3B0 */
    s32 unk3B4; /* 0x3B4 */
    s16 unk3B8; /* 0x3B8 */
    u8 pad_3BA[0x2];
    s16 unk3BC; /* 0x3BC */
    s16 unk3BE; /* 0x3BE */
    u8 pad_3C0[0x10];
    s32 unk3D0; /* 0x3D0 */
    s32 unk3D4; /* 0x3D4 */
    f32 unk3D8; /* 0x3D8 */
    f32 unk3DC; /* 0x3DC */
    s32 unk3E0; /* 0x3E0 */
    u8 *unk3E4; /* 0x3E4 */
    s32 unk3E8; /* 0x3E8 */
    u8 pad_3EC[0x8];
    f32 unk3F4; /* 0x3F4 */
    f32 unk3F8; /* 0x3F8 */
    u8 pad_3FC[0x4];
    Vec4 unk400; /* 0x400 */
    f32 unk410; /* 0x410 */
    f32 unk414; /* 0x414 */
    s32 unk418; /* 0x418: set when velocity.z clamps to unk500.z, counts up */
    s16 unk41C; /* 0x41C */
    s16 unk41E; /* 0x41E: set to 1 when FUN_L00_00233a78(velocity) < 0.001 */
    s32 unk420; /* 0x420: per-state scale_game_frames(N), compared with state_timer */
    f32 unk424; /* 0x424 */
    f32 unk428; /* 0x428 */
    f32 unk42C; /* 0x42C */
    f32 unk430; /* 0x430 */
    f32 unk434; /* 0x434 */
    f32 unk438; /* 0x438 */
    f32 unk43C; /* 0x43C */
    f32 unk440; /* 0x440 */
    f32 unk444; /* 0x444 */
    f32 unk448; /* 0x448 */
    s32 unk44C; /* 0x44C */
    s32 unk450; /* 0x450 */
    f32 unk454; /* 0x454 */
    f32 unk458; /* 0x458 */
    f32 unk45C; /* 0x45C */
    Vec4 unk460; /* 0x460 */
    Vec4 unk470; /* 0x470 */
    f32 unk480; /* 0x480 */
    f32 unk484; /* 0x484 */
    f32 unk488; /* 0x488 */
    f32 unk48C; /* 0x48C */
    f32 unk490; /* 0x490 */
    f32 unk494; /* 0x494 */
    s16 unk498; /* 0x498 */
    s16 unk49A; /* 0x49A */
    s16 unk49C; /* 0x49C */
    s16 unk49E; /* 0x49E */
    f32 unk4A0; /* 0x4A0 */
    s16 unk4A4; /* 0x4A4 */
    s16 unk4A6; /* 0x4A6 */
    s16 unk4A8; /* 0x4A8 */
    s16 unk4AA; /* 0x4AA */
    s16 unk4AC; /* 0x4AC */
    u8 unk4AE; /* 0x4AE */
    u8 unk4AF; /* 0x4AF */
    f32 unk4B0; /* 0x4B0 */
    u8 pad_4B4[0x4];
    f32 unk4B8; /* 0x4B8 */
    s32 unk4BC; /* 0x4BC */
    f32 unk4C0; /* 0x4C0 */
    s32 unk4C4; /* 0x4C4 */
    u8 pad_4C8[0x8];
    Vec4 unk4D0; /* 0x4D0 */
    u8 pad_4E0[0x4];
    f32 unk4E4; /* 0x4E4 */
    s32 unk4E8; /* 0x4E8 */
    f32 unk4EC; /* 0x4EC */
    f32 unk4F0; /* 0x4F0 */
    u8 pad_4F4[0x4];
    s32 unk4F8; /* 0x4F8: first argument of FUN_L00_00233f80 (FUN_L01_00233de0) */
    u8 pad_4FC[0x4];
    Vec4 unk500; /* 0x500 */
    Vec4 unk510; /* 0x510 */
    Vec4 unk520; /* 0x520 */
    Vec4 unk530; /* 0x530 */
    Vec4 unk540; /* 0x540 */
    Vec4 unk550; /* 0x550 */
    s32 unk560; /* 0x560 */
    s32 unk564; /* 0x564 */
    f32 unk568; /* 0x568 */
    s32 unk56C; /* 0x56C */
    s32 unk570; /* 0x570 */
    f32 unk574; /* 0x574 */
    s32 unk578; /* 0x578 */
    f32 unk57C; /* 0x57C */
    f32 unk580; /* 0x580 */
    s32 unk584; /* 0x584 */
    f32 unk588; /* 0x588 */
    s32 unk58C; /* 0x58C */
    s32 unk590; /* 0x590 */
    s32 unk594; /* 0x594 */
    s32 unk598; /* 0x598 */
    f32 unk59C; /* 0x59C */
    s32 unk5A0; /* 0x5A0 */
    s32 unk5A4; /* 0x5A4 */
    s32 unk5A8; /* 0x5A8 */
    union { f32 f; s32 i; } unk5AC; /* 0x5AC: float approached toward a speed, zeroed as an int */
    f32 unk5B0; /* 0x5B0 */
    s32 unk5B4; /* 0x5B4 */
    s32 unk5B8; /* 0x5B8 */
    s16 unk5BC; /* 0x5BC */
    s16 unk5BE; /* 0x5BE */
    s32 unk5C0; /* 0x5C0 */
    s32 unk5C4; /* 0x5C4 */
    f32 unk5C8; /* 0x5C8 */
    f32 unk5CC; /* 0x5CC */
    f32 unk5D0; /* 0x5D0 */
    f32 unk5D4; /* 0x5D4 */
    struct Moby *unk5D8; /* 0x5D8 */
    f32 unk5DC; /* 0x5DC */
    Vec4 unk5E0; /* 0x5E0 */
    s32 *unk5F0; /* 0x5F0 */
    s32 unk5F4; /* 0x5F4 */
    f32 unk5F8; /* 0x5F8 */
    s32 unk5FC; /* 0x5FC */
    s32 unk600; /* 0x600 */
    f32 unk604; /* 0x604 */
    u8 pad_608[0x4];
    s32 unk60C; /* 0x60C */
    f32 unk610; /* 0x610 */
    f32 unk614; /* 0x614 */
    union { f32 f; s32 i; } unk618; /* 0x618: float distance clamp, zeroed as an int */
    u8 pad_61C[0x54];
    f32 unk670; /* 0x670 */
    f32 unk674; /* 0x674 */
    u8 pad_678[0x10];
    f32 unk688; /* 0x688 */
    u8 pad_68C[0x4];
    f32 unk690; /* 0x690 */
    f32 unk694; /* 0x694 */
    s32 unk698; /* 0x698 */
    f32 unk69C; /* 0x69C */
    s32 unk6A0; /* 0x6A0 */
    struct Moby *unk6A4; /* 0x6A4 */
    u8 pad_6A8[0x18];
    Vec4 unk6C0; /* 0x6C0: 0x60 bytes cleared by FillTransferWords */
    f32 unk6D0; /* 0x6D0 */
    f32 unk6D4; /* 0x6D4 */
    u8 pad_6D8[0x48];
    Vec4 unk720; /* 0x720 */
    u8 pad_730[0x10];
    Vec4 unk740; /* 0x740 */
    Vec4 unk750; /* 0x750 */
    Vec4 unk760; /* 0x760 */
    Vec4 unk770; /* 0x770 */
    Vec4 unk780; /* 0x780 */
    Vec4 unk790; /* 0x790 */
    u8 pad_7A0[0x30];
    f32 unk7D0[0x20]; /* 0x7D0 */
    u8 pad_850[0x4];
    f32 unk854; /* 0x854 */
    f32 unk858; /* 0x858 */
    f32 unk85C; /* 0x85C */
    f32 unk860; /* 0x860 */
    s32 unk864; /* 0x864 */
    f32 unk868; /* 0x868 */
    u8 *unk86C; /* 0x86C */
    s32 unk870; /* 0x870 */
    f32 unk874; /* 0x874 */
    f32 unk878; /* 0x878 */
    f32 unk87C; /* 0x87C */
    u8 pad_880[0x4];
    s16 unk884; /* 0x884 */
    s16 unk886; /* 0x886 */
    s16 unk888; /* 0x888 */
    s16 unk88A; /* 0x88A */
    u8 unk88C; /* 0x88C */
    u8 unk88D; /* 0x88D */
    u8 unk88E; /* 0x88E */
    u8 unk88F; /* 0x88F */
    u8 pad_890[0x4];
    s32 unk894; /* 0x894: frame counter shown as m:ss.hh on the HUD (FUN_L05_00266710) */
    s16 unk898; /* 0x898 */
    s16 unk89A; /* 0x89A: shown + 1 (capped at 3) on the HUD (FUN_L05_00266320) */
    s16 unk89C; /* 0x89C */
    s16 unk89E; /* 0x89E */
    f32 unk8A0; /* 0x8A0 */
    f32 unk8A4; /* 0x8A4 */
    s32 unk8A8; /* 0x8A8: count shown on the HUD (FUN_L05_00266710) */
    s16 unk8AC; /* 0x8AC */
    u8 pad_8AE[0x1];
    u8 unk8AF; /* 0x8AF */
    s16 unk8B0; /* 0x8B0 */
    s16 unk8B2; /* 0x8B2 */
    void *unk8B4; /* 0x8B4 */
    union { f32 f; s32 i; } unk8B8; /* 0x8B8: read as a float, zeroed as an int */
    s16 unk8BC; /* 0x8BC */
    s16 unk8BE; /* 0x8BE */
    s32 unk8C0; /* 0x8C0: 1..3 picks the HUD rank string (FUN_L05_00266320) */
    s32 unk8C4; /* 0x8C4 */
    u8 pad_8C8[0x4];
    s16 unk8CC; /* 0x8CC */
    u8 unk8CE; /* 0x8CE */
    u8 pad_8CF[0x1];
    Vec4 unk8D0; /* 0x8D0 */
    s32 unk8E0; /* 0x8E0 */
    f32 unk8E4; /* 0x8E4 */
    f32 unk8E8; /* 0x8E8 */
    f32 unk8EC; /* 0x8EC */
    s32 unk8F0; /* 0x8F0 */
    s32 unk8F4; /* 0x8F4 */
    s16 unk8F8; /* 0x8F8 */
    u8 pad_8FA[0x2];
    f32 unk8FC; /* 0x8FC */
    s16 unk900; /* 0x900 */
    s16 unk902; /* 0x902 */
    u8 pad_904[0x6];
    s16 unk90A; /* 0x90A */
    s16 unk90C; /* 0x90C */
    s16 unk90E; /* 0x90E */
    s32 unk910; /* 0x910 */
    s32 unk914; /* 0x914 */
    u8 pad_918[0x8];
    Vec4 unk920; /* 0x920 */
    f32 unk930; /* 0x930 */
    u8 pad_934[0xC];
    f32 unk940; /* 0x940 */
    f32 unk944; /* 0x944 */
    f32 unk948; /* 0x948 */
    f32 unk94C; /* 0x94C */
    f32 unk950; /* 0x950 */
    f32 unk954; /* 0x954 */
    u8 pad_958[0x8];
    f32 unk960; /* 0x960 */
    struct Moby *unk964; /* 0x964 */
    s32 unk968; /* 0x968 */
    f32 unk96C; /* 0x96C */
    f32 unk970; /* 0x970 */
    s32 unk974; /* 0x974 */
    u8 pad_978[0x4];
    f32 unk97C; /* 0x97C */
    f32 unk980; /* 0x980 */
    f32 unk984; /* 0x984 */
    s32 unk988; /* 0x988 */
    u8 pad_98C[0x4];
    struct Moby *unk990; /* 0x990 */
    struct Moby *unk994; /* 0x994 */
    f32 unk998; /* 0x998 */
    s16 unk99C; /* 0x99C */
    s16 unk99E; /* 0x99E */
    f32 unk9A0; /* 0x9A0 */
    f32 unk9A4; /* 0x9A4 */
    f32 unk9A8; /* 0x9A8 */
    f32 unk9AC; /* 0x9AC */
    f32 unk9B0; /* 0x9B0 */
    f32 unk9B4; /* 0x9B4 */
    f32 unk9B8; /* 0x9B8 */
    s16 unk9BC; /* 0x9BC */
    s16 unk9BE; /* 0x9BE */
    u8 pad_9C0[0x4];
    f32 unk9C4; /* 0x9C4 */
    f32 unk9C8; /* 0x9C8 */
    f32 unk9CC; /* 0x9CC */
    f32 unk9D0; /* 0x9D0: rail yaw (FUN_L01_002f6328) */
    f32 unk9D4; /* 0x9D4 */
    u8 pad_9D8[0x4];
    f32 unk9DC; /* 0x9DC: rail speed, eased toward the rail's speed */
    f32 unk9E0; /* 0x9E0: pull toward the rail, capped at the distance */
    f32 unk9E4; /* 0x9E4 */
    f32 unk9E8; /* 0x9E8 */
    u8 pad_9EC[0x64];
    u8 *unkA50; /* 0xA50 */
    struct Moby *unkA54; /* 0xA54 */
    s32 unkA58; /* 0xA58 */
    f32 unkA5C; /* 0xA5C */
    s32 unkA60; /* 0xA60 */
    s32 unkA64; /* 0xA64 */
    f32 unkA68; /* 0xA68 */
    f32 unkA6C; /* 0xA6C */
    f32 unkA70; /* 0xA70 */
    u8 pad_A74[0x8];
    s32 unkA7C; /* 0xA7C */
    s32 unkA80; /* 0xA80 */
    u8 *unkA84; /* 0xA84 */
    u8 *unkA88; /* 0xA88 */
    void *unkA8C; /* 0xA8C */
    f32 unkA90; /* 0xA90 */
    f32 unkA94; /* 0xA94 */
    s32 unkA98; /* 0xA98 */
    s32 unkA9C; /* 0xA9C */
    s32 unkAA0; /* 0xAA0 */
    s32 unkAA4; /* 0xAA4 */
    f32 unkAA8; /* 0xAA8 */
    u8 pad_AAC[0x8];
    s32 unkAB4; /* 0xAB4 */
    u8 pad_AB8[0x248];
    u8*unkD00; /* 0xD00 */
    u8*unkD04; /* 0xD04 */
    u8 *unkD08[2]; /* 0xD08: per item slot 0/1: moby from FUN_L00_0024f028 */
    u8 *unkD10; /* 0xD10 */
    s32 unkD14; /* 0xD14 */
    u8 pad_D18[0x2D8];
    struct HeroRandTimer rand_timer;/* 0xFF0 */
    u8 pad_FFC[0x14];
    s32 unk1010; /* 0x1010 */
    u8 pad_1014[0x7C];
    struct HeroItemSlot items[4]; /* 0x1090: item slots; slot 0 is the equipped gadget */
    u8 pad_11D0[0x110];
    s16 unk12E0; /* 0x12E0 */
    u8 unk12E2; /* 0x12E2 */
    u8 unk12E3; /* 0x12E3 */
    u8 base_condition; /* 0x12E4 */
    u8 selector_1; /* 0x12E5 */
    u8 selector_3; /* 0x12E6 */
    u8 unk12E7; /* 0x12E7 */
    u8 unk12E8; /* 0x12E8 */
    u8 unk12E9; /* 0x12E9 */
    u8 unk12EA; /* 0x12EA */
    u8 selector_11; /* 0x12EB */
    u8 selector_13; /* 0x12EC */
    u8 unk12ED; /* 0x12ED */
    u8 unk12EE; /* 0x12EE */
    u8 pad_12EF[0x301];
    struct Moby *ship_moby; /* 0x15F0: the ship the hero is flying (l17 FUN_L17_002ed018) */
    s16 ship_oclass; /* 0x15F4: its oclass, -1 when none */
    u8 ship_ammo; /* 0x15F6: shots left in the space levels; firing needs one and takes it (FUN_L11_003126f8) */
    u8 ship_ammo_max; /* 0x15F7: ammo pips the ship HUD draws, lit while below ship_ammo */
    u8 unk15F8; /* 0x15F8 */
    u8 unk15F9; /* 0x15F9 */
    u8 unk15FA; /* 0x15FA */
    u8 unk15FB; /* 0x15FB */
    f32 ship_hp; /* 0x15FC: ship health; l17 subtracts collision damage and explodes the ship below 0 */
    f32 ship_hp_max; /* 0x1600: full ship_hp; the HUD bar shows ship_hp over it */
    f32 unk1604; /* 0x1604 */
    s32 ship_hp_percent; /* 0x1608: ship_hp as a percentage for the HUD */
    s16 unk160C; /* 0x160C */
    u8 unk160E; /* 0x160E */
    u8 ship_flags; /* 0x160F: 2 = being steered back from the edge or height limit of the space arena (FUN_L11_00313f60) */
    u8 pad_1610[0x4];
    s32 unk1614; /* 0x1614 */
    u8 pad_1618[0x8];
    void *unk1620; /* 0x1620 */
    void *unk1624; /* 0x1624 */
    u8 pad_1628[0x8];
    s32 unk1630; /* 0x1630 */
    s16 unk1634; /* 0x1634 */
    s16 unk1636; /* 0x1636 */
    u8 pad_1638[0x8];
    Vec4 unk1640; /* 0x1640 */
    s32 unk1650; /* 0x1650 */
    u8 pad_1654[0xC];
    s32 unk1660; /* 0x1660 */
    u8 pad_1664[0xC];
    struct MobyTrail trail; /* 0x1670: trail of moby copies following hero.moby */
    u8 pad_17B0[0x350];
    Vec4 unk1B00[32]; /* 0x1B00: ring of 32 quads indexed by unk21B0 */
    u8 pad_1D00[0x20];
    f32 unk1D20; /* 0x1D20 */
    f32 unk1D24; /* 0x1D24 */
    u8 pad_1D28[0x238];
    u8 unk1F60[0x40]; /* 0x1F60: 0x40-byte buffer cleared by FUN_L00_002b58d8 */
    u8 unk1FA0[0x40]; /* 0x1FA0: 0x40-byte buffer cleared by FUN_L00_002b58d8 */
    u8 *unk1FE0; /* 0x1FE0: moby set by FUN_L00_002b58d8 */
    u8 pad_1FE4[0x11];
    u8 unk1FF5; /* 0x1FF5 */
    u8 ammo_used; /* 0x1FF6 */
    u8 ammo_capacity; /* 0x1FF7 */
    u8 pad_1FF8[0x48];
    struct Moby *unk2040; /* 0x2040: nearest oclass 0x25D moby (FUN_L00_002d2ee8) */
    f32 unk2044; /* 0x2044: distance to unk2040; 100000 when none */
    s32 unk2048; /* 0x2048 */
    u8 pad_204C[0x34];
    struct Moby *moby; /* 0x2080: the hero's moby */
    struct HeroState state; /* 0x2084 */
    u8 unk20A4; /* 0x20A4 */
    u8 unk20A5; /* 0x20A5 */
    u8 unk20A6; /* 0x20A6: forces slot 0 to item 8 */
    u8 unk20A7; /* 0x20A7 */
    u8 unk20A8; /* 0x20A8 */
    u8 unk20A9; /* 0x20A9 */
    u8 unk20AA; /* 0x20AA */
    u8 unk20AB; /* 0x20AB */
    u8 unk20AC; /* 0x20AC */
    u8 unk20AD; /* 0x20AD */
    u8 unk20AE; /* 0x20AE */
    u8 unk20AF; /* 0x20AF */
    u8 pad_20B0[0x1];
    u8 unk20B1; /* 0x20B1 */
    u8 unk20B2; /* 0x20B2 */
    u8 unk20B3; /* 0x20B3 */
    u8 unk20B4; /* 0x20B4 */
    u8 pad_20B5[0x3];
    s32 pending_item[7]; /* 0x20B8: per slot: item to switch to */
    s32 selected_item[7]; /* 0x20D4: per slot: item after a switch */
    s32 saved_item[7]; /* 0x20F0: per slot: item kept while another is forced in */
    s32 restore_item[7]; /* 0x210C: per slot: 1 puts saved_item back */
    u8 pad_2128[0x88];
    s32 unk21B0; /* 0x21B0: unk1B00 ring index */
    s32 unk21B4; /* 0x21B4: unk1B00 ring count */
    u8 pad_21B8[0x60];
    s32 unk2218; /* 0x2218 */
    u8 pad_221C[0x4];
    s32 unk2220; /* 0x2220 */
    s32 unk2224; /* 0x2224 */
    s32 unk2228; /* 0x2228 */
    s32 unk222C; /* 0x222C */
    s32 unk2230; /* 0x2230 */
    s32 unk2234; /* 0x2234 */
    u8 pad_2238[0x38];
    s32 unk2270; /* 0x2270 */
    s32 unk2274; /* 0x2274 */
    u8 pad_2278[0x8];
    struct Moby *unk2280; /* 0x2280 */
    s32 unk2284; /* 0x2284 */
    f32 unk2288; /* 0x2288 */
    f32 unk228C; /* 0x228C */
    f32 unk2290; /* 0x2290 */
    s32 unk2294; /* 0x2294 */
    s32 unk2298; /* 0x2298 */
    f32 unk229C; /* 0x229C */
    s32 unk22A0; /* 0x22A0 */
    f32 unk22A4; /* 0x22A4 */
    struct HeroHealth health; /* 0x22A8 */
    s32 unk22B4; /* 0x22B4 */
    f32 unk22B8; /* 0x22B8: distance to the nearest carrying path this frame (FUN_L01_002f3120 keeps the minimum) */
    u8 pad_22BC[0x8];
    s32 unk22C4; /* 0x22C4 */
    s16 unk22C8; /* 0x22C8 */
    u8 unk22CA; /* 0x22CA */
    u8 unk22CB; /* 0x22CB */
    s16 unk22CC; /* 0x22CC */
    s16 unk22CE; /* 0x22CE */
    u8 pad_22D0[0x2];
    s16 unk22D2; /* 0x22D2 */
    s16 unk22D4; /* 0x22D4: countdown set on pad bit 0x10 press */
    s16 unk22D6; /* 0x22D6: countdown; nonzero with unk22D4 switches pending_item[0] */
    s16 unk22D8; /* 0x22D8 */
    s16 unk22DA; /* 0x22DA */
    s16 unk22DC; /* 0x22DC */
    s16 unk22DE; /* 0x22DE */
    s16 unk22E0; /* 0x22E0 */
    u8 pad_22E2[0x12];
    s32 unk22F4; /* 0x22F4 */
    s32 unk22F8; /* 0x22F8 */
    s16 unk22FC; /* 0x22FC */
};
extern struct Hero D_0013F450;
extern char D_L03_00166F40[];
typedef int OvlQuad __attribute__((mode(TI)));
typedef float MineVec[4] __attribute__((aligned(16)));
typedef struct {
    OvlQuad q[5];
} MineBlast;
typedef struct {
    u8 pad0[0x60]; /* 0x00: fall record (FUN_L00_0025c698) */
    s32 unk60;
    s32 timer; /* 0x64: arming delay */
    struct Moby *target; /* 0x68: moby it is stuck to or homing on */
    s32 age; /* 0x6C: frames alive */
} MineVars;
typedef struct {
    u8 pad0[0x160];
    f32 shake; /* 0x160 */
    u8 pad164[4];
    s32 shake_frames; /* 0x168 */
} MineCamera;
extern MineBlast D_L03_001E35A0;
extern struct Moby * D_L03_00178080[];
extern MineCamera D_L03_00166E00;
extern char D_L03_001B0BB0[];
extern float D_0015EE60 MACRO_ADDR;
extern int func_L00_0025D6F0(struct Moby *, void *);
extern s32 func_001F9850(s32);
extern s32 func_001F9908_CD270(s32 *) __asm__("func_001F9908");
extern void func_00213DE0(struct Moby *, int, int, int);
extern void func_0020D678_CD270(struct Moby *) __asm__("func_0020D678");
extern void func_001F9BF0(void *, void *, void *);
extern void func_001F9BD8(void *, void *, void *);
extern f32 func_001F9CB8(void *);
extern void func_L00_001FF4B0(void *, void *, f32);
extern f32 func_001F9D48(void *, void *);
extern f32 func_001F9B88(f32);
extern void func_0022ED80_CD270(int, int, struct Moby *) __asm__("func_0022ED80");
extern int func_L00_001F2BE8(void *, int, struct Moby *, void *, f32);
extern void func_L00_0025BA50(struct Moby *, void *, void *, int, int, int, int, int, f32, f32, f32);
extern s32 func_001FA898(f32);
extern s32 func_002140B0(s32);
extern f32 func_002140F8(f32, f32);
extern f32 func_00214158(void);
extern f32 func_001F9F90(f32);
extern f32 func_001F9FA8(f32);
extern s32 func_L00_00258BC8(s32, s32);
extern int func_L00_00237B70_CD270(int, int, f32) __asm__("func_L00_00237B70");
extern void func_00215C00(void *, f32, f32, f32);
extern void func_L00_0026CD70(void *, void *, int, int, f32, int, int);
extern void func_L00_002D4CE8(void *, void *, int, int);
extern void func_L00_00260878(struct Moby *, void *);

/* l03 mine update: falls until it lands, sticks to or homes on its target, arms, and explodes on contact (debris, camera shake, blast) or shrinks away when old.
   Adapted from Lombyte (MIT) for PAL by OpenRAC's tools/port.py: src/overlays/l03/gameplay/entities/002c9eb8.c, FUN_L03_002cbea8. */
void func_L03_002CD270(struct Moby *m) {
    MineBlast blast = D_L03_001E35A0;
    MineVec tmp;
    MineVars *v = (MineVars *)m->pvars;
    struct Moby *t;
    float dist;
    int n;
    int i;
    int k;

    func_L03_002CDBF0((unsigned char *)m);
    v->unk60 = 0;
    v->age++;
    switch (m->state) {
    case 0:
        break;
    case 1:
        if (func_L00_0025D6F0(m, v) & 1) {
            m->state = 3;
            if (m->prev_seq != 1) {
                func_00213DE0(m, 1, 0, scale_ticks(10));
            }
            v->timer = scale_ticks(60);
        } else if (m->pos.z < 5.0f) {
            func_0020D678_CD270(m);
            return;
        }
        break;
    case 2:
        FastVecSub(tmp, &v->target->pos, &m->pos);
        if (FastVecLength(tmp) < 0.25f) {
            func_0020D678_CD270(m);
            return;
        }
        func_L00_001FF4B0(tmp, tmp, D_0015EE6C * 14.0f);
        tmp[2] += D_0015EE6C * 4.0f;
        FastVecAdd(&m->pos, &m->pos, tmp);
        break;
    case 3:
        func_001F9908_CD270(&v->timer);
        t = v->target;
        if (t != 0 && t->state != 0xFE && t->state != 0xFD && func_001F9D48(&m->pos, &t->pos) < 3.0f && v->timer == 0) {
            m->state = 2;
            func_0022ED80_CD270(2, 0, m);
        }
        if (scale_ticks(3600) < v->age &&
            (v->target == 0 || v->target->state == 0xFE || v->target->state == 0xFD || scale_ticks(5400) < v->age)) {
            m->state = 5;
        }
        if (func_001F9D48(&D_0013F450.moby->pos, &m->pos) < 0.5f && FastAbsF(m->pos.z - D_0013F450.motion.pos.f[2]) < 0.25f) {
            m->state = 4;
            break;
        }
        n = coll_sphere_mobys(&m->pos, 0x10, m, 0, 1.0f);
        for (k = 0; k < n; k++) {
            struct Moby *o = D_L03_00178080[k];

            if ((o->flags & 0x1000) && (o != v->target || v->timer == 0)) {
                m->state = 4;
                break;
            }
        }
        break;
    case 4: {
        int cnt;

        dist = func_001F9D48(&m->pos, D_L03_00166F40);
        n = coll_sphere_mobys(&m->pos, 0x10, m, 0, 2.0f);
        *(OvlQuad *)tmp = *(OvlQuad *)&m->pos;
        func_L00_0025BA50(m, tmp, D_L03_00178080, n, 0, 0x810001, 4, 1, 3.0f, 0.25f, 1.5f);
        cnt = truncate_float_to_s32(dist * 15.0f);
        for (i = 0; i < cnt; i++) {
            int kind = random_integer_below(4);

            *(Vec4f *)tmp = (Vec4f){D_0015EE6C * 14.0f, D_0015EE6C * 22.0f, D_0015EE6C * 12.0f, 0.0f};
            {
                MineVec dir;
                MineVec r;
                float rr;
                float ang;

                *(OvlQuad *)r = 0;
                r[0] = random_float_between(D_0015EE6C * -0.5f, D_0015EE6C * 0.5f);
                r[1] = random_float_between(D_0015EE6C * -0.5f, D_0015EE6C * 0.5f);
                r[2] = random_float_between(D_0015EE6C * 4.0f, tmp[kind]);
                *(OvlQuad *)dir = *(OvlQuad *)r;
                rr = random_float_between(0.0f, kind == 1 ? 0.5f : 0.25f);
                ang = random_angle_radians();
                r[0] = FastCos(ang) * rr;
                r[1] = FastSin(ang) * rr;
                r[2] = 0.0f;
                FastVecAdd(r, r, &m->pos);
                r[2] -= rr * FastCos(0.785398f);
                dir[2] -= rr * D_0015EE6C * 8.0f;
                switch (kind) {
                case 0:
                    func_L00_0026CD70(r, dir, 0x1F101820, 0x101010, random_float_between(200000.0f, 300000.0f),
                                rand_range(scale_ticks(0xB4), scale_ticks(0xF0)), 0);
                    break;
                case 1:
                    func_L00_0026CD70(r, dir, 0x3F081020, 0x0F081020, random_float_between(50000.0f, 100000.0f), scale_ticks(0xB4), 1);
                    break;
                case 2:
                    func_L00_0026CD70(r, dir, random_integer_below(100) < 0x28 ? 0x5FF8F8F8 : 0x2F486078, 0x0F000020, 150000.0f,
                                rand_range(scale_ticks(0x1E), scale_ticks(0x2D)), 2);
                    break;
                case 3: {
                    int c1 = func_L00_00237B70_CD270(0x7F000000, 0x7F182030, random_float_between(0.25f, 1.0f));
                    int c2 = func_L00_00237B70_CD270(0, 0x5F5F5F, random_float_between(0.5f, 1.0f));

                    func_00215C00(dir, random_float_between(0.0f, 1.0f) * D_0015EE6C, ang, random_angle_radians());
                    func_L00_0026CD70(r, dir, c1, c2, random_float_between(200000.0f, 300000.0f),
                                rand_range(scale_ticks(0xF0), scale_ticks(0x12C)), 3);
                    break;
                }
                }
            }
        }
        func_0022ED80_CD270(0, 0, m);
        D_L03_00166E00.shake = dist < 20.0f ? 0.4f - dist * 0.0175f : 0.050000012f;
        D_L03_00166E00.shake_frames = scale_ticks(0x19);
        func_L00_002D4CE8(&blast, &m->pos, 0, 0);
        func_L00_00260878(m, D_L03_001B0BB0);
        func_0020D678_CD270(m);
        return;
    }
    case 5:
        m->scale *= D_0015EE60 * -0.074f + 1.0f;
        if (m->scale < m->pclass->scale * 0.01f) {
            func_L00_00260878(m, D_L03_001B0BB0);
            func_0020D678_CD270(m);
        }
        break;
    }
}
extern char *func_L00_0025B478(void *, int, int);

void func_L03_002CDBF0(unsigned char *arg) {
    char *item = func_L00_0025B478(arg, 0x130000, 0);
    if (item != 0) {
        char *other = *(char **)(item + 0x20);
        if (other != 0 && *(short *)(other + 0xA6) != *(short *)(arg + 0xA6)) {
            arg[0x20] = 4;
        }
    }
    arg[0xA4] = 0xFF;
}
extern char *func_0020D348(int);
extern float D_0015EE64 MACRO_ADDR;
extern float func_001F9CE8(void *);
extern float func_L00_001FF860(float, float);
extern void func_L00_0025D5B0(void *, void *, int, int, int, float);

/* Spawns a projectile moby (class 0x273) at pos, heading along dir, owned by parent p.
   Adapted from Lombyte (MIT) for PAL by OpenRAC's tools/port.py: src/overlays/l03/gameplay/entities/002c9eb8.c, FUN_L03_002cc888. */
char *func_L03_002CDC50(char *p, void *pos, float *dir) {
    char *m = CreateMoby(0x273);
    char *v;
    float s;

    if (m == 0) {
        return 0;
    }
    *(unsigned short *)(m + 0x32) = *(unsigned short *)(p + 0x32);
    m[0x30] = p[0x32];
    m[0x31] = 1;
    *(long *)(m + 0x38) = *(long *)(p + 0x38);
    qcopy(m + 0x10, pos);
    v = *(char **)(m + 0x78);
    s = D_0015EE64;
    *(float *)(v + 0x10) = s * 0.008f;
    *(float *)(v + 0x14) = s * 0.0005f;
    *(float *)(v + 0x18) = func_001F9CE8(dir);
    *(float *)(v + 0x1C) = dir[2];
    *(int *)(v + 0x20) = 0x400;
    *(float *)(v + 0x28) = 1.0f;
    *(float *)(v + 0x30) = 0.75f;
    *(float *)(v + 0x34) = 0.5f;
    *(float *)(v + 0x38) = 0.65f;
    *(float *)(v + 0x48) = 0.2f;
    *(float *)(v + 0x4C) = 0.01f;
    v[0x3D] = 0;
    *(int *)(v + 0x24) = 1;
    func_L00_0025D5B0(m, v, 0, 1, 0, func_L00_001FF860(dir[0], dir[1]));
    *(char **)(v + 0x68) = p;
    *(int *)(v + 0x6C) = 0;
    m[0x20] = 1;
    return m;
}
INCLUDE_ASM("asm/overlays", func_L03_002D44A0);
extern void func_00215F80(int, int);

void func_L03_002D44C8(void *arg, int mode) {
    if (mode == 1) {
        try_set_help_message(8, 0xBC9);
    } else {
        try_set_help_message(8, 0xBC9);
    }
}
INCLUDE_ASM("asm/overlays", func_L03_002D4560);
extern float D_0015EE6C MACRO_ADDR;
extern char D_0013E633[];
extern void func_001F9BF0(void *, void *, void *);
extern void func_001F9BD8(void *, void *, void *);
extern void func_L00_001FF4B0(void *, void *, float);
extern float func_L00_001FF860(float, float);
extern char *D_L03_001B08B0[];
extern float D_0015EE70 MACRO_ADDR;
extern float D_L03_00161B88 SDATA(D_L03_00161B88);
extern float D_L03_00161B8C SDATA(D_L03_00161B8C);
extern float D_L03_00161B90 SDATA(D_L03_00161B90);
extern float D_L03_00161B94 SDATA(D_L03_00161B94);
extern float D_L03_00161B98 SDATA(D_L03_00161B98);
extern float D_L03_00161B9C SDATA(D_L03_00161B9C);
extern float func_001F9CB8(void *);
extern float func_001F9D10(void *, void *);
extern float func_00214D88(float *, float *, float, float, float, float);
extern float func_001F9CE8(void *);
extern float func_L00_0025CE58(float *, float, float *, float, float, float);
extern int func_L00_0028EB98(void *, int);
extern int func_L00_0028EF68(int, int, int, int);
extern void func_L00_0028EBF0(int);

typedef struct PathFollower4CE0 {
    char pad0[0x60]; float speed; int waypoint;
    float yawVelocity, pitchVelocity, rollVelocity;
} PathFollower4CE0;

/* Moves along a waypoint path and eases the orientation toward its direction. */
int func_L03_002D4CE0(char *moby, int pathIndex, int *sound) {
    char **entry = &D_L03_001B08B0[pathIndex];
    PathFollower4CE0 *data = *(PathFollower4CE0 **)(moby + 0x78);
    float target[4];
    float direction[4];
    float zero = 0.0f;
    float step, distance, accel, pitch;
    int finished = 0;
    char *position;
    qcopy(target, *entry + (data->waypoint * 16 + 0x10));
    position = moby + 0x10;
    FastVecSub(direction, target, position);
    distance = FastVecLength(direction);
    step = D_L03_00161B88 * D_0015EE6C;
    if (distance < step + step) {
        data->waypoint++;
        finished = data->waypoint == *(int *)*entry;
    }
    distance = FastVecDist(position, *entry + (*(int *)*entry << 4));
    accel = D_L03_00161B8C * D_0015EE70;
    func_00214D88(&zero, &data->speed, distance, accel, accel, D_L03_00161B88 * D_0015EE6C);
    func_L00_001FF4B0(direction, direction, data->speed);
    FastVecAdd(position, direction, position);
    pitch = -func_L00_001FF860(func_001F9CE8(direction), direction[2]);
    if (pitch > 0.261799395f) pitch = 0.261799395f;
    else if (pitch < -0.261799395f) pitch = -0.261799395f;
    func_L00_0025CE58((float *)(moby + 0x44), pitch, &data->pitchVelocity,
        D_L03_00161B90 * 0.017453292f * D_0015EE70,
        D_L03_00161B90 * 0.017453292f * D_0015EE70,
        D_0015EE6C * 12.566371f);
    func_L00_0025CE58((float *)(moby + 0x48),
        func_L00_001FF860(target[0] - *(float *)(moby + 0x10), target[1] - *(float *)(moby + 0x14)), &data->yawVelocity,
        D_L03_00161B94 * 0.017453292f * D_0015EE70,
        D_L03_00161B94 * 0.017453292f * D_0015EE70,
        D_0015EE6C * 12.566371f);
    func_L00_0025CE58((float *)(moby + 0x40),
        data->yawVelocity * data->speed * D_L03_00161B9C, &data->rollVelocity,
        D_L03_00161B98 * 0.017453292f * D_0015EE70,
        D_L03_00161B98 * 0.017453292f * D_0015EE70,
        D_0015EE6C * 12.566371f);
    if (finished == 0) {
        if (func_L00_0028EB98(moby, *sound) == 0)
            *sound = func_L00_0028EF68(0, 4, (int)moby, 0x330);
    } else {
        if (*sound != -1) {
            char *e = D_0013E633 + 0x1D + *sound * 0x70;
            if (*(char **)(e + 0x88) == moby && ((unsigned char *)e)[0x74] != 0)
                func_L00_0028EBF0(*sound);
        }
        *sound = -1;
    }
    return finished;
}
extern void func_L00_00263B78(float, float, char *, float *, float *);
extern void func_L00_00263BF8(void *, char *, char *, float, float, float);
extern float D_0015EE6C MACRO_ADDR;
extern short D_L03_00161B70_g __asm__("D_L03_00161B70");
extern short D_L03_00161B74_g __asm__("D_L03_00161B74");
extern short D_L03_00161B78_g __asm__("D_L03_00161B78");
extern short D_L03_00161B7C_g __asm__("D_L03_00161B7C");
extern short D_L03_00161B80_g __asm__("D_L03_00161B80");

/* Sets two speed pairs on a moby's data from level constants scaled by degrees-to-radians and the frame scale. */
void func_L03_002D5008(char *m) {
    char *d = *(char **)(m + 0x78);
    func_L00_00263B78(*(float *)&D_L03_00161B70_g, *(float *)&D_L03_00161B74_g * 0.0174532925f * D_0015EE6C, m, (float *)(d + 0xEC), (float *)(d + 0xE8));
    func_L00_00263BF8(m, d + 0xF0, d + 0xF4, *(float *)&D_L03_00161B78_g, *(float *)&D_L03_00161B7C_g * 0.0174532925f * D_0015EE6C, *(float *)&D_L03_00161B80_g * 0.0174532925f * D_0015EE6C);
}
INCLUDE_ASM("asm/overlays", func_L03_002D5220);
extern struct Moby *func_0020D348_m(int) __asm__("func_0020D348");
extern float func_L00_001FF860(float, float);
extern int func_001F9850(int);
extern int func_L00_001EFFF0(void *, void *, int, void *, void *);
extern void func_L00_00251E30(void *);
extern char D_L03_00173FE0[];

typedef int u128 __attribute__((mode(TI)));

// Spawns a moby of class 0x341 at a position, initialises its data and registers it.
char *func_L03_002D5650(char *a, char *pos, char *parent, int n, float f0, float f1, float f2) {
    char *m = (char *)func_0020D348_m(0x341);
    char *d;
    if (m != 0) {
        float v[4];
        *(unsigned char *)(m + 0x30) = 0xFF;
        *(short *)(m + 0x32) = 0x7E;
        d = *(char **)(m + 0x78);
        m[0x31] = 1;
        m[0x20] = 1;
        qcopy(m + 0x10, pos);
        qcopy(d, a);
        *(float *)(m + 0x48) = func_L00_001FF860(*(float *)d, *(float *)(d + 4));
        *(int *)(d + 0x14) = scale_ticks(n);
        *(float *)(d + 0x18) = f2;
        *(float *)(d + 0x1C) = f0;
        *(float *)(d + 0x24) = f1;
        *(char **)(d + 0x10) = parent;
        *(int *)(d + 0x28) = 0;
        *(u128 *)v = *(u128 *)(parent + 0x10);
        v[2] = *(float *)(pos + 8);
        if (func_L00_001EFFF0(v, pos, 2, parent, 0) != 0) {
            *(int *)(d + 0x14) = 0;
            *(u128 *)(m + 0x10) = *(u128 *)D_L03_00173FE0;
            *(int *)(d + 0x24) = 0;
        }
        func_L00_00251E30(m);
    }
    return m;
}
INCLUDE_ASM("asm/overlays", func_L03_002D5790);
extern int D_L03_0015F6A8 MACRO_ADDR;
extern unsigned char D_0015EEB0[] MACRO_ADDR;
struct G_002DBAD8 {
    char pad0[0x30];
    int a;
    int b;
    char pad1[0xC];
    short n;
    char pad2[0x132];
    char *objs[1];
};
extern struct G_002DBAD8 D_L03_0016C9E0;
extern float D_L03_0015F680 MACRO_ADDR;
extern unsigned char D_L03_0017C5C0[];
extern void func_0020D960(char *, int, void *);
extern short D_L03_00161C34;

/* triggers objects matching the moby's class, with per-segment settings */
void func_L03_002DBAD8(char *moby) {
    int i;
    if (D_L03_0015F6A8 == 2 && gCheats[0]) {
        if (D_L03_0016C9E0.a == 2 && D_L03_0016C9E0.b >= 0x1EA && D_L03_0016C9E0.b < 0x266) {
            D_L03_0015F680 = -0.2f;
        }
        if (D_L03_0016C9E0.a == 2 && D_L03_0016C9E0.b >= 0x2EE && D_L03_0016C9E0.b < 0x321) {
            D_L03_0015F680 = 0.2f;
        }
        for (i = 0; i < D_L03_0016C9E0.n; i++) {
            char *o = D_L03_0016C9E0.objs[i];
            if (*(short *)(o + 0xA6) == *(short *)(moby + 0xA6)) {
                if (D_L03_0017C5C0[1] == 0) {
                    float f;
                    AttachManipulator(o, 0, D_L03_0017C5C0);
                    f = *(float *)&D_L03_00161C34;
                    *(float *)(D_L03_0017C5C0 + 0x20) = f;
                    *(float *)(D_L03_0017C5C0 + 0x24) = f;
                    *(float *)(D_L03_0017C5C0 + 0x28) = f;
                }
            }
        }
    }
}
INCLUDE_ASM("asm/overlays", func_L03_002DBC38);
INCLUDE_ASM("asm/overlays", func_L03_002DC3E8);
INCLUDE_ASM("asm/overlays", func_L03_002DC560);
INCLUDE_ASM("asm/overlays", func_L03_002DC648);
INCLUDE_ASM("asm/overlays", func_L03_002DC920);
INCLUDE_ASM("asm/overlays", func_L03_002DD158);
INCLUDE_ASM("asm/overlays", func_L03_002DDE38);
INCLUDE_ASM("asm/overlays", func_L03_002DDE9C);
INCLUDE_ASM("asm/overlays", func_L03_002DDEF8);
int func_L03_002DDF10(unsigned char *moby, char *data) {
    if (moby[0x20] && *(int *)(data + 0x7C) == 1) {
        return 1;
    }
    return 0;
}
extern int func_001FFB38(int, int, int, int, int, int, int);
extern void func_L00_002367A8(int, int);
extern void func_L00_00237B20(void);
extern void func_L00_00237B70(void);
extern void func_L00_00237B90(void);

/* Shows a help message for the mode, then keeps a hud queue entry alive. */
void func_L03_002DDF90(char *m, int mode) {
    char *d = *(char **)(m + 0x78);
    int h;
    switch (mode) {
    case 1:
        try_set_help_message(8, 0xBCE);
        break;
    case 2:
        try_set_help_message(8, 0xBCF);
        break;
    case 3:
        try_set_help_message(8, 0xBCB);
        break;
    case 4:
        try_set_help_message(8, 0xBCD);
        break;
    default:
        try_set_help_message(8, -1);
        break;
    }
    h = *(int *)(d + 0xA4);
    if (h == -1) {
        *(int *)(d + 0xA4) = queue_animation_update(0xC, 0, (int)func_L00_00237B20, (int)DefaultVtbl_DeleteMoby, (int)func_L00_00237B90, 0, 0);
    } else {
        func_L00_002367A8(h, 0xA);
    }
}
INCLUDE_ASM("asm/overlays", func_L03_002DE088);
extern short D_L03_00161C58;
extern short D_L03_00161C5C;
extern short D_L03_00161C60;
extern short D_L03_00161C64;
extern short D_L03_00161C68;
extern void func_L00_00263B78(float x, float y, char *a, float *p, float *q);
/* sets two aim angles on a moby from level constants scaled by degrees-to-radians */
void func_L03_002DE4B8(char *moby) {
    char *data = *(char **)(moby + 0x78);
    func_L00_00263B78(*(float *)&D_L03_00161C58, *(float *)&D_L03_00161C5C * 0.017453292f * D_0015EE6C, moby, (float *)(data + 0xAC), (float *)(data + 0xA8));
    func_L00_00263BF8((float *)moby, (float *)(data + 0xB0), (float *)(data + 0xB4), *(float *)&D_L03_00161C60, *(float *)&D_L03_00161C64 * 0.017453292f * D_0015EE6C, *(float *)&D_L03_00161C68 * 0.017453292f * D_0015EE6C);
}
typedef struct Sub_2E08E8 {
    char pad0[0x46];
    short f46;
} Sub_2E08E8;

typedef struct Node_2E08E8 {
    char pad0[0x10];
    float pos[4];
    char pad20[4];
    Sub_2E08E8 *f24;
    struct Node_2E08E8 *next;
} Node_2E08E8;

typedef struct Data_2E08E8 {
    int f0;
    int f4;
    int f8;
    int fC;
    int f10;
    int f14;
    int f18;
    int f1C;
    int f20;
    int f24;
    int f28;
    int f2C;
    int f30;
    int f34;
    int f38;
    int f3C;
    int f40;
    int f44;
    int f48;
    int f4C;
    int f50;
    int f54;
    int f58;
    int f5C;
    int f60;
    int f64;
    int f68;
    int f6C;
    int f70;
    int f74;
    int f78;
    int f7C;
} Data_2E08E8;

typedef struct Moby_2E08E8 {
    char pad0[0x10];
    float pos[4];
    unsigned char state;
    char pad21[0xF];
    unsigned char f30;
    char pad31[0x47];
    Data_2E08E8 *data;
} Moby_2E08E8;

typedef struct Hero_2E08E8 {
    char pad0[0x988];
    int f988;
    char pad98C[0x72C];
    int f10B8;
    char pad10BC[0xFC8];
    int f2084;
    char pad2088[4];
    unsigned int f208C;
} Hero_2E08E8;

typedef struct Help_2E08E8 {
    unsigned short count;
    unsigned short time;
    unsigned int mask;
} Help_2E08E8;

typedef struct Entry_2E08E8 {
    int pad0;
    int pad4;
    int active;
    char rest[0x40];
} Entry_2E08E8;

extern void func_001F9908(int *arg0);
extern int func_00215570(void *, int);
extern int func_L00_00203F20(int a, int b);
extern float func_001F9D48(void *, void *);
extern int func_L00_00234718(int);
extern int func_0022EE28(int, int, int);
extern void func_L00_00264DB8(int, int);
extern Help_2E08E8 D_00141948_2E08E8[] __asm__("D_00141948");
extern Help_2E08E8 D_00141A68_2E08E8[] __asm__("D_00141A68");
extern unsigned char D_0013D355[];
extern unsigned char D_0013D50F[];
extern unsigned char D_0013D5CA[];
extern unsigned char D_0013D5EB[];
extern int D_0015EFA4 MACRO_ADDR;
extern int D_0015EE84 MACRO_ADDR;
extern int D_L03_00179590[] NOT_SDA;
extern Node_2E08E8 *D_L03_00160064_2E08E8 __asm__("D_L03_00160064") MACRO_ADDR;
extern int D_L03_0015F76C MACRO_ADDR;
extern int D_L03_0015F768 MACRO_ADDR;
extern int D_L03_0015F6A8 MACRO_ADDR;
extern Entry_2E08E8 D_L03_00179C40[];

/* UpdateMoby_1342: tutorial hint and statistic triggers around the player on Kerwan. */
void func_L03_002E08E8(Moby_2E08E8 *moby) {
    Data_2E08E8 *data = moby->data;

    func_001F9908(&data->f58);
    switch (moby->state) {
    case 0:
        data->f50 = 0;
        data->f54 = 0;
        moby->f30 = 0xFF;
        moby->state = 1;
        break;
    case 1:
        if (is_point_inside_clip_volume(D_0013E633 + 0xE9D, data->f78) != 0
            && (((Hero_2E08E8 *)(D_0013E633 + 0xE1D))->f208C < 2 || ((Hero_2E08E8 *)(D_0013E633 + 0xE1D))->f208C == 9)) {
            unsigned char *g = D_0013D355 + 0x13B;
            g[0x1A] = 1;
        }

        {
            unsigned char *g = D_0013D355 + 0x13B;
            if (g[0x1A] == 0) {
                if (is_point_inside_clip_volume(D_0013E633 + 0xE9D, data->f0) != 0
                    && (((Hero_2E08E8 *)(D_0013E633 + 0xE1D))->f208C < 2 || ((Hero_2E08E8 *)(D_0013E633 + 0xE1D))->f208C == 9)
                    && D_L03_00179590[0] == 0 && D_L03_00179590[9] == -1) {
                    Help_2E08E8 *b = D_00141A68_2E08E8;
                    if (!(b[0x14].mask & 0x80000000)) {
                        Help_Request(0xBB8, 0x14);
                    }
                }
                if (is_point_inside_clip_volume(D_0013E633 + 0xE9D, data->fC) != 0
                    && (((Hero_2E08E8 *)(D_0013E633 + 0xE1D))->f208C < 2 || ((Hero_2E08E8 *)(D_0013E633 + 0xE1D))->f208C == 9)
                    && D_L03_00179590[0] == 0 && D_L03_00179590[9] == -1) {
                    Help_2E08E8 *b = D_00141A68_2E08E8;
                    if (!(b[0x15].mask & 0x80000000)) {
                        Help_Request(0xBB9, 0x15);
                    }
                }
                if (is_point_inside_clip_volume(D_0013E633 + 0xE9D, data->f18) != 0
                    && (((Hero_2E08E8 *)(D_0013E633 + 0xE1D))->f208C < 2 || ((Hero_2E08E8 *)(D_0013E633 + 0xE1D))->f208C == 9)
                    && D_L03_00179590[0] == 0 && D_L03_00179590[9] == -1) {
                    Help_2E08E8 *b = D_00141A68_2E08E8;
                    if (!(b[0x17].mask & 0x80000000)) {
                        Help_Request(0xBBB, 0x17);
                    }
                }
            }
        }

        if (is_point_inside_clip_volume(D_0013E633 + 0xE9D, data->f30) != 0) {
            Help_2E08E8 *h = D_00141948_2E08E8;
            if (h[3].count == 0
                && (((Hero_2E08E8 *)(D_0013E633 + 0xE1D))->f208C < 2 || ((Hero_2E08E8 *)(D_0013E633 + 0xE1D))->f208C == 9)) {
                int n;
                h[3].count++;
                n = scale_ticks(D_0015EFA4) / 600;
                if (h[3].time < n) {
                    h[3].time = scale_ticks(D_0015EFA4) / 600;
                }
                h[3].mask = h[3].mask | (1 << D_0015EE84) | 0x80000000;
            }
        }

        if (is_point_inside_clip_volume(D_0013E633 + 0xE9D, data->f24) != 0 && D_00141948_2E08E8[3].count == 0
            && ((Hero_2E08E8 *)(D_0013E633 + 0xE1D))->f208C >= 2 && ((Hero_2E08E8 *)(D_0013E633 + 0xE1D))->f208C != 9
            && data->f58 == 0) {
            data->f50++;
            data->f58 = scale_ticks(0x3C);
        } else if (data->f58 != 0) {
            if (((Hero_2E08E8 *)(D_0013E633 + 0xE1D))->f208C < 2 || ((Hero_2E08E8 *)(D_0013E633 + 0xE1D))->f208C == 9) {
                data->f58 = 0;
            }
        }

        if (is_point_inside_clip_volume(D_0013E633 + 0xE9D, data->f24) != 0 && D_00141948_2E08E8[3].count == 0
            && (((Hero_2E08E8 *)(D_0013E633 + 0xE1D))->f208C < 2 || ((Hero_2E08E8 *)(D_0013E633 + 0xE1D))->f208C == 9)
            && data->f50 % 6 == 0 && data->f50 != 0
            && D_L03_00179590[0] == 0 && D_L03_00179590[9] == -1) {
            Help_2E08E8 *b = D_00141A68_2E08E8;
            if (b[0x16].count == 0) {
                Help_Request(0xBBA, 0x16);
            }
        }

        if (is_point_inside_clip_volume(D_0013E633 + 0xE9D, data->f28) != 0
            && (((Hero_2E08E8 *)(D_0013E633 + 0xE1D))->f208C < 2 || ((Hero_2E08E8 *)(D_0013E633 + 0xE1D))->f208C == 9)
            && D_L03_00179590[0] == 0 && D_L03_00179590[9] == -1) {
            Help_2E08E8 *b = D_00141A68_2E08E8;
            if (b[0x18].count == 0) {
                int t = scale_ticks(D_0015EFA4) - D_00141948_2E08E8[9].time * 600;
                if (scale_ticks(0x34BC0) < t) {
                    Help_Request(0xBBC, 0x18);
                }
            }
        }

        {
            Node_2E08E8 *m;
            int count = 0;
            for (m = D_L03_00160064_2E08E8; m != 0; m = m->next) {
                if (m->f24 != 0 && m->f24->f46 == 5
                    && func_001F9D48(m->pos, D_0013E633 + 0xE9D) < 8.0f) {
                    count++;
                }
            }

            if (is_point_inside_clip_volume(D_0013E633 + 0xE9D, data->f3C) != 0 && count == 0
                && (((Hero_2E08E8 *)(D_0013E633 + 0xE1D))->f208C < 2 || ((Hero_2E08E8 *)(D_0013E633 + 0xE1D))->f208C == 9)
                && ((Hero_2E08E8 *)(D_0013E633 + 0xE1D))->f2084 != 0x1E
                && (gHaveHeliPack + 0xD)[0] != 0
                && func_L00_00234718(0xF) >= 0x15
                && D_L03_00179590[0] == 0 && D_L03_00179590[9] == -1
                && (D_00141A68_2E08E8)[0x4A].count == 0
                && D_00141948_2E08E8[0x13].count == 0) {
                Help_Request(0x4E20, 0x4A);
            } else if (((Hero_2E08E8 *)(D_0013E633 + 0xE1D))->f2084 == 0x1E) {
                Help_2E08E8 *h = D_00141948_2E08E8;
                unsigned int c = h[0x13].count;
                if (c <= 0xFFFE) {
                    h[0x13].count = c + 1;
                }
                if (scale_ticks(D_0015EFA4) / 600 > h[0x13].time) {
                    h[0x13].time = scale_ticks(D_0015EFA4) / 600;
                }
                h[0x13].mask = h[0x13].mask | (1 << D_0015EE84) | 0x80000000;
            }
        }

        if (is_point_inside_clip_volume(D_0013E633 + 0xE9D, data->f38) != 0
            && (((Hero_2E08E8 *)(D_0013E633 + 0xE1D))->f208C < 2 || ((Hero_2E08E8 *)(D_0013E633 + 0xE1D))->f208C == 9)
            && D_L03_0015F76C < 3
            && D_L03_00179590[0] == 0 && D_L03_00179590[9] == -1) {
            Help_2E08E8 *b = D_00141A68_2E08E8;
            if (b[0x40].count == 0) {
                Help_Request(0x3EC, 0x40);
            }
        }

        if (is_point_inside_clip_volume(D_0013E633 + 0xE9D, data->f38) != 0
            && (((Hero_2E08E8 *)(D_0013E633 + 0xE1D))->f208C < 2 || ((Hero_2E08E8 *)(D_0013E633 + 0xE1D))->f208C == 9)
            && ((Hero_2E08E8 *)(D_0013E633 + 0xE1D))->f2084 == 1
            && D_L03_0015F768 == -1
            && D_L03_00179590[0] == 0 && D_L03_00179590[9] == -1) {
            Help_2E08E8 *b = D_00141A68_2E08E8;
            if (b[0x40].count != 0 && b[0x41].count == 0) {
                Help_Request(0x3ED, 0x41);
            }
        }

        if (is_point_inside_clip_volume(D_0013E633 + 0xE9D, data->f40) != 0
            && (((Hero_2E08E8 *)(D_0013E633 + 0xE1D))->f208C < 2 || ((Hero_2E08E8 *)(D_0013E633 + 0xE1D))->f208C == 9)
            && D_L03_00179590[0] == 0 && D_L03_00179590[9] == -1) {
            Help_2E08E8 *b = D_00141A68_2E08E8;
            if (b[0x54].count == 0) {
                Help_Request(0xBC0, 0x54);
            }
        }

        if (D_L03_0015F6A8 == 0 && (gHavePersuader + 0x11)[0] != 0
            && D_L03_00179590[0] == 0 && D_L03_00179590[9] == -1) {
            Help_2E08E8 *b = D_00141A68_2E08E8;
            if (b[0x19].count == 0) {
                Help_Request(0xBBD, 0x19);
            }
        }

        if (is_point_inside_clip_volume(D_0013E633 + 0xE9D, data->f34) != 0) {
            Help_2E08E8 *h = D_00141948_2E08E8;
            if (h[0xF].count == 0
                && (((Hero_2E08E8 *)(D_0013E633 + 0xE1D))->f208C < 2 || ((Hero_2E08E8 *)(D_0013E633 + 0xE1D))->f208C == 9)) {
                int n;
                h[0xF].count++;
                n = scale_ticks(D_0015EFA4) / 600;
                if (h[0xF].time < n) {
                    h[0xF].time = scale_ticks(D_0015EFA4) / 600;
                }
                h[0xF].mask = h[0xF].mask | (1 << D_0015EE84) | 0x80000000;
            }
        }

        if (((Hero_2E08E8 *)(D_0013E633 + 0xE1D))->f988 != 0 && D_00141948_2E08E8[0xF].count == 0) {
            ((Hero_2E08E8 *)(D_0013E633 + 0xE1D))->f988 = 0;
            data->f54++;
        }
        if (D_00141948_2E08E8[0xF].count == 0
            && (((Hero_2E08E8 *)(D_0013E633 + 0xE1D))->f208C < 2 || ((Hero_2E08E8 *)(D_0013E633 + 0xE1D))->f208C == 9)
            && data->f54 >= 3
            && D_L03_00179590[0] == 0 && D_L03_00179590[9] == -1) {
            Help_2E08E8 *b = D_00141A68_2E08E8;
            if (b[0x1A].count == 0) {
                Help_Request(0xBBE, 0x1A);
            }
        }

        if (((Hero_2E08E8 *)(D_0013E633 + 0xE1D))->f2084 == 0x74) {
            Help_2E08E8 *h = D_00141948_2E08E8;
            if (h[0x10].count == 0) {
                int n;
                h[0x10].count++;
                n = scale_ticks(D_0015EFA4) / 600;
                if (h[0x10].time < n) {
                    h[0x10].time = scale_ticks(D_0015EFA4) / 600;
                }
                h[0x10].mask = h[0x10].mask | (1 << D_0015EE84) | 0x80000000;
            }
        }

        if (is_point_inside_clip_volume(D_0013E633 + 0xE9D, data->f2C) != 0 && D_00141948_2E08E8[0x10].count == 0
            && ((Hero_2E08E8 *)(D_0013E633 + 0xE1D))->f208C == 6 && ((Hero_2E08E8 *)(D_0013E633 + 0xE1D))->f10B8 == 8
            && D_L03_00179590[0] == 0 && D_L03_00179590[9] == -1) {
            Help_2E08E8 *b = D_00141A68_2E08E8;
            if (b[0x1B].count == 0) {
                Help_Request(0xBBF, 0x1B);
            }
        }

        if (is_point_inside_clip_volume(D_0013E633 + 0xE9D, data->f44) != 0
            && (((Hero_2E08E8 *)(D_0013E633 + 0xE1D))->f208C < 2 || ((Hero_2E08E8 *)(D_0013E633 + 0xE1D))->f208C == 9)
            && D_L03_00179590[0] == 0 && D_L03_00179590[9] == -1) {
            Help_2E08E8 *b = D_00141A68_2E08E8;
            if (b[0x79].count == 0) {
                Help_Request(0x4E2F, 0x79);
            }
        }

        if (is_point_inside_clip_volume(D_0013E633 + 0xE9D, data->f7C) != 0
            && ((Hero_2E08E8 *)(D_0013E633 + 0xE1D))->f208C < 2) {
            Help_2E08E8 *b = D_00141A68_2E08E8;
            if (b[0x4F].count == 0 && D_00141948_2E08E8[0x14].count == 0) {
                int count = 0;
                int i;
                for (i = 0; i < 37; i++) {
                    if (D_L03_00179C40[i].active == 0 && i != 8 && i != 24) {
                        if ((D_0013D50F + 0xB9)[i] != 0) {
                            count++;
                        }
                    }
                }
                if (count >= 2) {
                    Help_Request(0x4E25, 0x4F);
                }
            }
        }

        if (is_point_inside_clip_volume(D_0013E633 + 0xE9D, data->f70) != 0) {
            unsigned char *g = D_0013D355 + 0x13B;
            g[0x18] = 1;
        }
        if (is_point_inside_clip_volume(D_0013E633 + 0xE9D, data->f74) != 0) {
            unsigned char *q = D_0013D50F + 1;
            if (q[3] == 0) {
                q[3] = 1;
                func_0022EE28(1, 0, 0);
                ShowBanner(0x53DB, -1);
            }
        }
        break;
    }
}
typedef u32 u128_E1598 __attribute__((mode(TI), aligned(16)));
typedef union {
    u128_E1598 q;
    f32 f[4];
    s32 i[4];
} Vec4_2E1598;
extern s32 D_L03_0015F6A8 MACRO_ADDR;
struct L03Cutscene {
    char pad0[0x30];
    int mode;
    int t;
    char pad38[0x140];
    char *mobys[4];
};
extern struct L03Cutscene D_L03_0016C9E0_2E1598 __asm__("D_L03_0016C9E0");
extern void func_L00_00264870(void *);
extern void func_L00_00250800(void *, int, void *);
extern int func_L00_00258BC8(int, int);
extern float func_002140F8(float, float);
extern void func_L00_0026DD70(void *, void *, int, int, float, int);

/* Starts the cutscene, then during mode 3 (frames 900-10000) emits two particle beams from the listed moby.
   Adapted from Lombyte (MIT) for PAL by OpenRAC's tools/port.py: src/overlays/l03/gameplay/vendor/002df520.c, FUN_L03_002e01d0. */
void func_L03_002E1598(char *m) {
    char *moby;
    float from[4];
    float to[4];
    Vec4_2E1598 zero;

    switch (*(unsigned char *)(m + 0x20)) {
    case 0:
        *(unsigned char *)(m + 0x30) = 0xFF;
        m[0x20] = 1;
        break;
    case 1:
        if (D_L03_0015F6A8 != 2)
            break;
        if (D_L03_0016C9E0_2E1598.mode == 4 || D_L03_0016C9E0_2E1598.mode == 10) {
            int v = D_L03_0016C9E0_2E1598.mode;
            int i;
            i = 0;
            if (v == 4)
                i = 2;
            else if (v == 10)
                i = 0;
            func_L00_00264870(D_L03_0016C9E0_2E1598.mobys[i]);
        }
        if (D_L03_0015F6A8 != 2 || D_L03_0016C9E0_2E1598.mode != 3)
            break;
        if (D_L03_0016C9E0_2E1598.t < scale_ticks(900))
            break;
        if (D_L03_0016C9E0_2E1598.t > scale_ticks(10000))
            break;
        moby = D_L03_0016C9E0_2E1598.mobys[3];
        if (moby == 0)
            break;
        zero.q = 0;
        func_L00_00250800(moby, 0, from);
        func_L00_00250800(moby, 1, to);
        func_L00_0026DD70(from, &zero, 0x7F7F7F7F, 0x7F7F7F, random_float_between(0.25f, 0.5f) * 210000.0f,
                         scale_ticks(rand_range(45, 60)));
        func_L00_0026DD70(to, &zero, 0x407F7F7F, 0x7F7F7F, random_float_between(0.25f, 0.5f) * 210000.0f,
                         scale_ticks(rand_range(45, 60)));
        break;
    }
}
extern void func_0022ED80(int, int, int);
extern void func_L01_00279790(void *);
extern void func_L00_00264EA8(void *, int, int, int, int, int, int);
extern void func_L01_00279E10(void *, int);
extern void func_0020D678(void *);
void func_L03_002E3D10(char *m) {
    int hit = 0;
    char *r = func_L00_0025B478(m, 0x10000, 0);
    switch (*(unsigned char *)(m + 0x20)) {
    case 0:
        m[0x20] = 1;
        break;
    case 1:
        if (r != 0 && *(float *)(r + 0x2C) > 0.0f) hit = 1;
        if (hit) m[0x20] = 2;
        break;
    case 2:
        func_0022ED80(0, 0, (int)m);
        func_L01_00279790(m);
        func_L00_00264EA8(m, 0x725, 1, 0x725, 1, 1, 2);
        func_L01_00279E10(m, 0x724);
        DeleteMoby(m);
        break;
    }
}
INCLUDE_ASM("asm/overlays", func_L03_002ECBA8);
extern char D_0013E633[];
typedef struct CameraSmoothECD40 {
    float position[4]; int sourceFlag; float duration;
} CameraSmoothECD40;
typedef struct CameraZoomECD40 {
    float start, pad4, end, padC, weight;
} CameraZoomECD40;
typedef struct CameraOrientationECD40 {
    float vector[4]; char pad10[0x10];
    int flags20, flags24, flags28, flags2C, flags30;
    float height;
} CameraOrientationECD40;
typedef struct CameraDataECD40 {
    float position[4], motion[4]; float speed, acceleration;
    int state, pad2C, timer; char pad34[0x7C];
    CameraSmoothECD40 origin; char padC8[8];
    CameraZoomECD40 zoom; char padE4[0xC];
    CameraOrientationECD40 orientation;
} CameraDataECD40;
typedef struct CameraMobyECD40 {
    char pad0[0x70]; CameraDataECD40 *camera;
    char pad74[0xA]; short resetFlag;
    char pad80[4]; short index;
} CameraMobyECD40;
typedef struct CameraConfigECD40 {
    char pad0[0x20]; float range, weight;
} CameraConfigECD40;
typedef struct CameraEntryECD40 {
    char pad0[0x10]; float rotation[3]; CameraConfigECD40 *config;
} CameraEntryECD40;
extern CameraEntryECD40 *D_L03_0015F050_camera __asm__("D_L03_0015F050") MACRO_ADDR;

extern int D_L03_001670F4;
extern void func_001F9BC0(void *);
extern void func_001FA1F8(void *, void *);
extern void func_L03_002ECBA8(void *);
extern int func_001F9850(int);

/* ActivateCamera_14: seed the camera's smoothing state from the current camera table entry */
void func_L03_002ECD40(char *m) {
    CameraMobyECD40 *mob = (CameraMobyECD40 *)m;
    char *g = D_0013E633 + 0xE1D;
    CameraConfigECD40 *e = D_L03_0015F050_camera[mob->index].config;
    CameraSmoothECD40 *d1;
    CameraZoomECD40 *v;
    CameraDataECD40 *a;
    CameraDataECD40 *b;
    CameraOrientationECD40 *c;
    CameraEntryECD40 *dd;
    float t, height;
    float buf[16];
    d1 = &mob->camera->origin;
    d1->duration = 1.5f;
    d1->sourceFlag = *(int *)(g + 0x2080);
    qcopy(d1, g + 0x80);
    *(int *)&d1->position[3] = 0;
    v = &mob->camera->zoom;
    t = e->range;
    v->end = t;
    v->start = t;
    v->weight = e->weight;
    a = mob->camera;
    a->state = 0;
    a->speed = 0.01f;
    a->acceleration = 0.2f;
    clear_u64_value(a->motion);
    qcopy(a, g + 0x80);
    b = mob->camera;
    b->timer = scale_ticks(0x78);
    dd = D_L03_0015F050_camera;
    c = &mob->camera->orientation;
    c->flags30 = 0;
    c->flags28 = 0;
    c->flags2C = 0;
    height = *(float *)(g + 0x88);
    c->flags20 = 0;
    c->height = height;
    c->flags24 = 0;
    {
        int entry = mob->index << 5;
        entry += (int)dd;
        entry += 0x10;
        buf[12] = *(float *)(entry + 0);
        buf[13] = *(float *)(entry + 4);
        buf[14] = *(float *)(entry + 8);
    }
    *(int *)(buf + 15) = 0;
    func_001FA1F8(buf, buf + 12);
    qcopy(c, buf);
    func_L03_002ECBA8(m);
    mob->resetFlag = 0;
    D_L03_001670F4 = 0x78;
}
extern void func_L00_001FF4B0(void *, void *, float);
extern float func_001EC120(void *, float, float, float, float, float);
extern void func_001F9BD8(void *, void *, void *);
extern char D_0013E633[];

// Smooths a camera-like moby's position toward the player's and sets its orientation vector.
void func_L03_002ECEC8(void *arg) {
    char *m = arg;
    char *d = *(char **)(m + 0x70);
    char *a = d + 0xD0;
    char *b = d + 0xF0;
    char *g = D_0013E633 + 0xE1D;
    float v3[4];
    float v1[4];
    float v2[4];
    char *h;
    if (*(int *)(g + 0x2284) != 0x50 || *(int *)(g + 0x2084) == 0x11) {
        *(float *)(b + 0x34) = *(float *)(g + 0x88);
    }
    func_L00_001FF4B0(v1, D_0013E633 + 0x10AD, -*(float *)(a + 0x10));
    func_L00_001FF4B0(v3, b, -*(float *)a);
    h = D_0013E633 + 0xE1D;
    *(float *)d = Cam_InterpValues(d + 0x10, *(float *)d, *(float *)(h + 0x80), *(float *)(d + 0x20), *(float *)(d + 0x24), *(float *)(d + 0x28));
    *(float *)(d + 4) = Cam_InterpValues(d + 0x14, *(float *)(d + 4), *(float *)(h + 0x84), *(float *)(d + 0x20), *(float *)(d + 0x24), *(float *)(d + 0x28));
    *(float *)(d + 8) = Cam_InterpValues(d + 0x18, *(float *)(d + 8), *(float *)(b + 0x34), *(float *)(d + 0x20), *(float *)(d + 0x24), *(float *)(d + 0x28));
    FastVecAdd(v2, d, v1);
    FastVecAdd(v2, v2, v3);
    *(float *)(m + 0x30) = v2[0];
    *(float *)(m + 0x34) = v2[1];
    *(float *)(m + 0x38) = v2[2];
}
extern char D_0013E633[];
extern float func_001EC120(void *, float, float, float, float, float);
extern void func_L00_001FF4B0(void *, void *, float);
extern void func_001F9BD8(void *, void *, void *);
extern void func_001F9BF0(void *, void *, void *);
extern void func_001F9CA0(void *, void *, void *);
extern short D_L03_00161EF0;
extern short D_L03_00161EF4;
extern char D_L03_00166FC0[];

/* smooths the moby's data floats and rebuilds its orientation axes */
void func_L03_002ED020(void *arg) {
    char *m = arg;
    char *d = *(char **)(m + 0x70);
    float *p = (float *)(d + 0xB0);
    float a[4];
    float b[4];
    float c[4];
    qcopy(b, d);
    p[2] = Cam_InterpValues(d + 0xBC, p[2], *(float *)(D_0013E633 + 0xEA5), *(float *)&D_L03_00161EF0, *(float *)&D_L03_00161EF4, 0.0f);
    func_L00_001FF4B0(c, D_L03_00166FC0, p[5]);
    FastVecAdd(b, c, b);
    FastVecSub(a, b, m + 0x30);
    func_L00_001FF4B0(m, a, 1.0f);
    qcopy(m + 0x40, m);
    FastVecCross(m + 0x10, m, D_L03_00166FC0 - 0x10);
    func_L00_001FF4B0(m + 0x10, m + 0x10, 1.0f);
    FastVecCross(m + 0x20, m + 0x10, m);
}
INCLUDE_ASM("asm/overlays", func_L03_002ED138);
extern void func_L03_002ECEC8(void *);
extern void func_001E9768(void *);
extern void func_L03_002ED020(void *);

void func_L03_002ED178(void *arg) {
    func_L03_002ECEC8(arg);
    func_001E9768(arg);
    func_L03_002ED020(arg);
}
extern int D_L03_0015F050 MACRO_ADDR;
extern char D_0013E633[];
extern int func_00215570(void *, int);

void func_L03_002ED1B0(char *moby)
{
    char *entry = (char *)((*(short *)(moby + 0x84) << 5) + D_L03_0015F050);
    char *sub = *(char **)(entry + 0x1C);
    int value = *(int *)(sub + 0xC);
    if (value >= 0 && is_point_inside_clip_volume(D_0013E633 + 0xE9D, value) == 0) {
        *(short *)(moby + 0x7E) = 3;
    }
}
