/* Level 18 code following vendor; generated by tools/overlay_src.py, stubs replaced by C as functions are matched. */
#include "common.h"
#include "include_asm.h"

INCLUDE_ASM("asm/overlays", func_L18_002F9D48);
INCLUDE_ASM("asm/overlays", func_L18_002FABE0);
INCLUDE_ASM("asm/overlays", func_L18_002FAEF8);
INCLUDE_ASM("asm/overlays", func_L18_002FB080);
INCLUDE_ASM("asm/overlays", func_L18_002FB318);
INCLUDE_ASM("asm/overlays", func_L18_002FB6B0);
INCLUDE_ASM("asm/overlays", func_L18_002FBAA0);
INCLUDE_ASM("asm/overlays", func_L18_002FBB88);
INCLUDE_ASM("asm/overlays", func_L18_002FBCE8);
typedef struct {
    char pad0[0x84];
    void *child;
} Level18VendorData;

typedef struct {
    char pad0[0x78];
    Level18VendorData *data;
    char pad7C[0x2A];
    short class_id;
} Level18VendorMoby;

extern void func_0020D678(void *);

/* Remove a vendor moby and any child it owns. */
void func_L18_002FBD40(Level18VendorMoby *moby) {
    if (moby->class_id == 0x630) {
        void *child = moby->data->child;
        if (child != 0) {
            func_0020D678(child);
        }
        func_0020D678(moby);
    }
}
INCLUDE_ASM("asm/overlays", func_L18_002FC188);
INCLUDE_ASM("asm/overlays", func_L18_002FD058);
INCLUDE_ASM("asm/overlays", func_L18_002FD5C0);
INCLUDE_ASM("asm/overlays", func_L18_002FD9A0);
INCLUDE_ASM("asm/overlays", func_L18_002FDB28);
INCLUDE_ASM("asm/overlays", func_L18_002FDCA0);
INCLUDE_ASM("asm/overlays", func_L18_002FDCC4);
INCLUDE_ASM("asm/overlays", func_L18_002FDD20);
INCLUDE_ASM("asm/overlays", func_L18_002FDF58);
int func_L18_002FE070(char *a) {
    int r = func_L00_002DCDA8(a);
    if (r == 0) {
        if (*(unsigned char *)(a + 0x20) == 7) a[0x20] = 2;
    } else {
        a[0x20] = 7;
    }
    return r;
}
void func_L18_002FE1C0(unsigned char *arg) {
    unsigned short flags;
    arg[0x20] = 8;
    if (arg[0x53] != 0) {
        func_00213DE0(arg, 0, 0, func_001F9850(10));
    }
    flags = *(unsigned short *)(arg + 0x34);
    arg[0x31] = 0;
    flags |= 1;
    *(int *)(arg + 0x94) = 0;
    flags &= 0xEFFF;
    *(unsigned short *)(arg + 0x34) = flags;
}
