/* Level 04 (Eudora) code following vuchain; generated by tools/overlay_src.py, stubs replaced by C as functions are matched. */
#include "common.h"
#include "include_asm.h"

INCLUDE_ASM("asm/overlays", func_L04_00293490);
INCLUDE_ASM("asm/overlays", func_L04_00293530);
INCLUDE_ASM("asm/overlays", func_L04_00293578);
INCLUDE_ASM("asm/overlays", func_L04_00293990);
INCLUDE_ASM("asm/overlays", func_L04_002939E8);
INCLUDE_ASM("asm/overlays", func_L04_00293F08);
INCLUDE_ASM("asm/overlays", func_L04_00296938);
INCLUDE_ASM("asm/overlays", func_L04_00296FA8);
