#!/usr/bin/env python3
"""
asm/overlays/<name>.s for every "shared" or "level" function in
config/overlays/functions.tsv (docs/OVERLAYS.md, "Plan" step 1).

  python3 tools/overlays.py dump      # if not already done
  python3 tools/overlay_asm.py

Needs baserom/overlays/level_NN/{text.bin,manifest.json} (tools/overlays.py
dump) and config/overlays/functions.tsv (tools/overlays.py catalogue).

For each level, this builds a splat-compatible file-splits csv with one
entry per place the catalogue found in that level's text (so every byte of
the level's text is accounted for; gaps -- mostly the trailing zero words
the catalogue's fingerprinting trims off the end of a function -- get an
unnamed filler entry) plus a symbol_addrs file naming every one of those
places with its catalogue name. spimdisasm (run inside the build
container: bash tools/docker/run.sh) is then asked, once per level, to
disassemble the whole text against that forced split -- so its own
function-boundary heuristics never second-guess the catalogue. That
matters here: some catalogued "functions" are a handful of bytes of linker
remnant with no `jr $ra`, which spimdisasm's own analysis would normally
fold into whichever real function comes before them (emitted as a mid
function `alabel` instead of a new `glabel`) unless the boundary is
physically forced like this.

Only the file for each function's *canonical* (level, address) -- see
docs/OVERLAYS.md, "Names" -- is kept, under asm/overlays/<name>.s. Any
name spimdisasm invented on its own (never declared in a symbol_addrs
file) is left as the executable's own func_/D_ addressing when its address
is below 0x15F000 (the resident core, shared unchanged by every level), or
requalified as func_LNN_/D_LNN_/jtbl_LNN_ using the generating level's
number when it is 0x15F000 or above (that level's own lit/bss/data/vtbl
range). This is exactly the docs' "Names" rule, applied after the fact: an
autogenerated name is marked with a throwaway suffix while spimdisasm
still knows which symbols it invented, and the suffix is peeled off (and
the name requalified) once the disassembly is in hand.

The executable's own asm post-processing is re-run over the result:
tools/fix_vu0_macro.py, tools/sn_regnames.py, tools/fix_denormal_floats.py.

JUMP TABLES: a function whose canonical body dispatches through a jump
table (spimdisasm emits a `jtbl_.../jlabel_...` reference) is left out
here rather than guessing at the executable's jump-table pipeline; see the
printed summary and build-sn/overlays/asm_work/skipped_jumptables.txt for
the list.

Scratch input/output for spimdisasm lives under
build-sn/overlays/asm_work/ (not tracked, safe to delete between runs).
"""
import csv
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CATALOGUE = ROOT / "config/overlays/functions.tsv"
DUMP = ROOT / "baserom/overlays"
OUT = ROOT / "asm/overlays"
WORK = ROOT / "build-sn/overlays/asm_work"
DOCKER_RUN = ROOT / "tools/docker/run.sh"
# The post-processing scripts use 3.10+ syntax (`str | None`); this repo's
# host convention is /opt/homebrew/bin/python3 (see docs/claude-memory),
# falling back to whatever ran this script if that is not present.
HOST_PYTHON = "/opt/homebrew/bin/python3" if Path("/opt/homebrew/bin/python3").exists() else sys.executable

RESIDENT_MAX = 0x15F000          # below this: resident core, keeps the executable's names
SUFFIX = "_OVLAUTOGEN"           # marks a spimdisasm-autogenerated name until we requalify it

SYM_RE = re.compile(rf"\b(D_|func_|jtbl_|jlabel_)([0-9A-Fa-f]{{8}}){re.escape(SUFFIX)}\b")
LOCAL_RE = re.compile(rf"(\.L[0-9A-Fa-f]+){re.escape(SUFFIX)}")
SIZE_RE = re.compile(r"nonmatching\s+\S+,\s*(0x[0-9A-Fa-f]+)")


def parse_catalogue():
    rows = []
    with CATALOGUE.open() as f:
        for line in f:
            line = line.rstrip("\n")
            if not line or line.startswith("#"):
                continue
            name, kind, size, _fp, _nlevels, places = line.split("\t")
            place_list = []
            for p in places.split(","):
                lv, addr = p.split(":")
                place_list.append((int(lv), int(addr, 16)))
            rows.append({"name": name, "kind": kind, "size": int(size), "places": place_list})
    return rows


def level_ids():
    return sorted(int(p.name.split("_")[1]) for p in DUMP.glob("level_*") if (p / "manifest.json").exists())


def build_level_data(rows):
    """level -> {address: (name, size)} for every place in that level, and
    name -> (level, address, size, kind) for the canonical place of every
    shared/level row."""
    level_entries: dict[int, dict[int, tuple[str, int]]] = {}
    targets = {}
    for row in rows:
        places = row["places"]
        canonical = min(places)
        if row["kind"] in ("shared", "level"):
            targets[row["name"]] = (canonical[0], canonical[1], row["size"], row["kind"])
        for lv, addr in places:
            entries = level_entries.setdefault(lv, {})
            if addr in entries:
                raise SystemExit(f"level {lv:02d}: duplicate function start at {addr:08X} "
                                  f"({entries[addr][0]} and {row['name']})")
            entries[addr] = (row["name"], row["size"])
    return level_entries, targets


def level_manifest(lv):
    return json.loads((DUMP / f"level_{lv:02d}/manifest.json").read_text())


def text_record(manifest):
    return next(r for r in manifest["records"] if r["name"] == "text")


def build_boundaries(entries, text_addr, text_end):
    """[(address, name_or_None, size)] tiling [text_addr, text_end) exactly.
    name is None for filler gaps: mostly the trailing zero words the
    catalogue's fingerprinting trims off a function's declared size, or
    (at the very start of a level's text) a few words of alignment
    padding before the first real function."""
    items = sorted(entries.items())
    out = []
    cur = text_addr
    for addr, (name, size) in items:
        if addr < cur:
            raise SystemExit(f"overlapping function start at {addr:08X} (cur {cur:08X})")
        if addr > cur:
            out.append((cur, None, addr - cur))
        out.append((addr, name, size))
        cur = addr + size
    if cur < text_end:
        out.append((cur, None, text_end - cur))
    elif cur > text_end:
        raise SystemExit(f"function runs past end of text: {cur:08X} > {text_end:08X}")
    return out


def write_level_inputs(boundaries, text_addr, text_end, level_dir):
    level_dir.mkdir(parents=True, exist_ok=True)
    csv_path = level_dir / "splits.csv"
    sym_path = level_dir / "symbols.txt"
    with csv_path.open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["0", format(text_addr, "X"), ".text"])
        for addr, name, _size in boundaries:
            fname = f"gap{addr:08X}" if name is None else f"f{addr:08X}"
            w.writerow([format(addr - text_addr, "X"), format(addr, "X"), fname])
        w.writerow([format(text_end - text_addr, "X"), format(text_end, "X"), ".end"])
    with sym_path.open("w") as f:
        for addr, name, size in boundaries:
            if name is not None:
                f.write(f"{name} = 0x{addr:X}; // type:func size:0x{size:X}\n")
    return csv_path, sym_path


def _run_jobs(jobs):
    """Needs spimdisasm (only installed in the build container). One process,
    one call per level -- avoids re-starting the container or re-parsing
    each level's symbol_addrs per function."""
    from spimdisasm.singleFileDisasm.SingleFileDisasmInternals import (  # type: ignore
        getArgsParser, processArguments)

    parser = getArgsParser()
    for job in jobs:
        argv = [
            job["text_bin"], job["out_whole"],
            "--vram", job["vram"],
            "--start", "0x0",
            "--end", job["end"],
            "--file-splits", job["splits"],
            "--split-functions", job["out_split"],
            "--symbol-addrs", job["symbols"],
            "--instr-category", "r5900",
            "--compiler", "EEGCC",
            "--endian", "little",
            "--opcode-ljust", "10",
            "--custom-suffix", SUFFIX,
            "--no-glabel-count",
            "--no-use-fpccsr",
            "--no-cop0-named-registers",
            "--no-name-vars-by-section",
            "--no-name-vars-by-type",
            "--no-name-vars-by-file",
            "--quiet",
        ]
        args = parser.parse_args(argv)
        rc = processArguments(args)
        if rc:
            sys.exit(f"level {job['level']:02d}: spimdisasm exited {rc}")
        print(f"level {job['level']:02d}: disassembled")


def _worker_main(jobs_path):
    _run_jobs(json.loads(Path(jobs_path).read_text()))


def _have_spimdisasm() -> bool:
    try:
        import spimdisasm  # noqa: F401
        return True
    except ImportError:
        return False


def qualify(content: str, level: int) -> str:
    """Peel the autogen suffix off, requalifying anything spimdisasm named
    on its own that falls in this level's own range (docs/OVERLAYS.md,
    "Names")."""
    def repl(m: re.Match) -> str:
        prefix, addr_hex = m.group(1), m.group(2)
        if int(addr_hex, 16) >= RESIDENT_MAX:
            return f"{prefix}L{level:02d}_{addr_hex}"
        return f"{prefix}{addr_hex}"
    content = SYM_RE.sub(repl, content)
    content = LOCAL_RE.sub(r"\1", content)
    return content


def generate(levels=None):
    rows = parse_catalogue()
    level_entries, targets = build_level_data(rows)
    ids = levels if levels is not None else level_ids()

    WORK.mkdir(parents=True, exist_ok=True)
    jobs = []
    canonical_paths: dict[str, tuple[Path, int, int]] = {}  # name -> (path, level, size)
    for lv in ids:
        manifest = level_manifest(lv)
        text = text_record(manifest)
        text_addr, text_size = text["address"], text["bytes"]
        boundaries = build_boundaries(level_entries.get(lv, {}), text_addr, text_addr + text_size)

        level_dir = WORK / f"level_{lv:02d}"
        csv_path, sym_path = write_level_inputs(boundaries, text_addr, text_addr + text_size, level_dir)
        split_dir = level_dir / "split"
        jobs.append({
            "level": lv,
            "text_bin": str(DUMP / f"level_{lv:02d}/text.bin"),
            "vram": hex(text_addr),
            "end": hex(text_size),
            "splits": str(csv_path),
            "symbols": str(sym_path),
            "out_whole": str(level_dir / "whole"),
            "out_split": str(split_dir),
        })
        for addr, name, size in boundaries:
            if name is not None and name in targets and targets[name][:2] == (lv, addr):
                canonical_paths[name] = (split_dir / f"f{addr:08X}" / f"{name}.s", lv, size)

    print(f"disassembling {len(jobs)} level(s) with spimdisasm (this can take a while)...")
    if _have_spimdisasm():
        # Already running where spimdisasm is installed (e.g. this script was
        # itself invoked inside the build container by tools/setup_asm.sh):
        # run in-process, no nested container needed.
        _run_jobs(jobs)
    else:
        jobs_path = WORK / "jobs.json"
        jobs_path.write_text(json.dumps(jobs))
        subprocess.run(
            ["bash", str(DOCKER_RUN), "python", str(Path(__file__).resolve()), "_worker", str(jobs_path)],
            cwd=ROOT, check=True)

    OUT.mkdir(parents=True, exist_ok=True)
    written, skipped_jtbl, missing, bad_size = [], [], [], []
    for name, (path, lv, size) in sorted(canonical_paths.items()):
        if not path.exists():
            missing.append(name)
            continue
        content = path.read_text()
        if "jtbl_" in content or "jlabel_" in content:
            skipped_jtbl.append(name)
            continue
        m = SIZE_RE.search(content)
        if not m or int(m.group(1), 16) != size:
            bad_size.append(name)
            continue
        content = qualify(content, lv)
        if targets[name][1] % 8:
            # Like the executable's asm: `.align 3` only where retail's
            # function starts on 8 bytes; here it would pad.
            content = content.replace(".align 3\n", "", 1)
        if SUFFIX in content:
            print(f"warning: {name}: autogen suffix survived requalification", file=sys.stderr)
        (OUT / f"{name}.s").write_text(content)
        written.append(name)

    if skipped_jtbl:
        (WORK / "skipped_jumptables.txt").write_text("\n".join(skipped_jtbl) + "\n")

    for script in ("fix_vu0_macro.py", "sn_regnames.py", "fix_denormal_floats.py"):
        subprocess.run([HOST_PYTHON, str(ROOT / "tools" / script), str(OUT)], cwd=ROOT, check=True)

    print(f"wrote {len(written)} file(s) to {OUT.relative_to(ROOT)}")
    if skipped_jtbl:
        print(f"skipped {len(skipped_jtbl)} function(s) with a jump table "
              f"(see {(WORK / 'skipped_jumptables.txt').relative_to(ROOT)}): "
              + ", ".join(skipped_jtbl[:10]) + (", ..." if len(skipped_jtbl) > 10 else ""))
    if missing:
        print(f"MISSING (spimdisasm did not produce a file): {', '.join(missing)}", file=sys.stderr)
    if bad_size:
        print(f"BAD SIZE (nonmatching header size disagrees with the catalogue): {', '.join(bad_size)}",
              file=sys.stderr)
    if missing or bad_size:
        sys.exit(1)


def main():
    if len(sys.argv) >= 2 and sys.argv[1] == "_worker":
        _worker_main(sys.argv[2])
        return
    levels = None
    if len(sys.argv) >= 2 and sys.argv[1] == "--levels":
        levels = [int(x) for x in sys.argv[2].split(",")]
    generate(levels)


if __name__ == "__main__":
    main()
